// playground/examples/solid-text-align/toggle.tsx
import { Themes } from '@prosekit/themes'
import type { ParentProps } from 'solid-js'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  children,
}: ParentProps<{
  pressed: () => boolean
  disabled?: () => boolean
  onClick: () => void
}>) {
  return (
    <button
      data-state={pressed() ? 'on' : 'off'}
      disabled={disabled?.()}
      onClick={() => onClick()}
      onMouseDown={(event) => event.preventDefault()}
      class={Themes.TOGGLE_BUTTON}
    >
      {children}
    </button>
  )
}

// playground/examples/preact-readonly/toggle.tsx
import { Themes } from '@prosekit/themes'
import type { ComponentChild } from 'preact'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  children,
}: {
  pressed: boolean
  disabled?: boolean
  onClick: VoidFunction
  children: ComponentChild
}) {
  return (
    <button
      data-state={pressed ? 'on' : 'off'}
      disabled={disabled}
      onClick={() => onClick()}
      onMouseDown={(event) => event.preventDefault()}
      class={Themes.TOGGLE_BUTTON}
    >
      {children}
    </button>
  )
}
