// website/src/examples/solid/solid-example.ts
import type { JSX } from 'solid-js'
import h from 'solid-js/h'

import { loaders } from './loaders.gen'

export function SolidExample(props: { story: string }): JSX.Element | JSX.FunctionElement {
  const Example = loaders[props.story as keyof typeof loaders]
  return Example ? h(Example, null) : null
}

// playground/examples/svelte/example.svelte
<script lang="ts">
import { onMount } from 'svelte'
import { loaders } from './loaders.gen'

export let story: string = ''

let loader: (typeof loaders)[keyof typeof loaders] | undefined

onMount(() => {
  loader = loaders[story as keyof typeof loaders]
})
</script>

{#if loader}
  {#await loader() then { default: LazyComponent }}
    <LazyComponent />
  {/await}
{/if}
