// playground/examples/svelte-slash-menu/App.svelte
<script lang="ts">
import 'prosekit/basic/style.css'
import 'prosekit/extensions/placeholder/style.css'

import { createEditor } from 'prosekit/core'
import { defineExampleExtension } from './extension'
import { onMount } from 'svelte'
import { ProseKit } from 'prosekit/svelte'
import SlashMenu from './SlashMenu.svelte'

const editor = createEditor({ extension: defineExampleExtension() })

let place: HTMLDivElement
onMount(() => editor.mount(place))
</script>

<ProseKit {editor}>
  <div bind:this={place} class="EDITOR_CONTENT"></div>
  <SlashMenu />
</ProseKit>

// playground/examples/vue-toolbar/App.vue
<script setup lang="ts">
import 'prosekit/basic/style.css'
import 'prosekit/extensions/placeholder/style.css'

import { watchPostEffect, ref } from 'vue'
import { ProseKit } from 'prosekit/vue'
import { defineExampleExtension } from './extension'
import Toolbar from './Toolbar.vue'
import { createEditor } from 'prosekit/core'

const editor = createEditor({ extension: defineExampleExtension() })
const editorRef = ref<HTMLDivElement | null>(null)
watchPostEffect(() => editor.mount(editorRef.value))
</script>

<template>
  <ProseKit :editor="editor">
    <div ref="editorRef" class="EDITOR_CONTENT"></div>
    <Toolbar />
  </ProseKit>
</template>
