// registry/src/solid/loaders.gen.ts
// This file is generated from update-loader.ts
import { lazy } from 'solid-js'

export const loaders = {
  'block-handle': lazy(() => import('./examples/block-handle').then((m) => ({ default: m.ExampleEditor }))),
  'blockquote': lazy(() => import('./examples/blockquote').then((m) => ({ default: m.ExampleEditor }))),
  'bold': lazy(() => import('./examples/bold').then((m) => ({ default: m.ExampleEditor }))),
  'change-tracking': lazy(() => import('./examples/change-tracking').then((m) => ({ default: m.ExampleEditor }))),
  'code': lazy(() => import('./examples/code').then((m) => ({ default: m.ExampleEditor }))),
  'code-block': lazy(() => import('./examples/code-block').then((m) => ({ default: m.ExampleEditor }))),
  'code-block-themes': lazy(() => import('./examples/code-block-themes').then((m) => ({ default: m.ExampleEditor }))),
  'drop-cursor': lazy(() => import('./examples/drop-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'emoji-rules': lazy(() => import('./examples/emoji-rules').then((m) => ({ default: m.ExampleEditor }))),
  'full': lazy(() => import('./examples/full').then((m) => ({ default: m.ExampleEditor }))),
  'gap-cursor': lazy(() => import('./examples/gap-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'hard-break': lazy(() => import('./examples/hard-break').then((m) => ({ default: m.ExampleEditor }))),
  'heading': lazy(() => import('./examples/heading').then((m) => ({ default: m.ExampleEditor }))),
  'horizontal-rule': lazy(() => import('./examples/horizontal-rule').then((m) => ({ default: m.ExampleEditor }))),
  'image-view': lazy(() => import('./examples/image-view').then((m) => ({ default: m.ExampleEditor }))),
  'inline-menu': lazy(() => import('./examples/inline-menu').then((m) => ({ default: m.ExampleEditor }))),
  'italic': lazy(() => import('./examples/italic').then((m) => ({ default: m.ExampleEditor }))),
  'keymap': lazy(() => import('./examples/keymap').then((m) => ({ default: m.ExampleEditor }))),
  'link': lazy(() => import('./examples/link').then((m) => ({ default: m.ExampleEditor }))),
  'list': lazy(() => import('./examples/list').then((m) => ({ default: m.ExampleEditor }))),
  'list-custom-checkbox': lazy(() => import('./examples/list-custom-checkbox').then((m) => ({ default: m.ExampleEditor }))),
  'minimal': lazy(() => import('./examples/minimal').then((m) => ({ default: m.ExampleEditor }))),
  'placeholder': lazy(() => import('./examples/placeholder').then((m) => ({ default: m.ExampleEditor }))),
  'readonly': lazy(() => import('./examples/readonly').then((m) => ({ default: m.ExampleEditor }))),
  'rtl': lazy(() => import('./examples/rtl').then((m) => ({ default: m.ExampleEditor }))),
  'strike': lazy(() => import('./examples/strike').then((m) => ({ default: m.ExampleEditor }))),
  'table': lazy(() => import('./examples/table').then((m) => ({ default: m.ExampleEditor }))),
  'text-align': lazy(() => import('./examples/text-align').then((m) => ({ default: m.ExampleEditor }))),
  'toolbar': lazy(() => import('./examples/toolbar').then((m) => ({ default: m.ExampleEditor }))),
  'typography': lazy(() => import('./examples/typography').then((m) => ({ default: m.ExampleEditor }))),
  'underline': lazy(() => import('./examples/underline').then((m) => ({ default: m.ExampleEditor }))),
  'unmount': lazy(() => import('./examples/unmount').then((m) => ({ default: m.ExampleEditor }))),
  'view-adapter': lazy(() => import('./examples/view-adapter').then((m) => ({ default: m.ExampleEditor }))),
}

// playground/examples/react/loaders.gen.ts
// This file is generated from gen-playground-pages.ts
import { lazy } from 'react'

export const loaders = {
  'minimal': lazy(() => import('./minimal/editor')),
  'block-handle': lazy(() => import('./block-handle/editor')),
  'blockquote': lazy(() => import('./blockquote/editor')),
  'change-tracking': lazy(() => import('./change-tracking/editor')),
  'code-block': lazy(() => import('./code-block/editor')),
  'code-block-themes': lazy(() => import('./code-block-themes/editor')),
  'full': lazy(() => import('./full/editor')),
  'gap-cursor': lazy(() => import('./gap-cursor/editor')),
  'heading': lazy(() => import('./heading/editor')),
  'horizontal-rule': lazy(() => import('./horizontal-rule/editor')),
  'image-view': lazy(() => import('./image-view/editor')),
  'inline-menu': lazy(() => import('./inline-menu/editor')),
  'keymap': lazy(() => import('./keymap/editor')),
  'link': lazy(() => import('./link/editor')),
  'list': lazy(() => import('./list/editor')),
  'loro': lazy(() => import('./loro/editor')),
  'mark-rule': lazy(() => import('./mark-rule/editor')),
  'placeholder': lazy(() => import('./placeholder/editor')),
  'readonly': lazy(() => import('./readonly/editor')),
  'save-html': lazy(() => import('./save-html/editor')),
  'save-json': lazy(() => import('./save-json/editor')),
  'save-markdown': lazy(() => import('./save-markdown/editor')),
  'search': lazy(() => import('./search/editor')),
  'slash-menu': lazy(() => import('./slash-menu/editor')),
  'table': lazy(() => import('./table/editor')),
  'toolbar': lazy(() => import('./toolbar/editor')),
  'unmount': lazy(() => import('./unmount/editor')),
  'user-menu': lazy(() => import('./user-menu/editor')),
  'user-menu-dynamic': lazy(() => import('./user-menu-dynamic/editor')),
  'word-counter': lazy(() => import('./word-counter/editor')),
  'yjs': lazy(() => import('./yjs/editor')),
}
