// playground/examples/vue-full/block-handle.vue
<script setup lang="ts">
import { useEditor } from 'prosekit/vue'
import { BlockDragHandle, BlockPopover } from 'prosekit/vue/block-handle'

const editor = useEditor()
</script>

<template>
  <BlockPopover class="BLOCK_HANDLE">
    <BlockDragHandle>
      <div class="ICON_DRAG_HANDLE"></div>
    </BlockDragHandle>
  </BlockPopover>
</template>

// playground/examples/react/block-handle/block-handle.tsx
import { Themes } from "@prosekit/themes";
import { BlockDragHandle, BlockPopover } from 'prosekit/react/block-handle'

export default function BlockHandle() {
  return (
    <BlockPopover className={Themes.BLOCK_HANDLE}>
      <BlockDragHandle>
        <div className={Themes.ICON_DRAG_HANDLE} />
      </BlockDragHandle>
    </BlockPopover>
  )
}
