// playground/examples/svelte-bold/button.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
export let pressed: boolean = false 
export let disabled: boolean = false
export let onClick: VoidFunction
</script>

<button
  data-state={pressed ? 'on' : 'off'}
  disabled={disabled ? true : undefined}
  on:click={onClick}
  on:mousedown|preventDefault
  class={Themes.TOGGLE_BUTTON}
>
  <slot />
</button>

// playground/examples/solid-text-align/button.tsx
import { Themes } from '@prosekit/themes'
import type { ParentProps } from 'solid-js'

export default function Button({
  pressed,
  disabled,
  onClick,
  children,
}: ParentProps<{
  pressed: () => boolean
  disabled?: () => boolean
  onClick: () => void
}>) {
  return (
    <button
      data-state={pressed() ? 'on' : 'off'}
      disabled={disabled?.()}
      onClick={() => onClick()}
      onMouseDown={(event) => event.preventDefault()}
      class={Themes.TOGGLE_BUTTON}
    >
      {children}
    </button>
  )
}
