// playground/examples/vue-full/InlineMenu.vue
<script setup lang="ts">
import { useEditor } from 'prosekit/vue'
import { InlinePopover } from 'prosekit/vue/inline-popover'
import InlineButtons from './InlineButtons.vue'

const editor = useEditor()
</script>

<template>
  <InlinePopover class="INLINE_MENU" :editor="editor">
    <InlineButtons />
  </InlinePopover>
</template>

// playground/examples/react-inline-menu/InlineMenu.tsx
import { useEditor } from 'prosekit/react'
import { InlinePopover } from 'prosekit/react/inline-popover'

import InlineButtons from './InlineButtons'

export default function InlineMenu() {
  const editor = useEditor()

  return (
    <InlinePopover className="INLINE_MENU" editor={editor}>
      <InlineButtons />
    </InlinePopover>
  )
}
