// registry/src/svelte/ui/inline-menu/inline-menu.svelte
<script lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import type { Editor } from 'prosekit/core'
import type { LinkAttrs } from 'prosekit/extensions/link'
import type { EditorState } from 'prosekit/pm/state'
import { useEditor, useEditorDerivedValue } from 'prosekit/svelte'
import { InlinePopoverPopup, InlinePopoverPositioner, InlinePopoverRoot } from 'prosekit/svelte/inline-popover'

import { Button } from '../button'

function getInlineMenuItems(editor: Editor<BasicExtension>) {
  return {
    bold: editor.commands.toggleBold
      ? {
        isActive: editor.marks.bold.isActive(),
        canExec: editor.commands.toggleBold.canExec(),
        command: () => editor.commands.toggleBold(),
      }
      : undefined,
    italic: editor.commands.toggleItalic
      ? {
        isActive: editor.marks.italic.isActive(),
        canExec: editor.commands.toggleItalic.canExec(),
        command: () => editor.commands.toggleItalic(),
      }
      : undefined,
    underline: editor.commands.toggleUnderline
      ? {
        isActive: editor.marks.underline.isActive(),
        canExec: editor.commands.toggleUnderline.canExec(),
        command: () => editor.commands.toggleUnderline(),
      }
      : undefined,
    strike: editor.commands.toggleStrike
      ? {
        isActive: editor.marks.strike.isActive(),
        canExec: editor.commands.toggleStrike.canExec(),
        command: () => editor.commands.toggleStrike(),
      }
      : undefined,
    code: editor.commands.toggleCode
      ? {
        isActive: editor.marks.code.isActive(),
        canExec: editor.commands.toggleCode.canExec(),
        command: () => editor.commands.toggleCode(),
      }
      : undefined,
    link: editor.commands.addLink
      ? {
        isActive: editor.marks.link.isActive(),
        canExec: editor.commands.addLink.canExec({ href: '' }),
        command: () => editor.commands.expandLink(),
        currentLink: getCurrentLink(editor.state) || '',
      }
      : undefined,
  }
}

function getCurrentLink(state: EditorState): string | undefined {
  const from = state.selection.$from
  const marks = from.marksAcross(from)
  if (!marks) {
    return
  }
  for (const mark of marks) {
    if (mark.type.name === 'link') {
      return (mark.attrs as LinkAttrs).href
    }
  }
}

const editor = useEditor<BasicExtension>()
const items = useEditorDerivedValue(getInlineMenuItems)

let linkMenuOpen = $state(false)
function toggleLinkMenuOpen() {
  linkMenuOpen = !linkMenuOpen
}

function handleLinkUpdate(href?: string) {
  if (href) {
    $editor.commands.addLink({ href })
  } else {
    $editor.commands.removeLink()
  }

  linkMenuOpen = false
  $editor.focus()
}
</script>

<InlinePopoverRoot
  onOpenChange={(event) => {
    if (!event.detail) linkMenuOpen = false
  }}
>
  <InlinePopoverPositioner class="CSS_INLINE_MENU_POSITIONER">
    <InlinePopoverPopup
      data-testid="inline-menu-main"
      class="CSS_INLINE_MENU_MAIN"
    >
      {#if $items.bold}
        <Button
          pressed={$items.bold.isActive}
          disabled={!$items.bold.canExec}
          onClick={$items.bold.command}
          tooltip="Bold"
        >
          <div class="CSS_ICON_BOLD"></div>
        </Button>
      {/if}
      {#if $items.italic}
        <Button
          pressed={$items.italic.isActive}
          disabled={!$items.italic.canExec}
          onClick={$items.italic.command}
          tooltip="Italic"
        >
          <div class="CSS_ICON_ITALIC"></div>
        </Button>
      {/if}
      {#if $items.underline}
        <Button
          pressed={$items.underline.isActive}
          disabled={!$items.underline.canExec}
          onClick={$items.underline.command}
          tooltip="Underline"
        >
          <div class="CSS_ICON_UNDERLINE"></div>
        </Button>
      {/if}
      {#if $items.strike}
        <Button
          pressed={$items.strike.isActive}
          disabled={!$items.strike.canExec}
          onClick={$items.strike.command}
          tooltip="Strikethrough"
        >
          <div class="CSS_ICON_STRIKETHROUGH"></div>
        </Button>
      {/if}
      {#if $items.code}
        <Button
          pressed={$items.code.isActive}
          disabled={!$items.code.canExec}
          onClick={$items.code.command}
          tooltip="Code"
        >
          <div class="CSS_ICON_CODE"></div>
        </Button>
      {/if}
      {#if $items.link?.canExec && $items.link}
        <Button
          pressed={$items.link.isActive}
          onClick={() => {
            $items.link!.command()
            toggleLinkMenuOpen()
          }}
          tooltip="Link"
        >
          <div class="CSS_ICON_LINK"></div>
        </Button>
      {/if}
    </InlinePopoverPopup>
  </InlinePopoverPositioner>
</InlinePopoverRoot>

<InlinePopoverRoot
  defaultOpen={false}
  open={linkMenuOpen}
  onOpenChange={(event) => {
    linkMenuOpen = event.detail
  }}
>
  <InlinePopoverPositioner placement="bottom" class="CSS_INLINE_MENU_POSITIONER">
    <InlinePopoverPopup
      data-testid="inline-menu-link"
      class="CSS_INLINE_MENU_LINK"
    >
      {#if linkMenuOpen && $items.link}
        <form
          onsubmit={(event) => {
            event.preventDefault()
            const target = event.target as HTMLFormElement | null
            const href = target?.querySelector('input')?.value?.trim()
            handleLinkUpdate(href)
          }}
        >
          <input
            placeholder="Paste the link..."
            value={$items.link.currentLink || ''}
            class="CSS_INLINE_MENU_LINK_INPUT"
          />
        </form>
      {/if}
      {#if $items.link?.isActive}
        <button
          class="CSS_INLINE_MENU_LINK_REMOVE_BUTTON"
          onclick={() => handleLinkUpdate()}
          onmousedown={(e) => e.preventDefault()}
        >
          Remove link
        </button>
      {/if}
    </InlinePopoverPopup>
  </InlinePopoverPositioner>
</InlinePopoverRoot>

// registry/src/vue/ui/inline-menu/inline-menu.vue
<script setup lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import type { Editor } from 'prosekit/core'
import type { LinkAttrs } from 'prosekit/extensions/link'
import type { EditorState } from 'prosekit/pm/state'
import { useEditor, useEditorDerivedValue } from 'prosekit/vue'
import { InlinePopoverPopup, InlinePopoverPositioner, InlinePopoverRoot } from 'prosekit/vue/inline-popover'
import { ref } from 'vue'

import { Button } from '../button'

function getInlineMenuItems(editor: Editor<BasicExtension>) {
  return {
    bold: editor.commands.toggleBold
      ? {
        isActive: editor.marks.bold.isActive(),
        canExec: editor.commands.toggleBold.canExec(),
        command: () => editor.commands.toggleBold(),
      }
      : undefined,
    italic: editor.commands.toggleItalic
      ? {
        isActive: editor.marks.italic.isActive(),
        canExec: editor.commands.toggleItalic.canExec(),
        command: () => editor.commands.toggleItalic(),
      }
      : undefined,
    underline: editor.commands.toggleUnderline
      ? {
        isActive: editor.marks.underline.isActive(),
        canExec: editor.commands.toggleUnderline.canExec(),
        command: () => editor.commands.toggleUnderline(),
      }
      : undefined,
    strike: editor.commands.toggleStrike
      ? {
        isActive: editor.marks.strike.isActive(),
        canExec: editor.commands.toggleStrike.canExec(),
        command: () => editor.commands.toggleStrike(),
      }
      : undefined,
    code: editor.commands.toggleCode
      ? {
        isActive: editor.marks.code.isActive(),
        canExec: editor.commands.toggleCode.canExec(),
        command: () => editor.commands.toggleCode(),
      }
      : undefined,
    link: editor.commands.addLink
      ? {
        isActive: editor.marks.link.isActive(),
        canExec: editor.commands.addLink.canExec({ href: '' }),
        command: () => editor.commands.expandLink(),
        currentLink: getCurrentLink(editor.state) || '',
      }
      : undefined,
  }
}

function getCurrentLink(state: EditorState): string | undefined {
  const { $from } = state.selection
  const marks = $from.marksAcross($from)
  if (!marks) {
    return
  }
  for (const mark of marks) {
    if (mark.type.name === 'link') {
      return (mark.attrs as LinkAttrs).href
    }
  }
}

const editor = useEditor<BasicExtension>()
const items = useEditorDerivedValue(getInlineMenuItems)

const linkMenuOpen = ref(false)
function toggleLinkMenuOpen() {
  linkMenuOpen.value = !linkMenuOpen.value
}

function handleLinkUpdate(href?: string) {
  if (href) {
    editor.value.commands.addLink({ href })
  } else {
    editor.value.commands.removeLink()
  }

  linkMenuOpen.value = false
  editor.value.focus()
}
</script>

<template>
  <InlinePopoverRoot
    @open-change="(event) => {
      if (!event.detail) linkMenuOpen = false
    }"
  >
    <InlinePopoverPositioner class="CSS_INLINE_MENU_POSITIONER">
      <InlinePopoverPopup
        data-testid="inline-menu-main"
        class="CSS_INLINE_MENU_MAIN"
      >
        <Button
          v-if="items.bold"
          :pressed="items.bold.isActive"
          :disabled="!items.bold.canExec"
          tooltip="Bold"
          @click="items.bold.command"
        >
          <div class="CSS_ICON_BOLD"></div>
        </Button>
        <Button
          v-if="items.italic"
          :pressed="items.italic.isActive"
          :disabled="!items.italic.canExec"
          tooltip="Italic"
          @click="items.italic.command"
        >
          <div class="CSS_ICON_ITALIC"></div>
        </Button>
        <Button
          v-if="items.underline"
          :pressed="items.underline.isActive"
          :disabled="!items.underline.canExec"
          tooltip="Underline"
          @click="items.underline.command"
        >
          <div class="CSS_ICON_UNDERLINE"></div>
        </Button>
        <Button
          v-if="items.strike"
          :pressed="items.strike.isActive"
          :disabled="!items.strike.canExec"
          tooltip="Strikethrough"
          @click="items.strike.command"
        >
          <div class="CSS_ICON_STRIKETHROUGH"></div>
        </Button>
        <Button
          v-if="items.code"
          :pressed="items.code.isActive"
          :disabled="!items.code.canExec"
          tooltip="Code"
          @click="items.code.command"
        >
          <div class="CSS_ICON_CODE"></div>
        </Button>
        <Button
          v-if="items.link?.canExec && items.link"
          :pressed="items.link.isActive"
          tooltip="Link"
          @click="() => {
            items.link!.command()
            toggleLinkMenuOpen()
          }"
        >
          <div class="CSS_ICON_LINK"></div>
        </Button>
      </InlinePopoverPopup>
    </InlinePopoverPositioner>
  </InlinePopoverRoot>

  <InlinePopoverRoot
    v-if="items.link"
    :default-open="false"
    :open="linkMenuOpen"
    @open-change="(event) => {
      linkMenuOpen = event.detail
    }"
  >
    <InlinePopoverPositioner placement="bottom" class="CSS_INLINE_MENU_POSITIONER">
      <InlinePopoverPopup
        data-testid="inline-menu-link"
        class="CSS_INLINE_MENU_LINK"
      >
        <form
          v-if="linkMenuOpen"
          @submit.prevent="(event) => {
            const target = event.target as HTMLFormElement | null
            const href = target?.querySelector('input')?.value?.trim()
            handleLinkUpdate(href)
          }"
        >
          <input
            placeholder="Paste the link..."
            :value="items.link.currentLink || ''"
            class="CSS_INLINE_MENU_LINK_INPUT"
          >
        </form>
        <button
          v-if="items.link.isActive"
          class="CSS_INLINE_MENU_LINK_REMOVE_BUTTON"
          @click="() => handleLinkUpdate()"
          @mousedown.prevent
        >
          Remove link
        </button>
      </InlinePopoverPopup>
    </InlinePopoverPositioner>
  </InlinePopoverRoot>
</template>
