// packages/solid/src/hooks/use-editor-extension.ts
import type { Editor, Extension } from '@prosekit/core'
import { EditorNotFoundError } from '@prosekit/core'
import { createEffect, onCleanup, type Accessor } from 'solid-js'

import { useEditorContext } from '../contexts/editor-context'
import type { MaybeAccessor } from '../types'
import { toValue } from '../utils/to-value'

/**
 * @internal
 */
export function useEditorExtension(
  editorAccessor: MaybeAccessor<Editor> | undefined | null,
  extensionAccessor: Accessor<Extension | null>,
) {
  const editorContext = useEditorContext()

  createEffect(() => {
    const editor = toValue(editorAccessor) || toValue(editorContext)
    const extension = extensionAccessor()

    if (!editor) {
      throw new EditorNotFoundError()
    }
    if (extension) {
      onCleanup(editor.use(extension))
    }
  })
}

// packages/react-binding/src/hooks/use-editor-extension.ts
import { EditorNotFoundError, type Extension } from '@prosekit/core'
import { useEffect } from 'react'

import type { ReactBindingEditor } from '../editor/react-binding-editor.ts'

export function useEditorExtension(
  editor: ReactBindingEditor | null | undefined,
  extension: Extension | null,
): void {
  if (!editor) {
    throw new EditorNotFoundError()
  }

  useEffect(() => {
    if (extension) {
      return editor.use(extension)
    }
  }, [editor, extension])
}
