// registry/src/solid/examples/user-menu-dynamic/user-menu-dynamic.tsx
import { createSignal, type JSX } from 'solid-js'

import { UserMenu } from '../../ui/user-menu'

import { useUserQuery } from './use-user-query'

export default function UserMenuDynamic(): JSX.Element {
  const [query, setQuery] = createSignal('')
  const [open, setOpen] = createSignal(false)

  const { loading, users } = useUserQuery(query, open)

  return (
    <UserMenu
      users={users()}
      loading={loading()}
      onQueryChange={setQuery}
      onOpenChange={setOpen}
    />
  )
}

// registry/src/react/examples/user-menu-dynamic/user-menu-dynamic.tsx
import { useState } from 'react'

import { UserMenu } from '../../ui/user-menu'

import { useUserQuery } from './use-user-query'

export default function UserMenuDynamic() {
  const [query, setQuery] = useState('')
  const [open, setOpen] = useState(false)

  const { loading, users } = useUserQuery(query, open)

  return (
    <UserMenu
      users={users}
      loading={loading}
      onQueryChange={setQuery}
      onOpenChange={setOpen}
    />
  )
}
