// packages/solid/src/components/drop-indicator/drop-indicator.gen.ts
import { 
  type DropIndicatorElement,
  type DropIndicatorProps as Props,
  type DropIndicatorEvents as Events,
  dropIndicatorProps,
  dropIndicatorEvents,
} from '@prosekit/web/drop-indicator'
import type { Component } from 'solid-js'

import type { PropsWithElement } from '../../types.ts'
import { createComponent } from '../create-component.ts'
import type { CreateProps } from '../create-props.ts'

/**
 * Props for the {@link DropIndicator} component.
 */
export interface DropIndicatorProps extends Partial<CreateProps<Props, Events>> {}

export const DropIndicator: Component<PropsWithElement<
  DropIndicatorProps,
  DropIndicatorElement
>> = createComponent<
  DropIndicatorProps,
  DropIndicatorElement
>(
  'prosekit-drop-indicator', 
  Object.keys(dropIndicatorProps),
  Object.keys(dropIndicatorEvents),
)

// packages/react/src/components/drop-indicator/drop-indicator.gen.ts
import {
  type DropIndicatorElement,
  type DropIndicatorProps as Props,
  type DropIndicatorEvents as Events,
  dropIndicatorProps,
  dropIndicatorEvents,
} from '@prosekit/web/drop-indicator'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'
import type { CreateProps } from '../create-props'

/**
 * Props for the {@link DropIndicator} component.
 */
export interface DropIndicatorProps extends Partial<CreateProps<Props, Events>> {}
 
export const DropIndicator: ForwardRefExoticComponent<
  DropIndicatorProps &
  RefAttributes<DropIndicatorElement> &
  HTMLAttributes<DropIndicatorElement>
> = createComponent<
  DropIndicatorProps, 
  DropIndicatorElement
>(
  'prosekit-drop-indicator',
  'DropIndicator',
  Object.keys(dropIndicatorProps),
  Object.keys(dropIndicatorEvents),
)
