// packages/react/src/components/table-handle/table-cell-popover-item.gen.ts
import {
  TableCellPopoverItemElement,
  defaultTableCellPopoverItemProps,
  type TableCellPopoverItemProps,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'

export const TableCellPopoverItem: ForwardRefExoticComponent<
  Partial<TableCellPopoverItemProps> &
  RefAttributes<TableCellPopoverItemElement> &
  HTMLAttributes<TableCellPopoverItemElement>
> = createComponent<
  TableCellPopoverItemProps, 
  TableCellPopoverItemElement
>(
  'prosekit-table-cell-popover-item',
  'TableCellPopoverItem',
  defaultTableCellPopoverItemProps,
)

// packages/svelte/src/components/table-handle/table-cell-popover-item.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'
import { defaultTableCellPopoverItemProps } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useWebComponent } from '../../utils/use-web-component'

let attributes: Record<string, unknown> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useWebComponent(defaultTableCellPopoverItemProps)

$: {
  attributes = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-cell-popover-item {...attributes} bind:this={element}>
    <slot />
  </prosekit-table-cell-popover-item>
</ClientUpdate>
