// packages/react/src/components/table-handle/table-cell-popover-content.gen.ts
import {
  TableCellPopoverContentElement,
  defaultTableCellPopoverContentProps,
  type TableCellPopoverContentProps,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'

export const TableCellPopoverContent: ForwardRefExoticComponent<
  Partial<TableCellPopoverContentProps> &
  RefAttributes<TableCellPopoverContentElement> &
  HTMLAttributes<TableCellPopoverContentElement>
> = createComponent<
  TableCellPopoverContentProps, 
  TableCellPopoverContentElement
>(
  'prosekit-table-cell-popover-content',
  'TableCellPopoverContent',
  defaultTableCellPopoverContentProps,
)

// packages/svelte/src/components/table-handle/table-cell-popover-content.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'
import { defaultTableCellPopoverContentProps } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useWebComponent } from '../../utils/use-web-component'

let attributes: Record<string, unknown> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useWebComponent(defaultTableCellPopoverContentProps)

$: {
  attributes = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-cell-popover-content {...attributes} bind:this={element}>
    <slot />
  </prosekit-table-cell-popover-content>
</ClientUpdate>
