// packages/react/src/components/table-handle/table-row-popover-trigger.gen.ts
import {
  defaultTableRowPopoverTriggerProps,
  type TableRowPopoverTriggerElement,
  type TableRowPopoverTriggerProps
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'

export const TableRowPopoverTrigger: ForwardRefExoticComponent<
  Partial<TableRowPopoverTriggerProps> &
  RefAttributes<TableRowPopoverTriggerElement> &
  HTMLAttributes<TableRowPopoverTriggerElement>
> = createComponent<
  TableRowPopoverTriggerProps, 
  TableRowPopoverTriggerElement
>(
  'prosekit-table-row-popover-trigger',
  'TableRowPopoverTrigger',
  defaultTableRowPopoverTriggerProps,
)

// packages/svelte/src/components/table-handle/table-row-popover-trigger.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { defaultTableRowPopoverTriggerProps } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useWebComponent } from '../../utils/use-web-component'

let attributes: Record<string, unknown> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useWebComponent(defaultTableRowPopoverTriggerProps)

$: {
  attributes = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-row-popover-trigger {...attributes} bind:this={element}>
    <slot />
  </prosekit-table-row-popover-trigger>
</ClientUpdate>
