// registry/src/react/ui/user-menu/user-menu.tsx
import type { BasicExtension } from 'prosekit/basic'
import { canUseRegexLookbehind, type Union } from 'prosekit/core'
import type { MentionExtension } from 'prosekit/extensions/mention'
import { useEditor } from 'prosekit/react'
import {
  AutocompleteEmpty,
  AutocompleteItem,
  AutocompletePopup,
  AutocompletePositioner,
  AutocompleteRoot,
} from 'prosekit/react/autocomplete'

// Match inputs like "@", "@foo", "@foo bar" etc. Do not match "@ foo".
const regex = canUseRegexLookbehind() ? /(?<!\S)@(\S.*)?$/u : /@(\S.*)?$/u

export default function UserMenu(props: {
  users: { id: number; name: string }[]
  loading?: boolean
  onQueryChange?: (query: string) => void
  onOpenChange?: (open: boolean) => void
}) {
  const editor = useEditor<Union<[MentionExtension, BasicExtension]>>()

  const handleUserInsert = (id: number, username: string) => {
    editor.commands.insertMention({
      id: id.toString(),
      value: '@' + username,
      kind: 'user',
    })
    editor.commands.insertText({ text: ' ' })
  }

  return (
    <AutocompleteRoot
      regex={regex}
      onQueryChange={(event) => props.onQueryChange?.(event.detail)}
      onOpenChange={(event) => props.onOpenChange?.(event.detail)}
    >
      <AutocompletePositioner>
        <AutocompletePopup className="CSS_AUTOCOMPLETE_POPUP">
          <AutocompleteEmpty className="CSS_AUTOCOMPLETE_MENU_ITEM">
            {props.loading ? 'Loading...' : 'No results'}
          </AutocompleteEmpty>

          {props.users.map((user) => (
            <AutocompleteItem
              key={user.id}
              className="CSS_AUTOCOMPLETE_MENU_ITEM"
              onSelect={() => handleUserInsert(user.id, user.name)}
            >
              <span className={props.loading ? 'opacity-50' : undefined}>
                {user.name}
              </span>
            </AutocompleteItem>
          ))}
        </AutocompletePopup>
      </AutocompletePositioner>
    </AutocompleteRoot>
  )
}

// registry/src/vue/ui/user-menu/user-menu.vue
<script setup lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import { canUseRegexLookbehind, type Union } from 'prosekit/core'
import type { MentionExtension } from 'prosekit/extensions/mention'
import { useEditor } from 'prosekit/vue'
import { AutocompleteEmpty, AutocompleteItem, AutocompletePopup, AutocompletePositioner, AutocompleteRoot } from 'prosekit/vue/autocomplete'

const props = defineProps<{
  users: { id: number; name: string }[]
  loading?: boolean
  onQueryChange?: (query: string) => void
  onOpenChange?: (open: boolean) => void
}>()

const editor = useEditor<Union<[MentionExtension, BasicExtension]>>()

function handleUserInsert(id: number, username: string) {
  editor.value.commands.insertMention({
    id: id.toString(),
    value: '@' + username,
    kind: 'user',
  })
  editor.value.commands.insertText({ text: ' ' })
}

// Match inputs like "@", "@foo", "@foo bar" etc. Do not match "@ foo".
const regex = canUseRegexLookbehind() ? /(?<!\S)@(\S.*)?$/u : /@(\S.*)?$/u
</script>

<template>
  <AutocompleteRoot
    :regex="regex"
    @query-change="(event) => props.onQueryChange?.(event.detail)"
    @open-change="(event) => props.onOpenChange?.(event.detail)"
  >
    <AutocompletePositioner>
      <AutocompletePopup class="CSS_AUTOCOMPLETE_POPUP">
        <AutocompleteEmpty class="CSS_AUTOCOMPLETE_MENU_ITEM">
          {{ props.loading ? 'Loading...' : 'No results' }}
        </AutocompleteEmpty>

        <AutocompleteItem
          v-for="user in props.users"
          :key="user.id"
          class="CSS_AUTOCOMPLETE_MENU_ITEM"
          @select="() => handleUserInsert(user.id, user.name)"
        >
          <span v-if="props.loading" class="opacity-50">
            {{ user.name }}
          </span>
          <span v-else>
            {{ user.name }}
          </span>
        </AutocompleteItem>
      </AutocompletePopup>
    </AutocompletePositioner>
  </AutocompleteRoot>
</template>
