// playground/examples/svelte-code/button.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/svelte/tooltip'

export let pressed: boolean | undefined = undefined
export let disabled: boolean | undefined = undefined
export let tooltip: string | undefined = undefined
export let onClick: VoidFunction | undefined = undefined
</script>

<TooltipRoot>
  <TooltipTrigger class={Themes.TOOLTIP_TRIGGER}>
    <button
      data-state={pressed ? 'on' : 'off'}
      disabled={disabled ? true : undefined}
      on:click={onClick}
      on:mousedown|preventDefault
      class={Themes.TOGGLE_BUTTON}
    >
      <slot></slot>
      {#if tooltip}
        <span class="sr-only">{tooltip}</span>
      {/if}
    </button>
  </TooltipTrigger>
  <TooltipContent class={Themes.TOOLTIP_CONTENT}>
    {tooltip}
  </TooltipContent>
</TooltipRoot>

// playground/examples/vue-code-block/button.vue
<script setup lang="ts">
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/vue/tooltip'

defineProps<{
  pressed?: Boolean
  disabled?: Boolean
  tooltip?: string
  onClick?: VoidFunction
}>()
</script>

<template>
  <TooltipRoot>
    <TooltipTrigger :class="Themes.TOOLTIP_TRIGGER">
      <button
        :data-state="pressed ? 'on' : 'off'"
        :disabled="disabled ? true : undefined"
        @click="onClick"
        @mousedown.prevent
        :class="Themes.TOGGLE_BUTTON"
      >
        <slot></slot>
      </button>
    </TooltipTrigger>
    <TooltipContent v-if="tooltip && !disabled" :class="Themes.TOOLTIP_CONTENT">
      {{ tooltip }}
    </TooltipContent>
  </TooltipRoot>
</template>
