// playground/examples/svelte-minimal/App.svelte
<script lang="ts">
import 'prosekit/basic/style.css'

import { onMount } from 'svelte'
import { createEditor } from 'prosekit/core'
import { ProseKit } from 'prosekit/svelte/components/prosekit'
import { addBasicExtension } from 'prosekit/basic'

const extension = addBasicExtension()
const editor = createEditor({ extension })

let place: HTMLDivElement
onMount(() => editor.mount(place))
</script>

<main>
  <ProseKit {editor}>
    <div bind:this={place} class="example-editor EDITOR_BOX"></div>
  </ProseKit>
</main>

// playground/examples/vue-minimal/App.vue
<script setup lang="ts">
import 'prosekit/basic/style.css'

import { addBasicExtension } from 'prosekit/basic'
import { createEditor } from 'prosekit/core'
import { ProseKit } from 'prosekit/vue'
import { ref, watchPostEffect } from 'vue'

const extension = addBasicExtension()
const editor = createEditor({ extension })
const editorRef = ref<HTMLDivElement | null>(null)
watchPostEffect(() => editor.mount(editorRef.value))
</script>

<template>
  <ProseKit :editor="editor">
    <div ref="editorRef" class="example-editor EDITOR_BOX"></div>
  </ProseKit>
</template>
