// registry/src/preact/ui/block-handle/block-handle.tsx
import {
  BlockHandleAdd,
  BlockHandleDraggable,
  BlockHandlePopup,
  BlockHandlePositioner,
  BlockHandleRoot,
} from 'prosekit/preact/block-handle'

interface Props {
  dir?: 'ltr' | 'rtl'
}

export default function BlockHandle(props: Props) {
  return (
    <BlockHandleRoot className="contents">
      <BlockHandlePositioner
        placement={props.dir === 'rtl' ? 'right' : 'left'}
        className="CSS_BLOCK_HANDLE_POSITIONER"
      >
        <BlockHandlePopup className="CSS_BLOCK_HANDLE_POPUP">
          <BlockHandleAdd className="CSS_BLOCK_HANDLE_ADD">
            <div className="CSS_ICON_PLUS" />
          </BlockHandleAdd>
          <BlockHandleDraggable className="CSS_BLOCK_HANDLE_DRAG">
            <div className="CSS_ICON_DRAG_HANDLE" />
          </BlockHandleDraggable>
        </BlockHandlePopup>
      </BlockHandlePositioner>
    </BlockHandleRoot>
  )
}

// registry/src/svelte/ui/block-handle/block-handle.svelte
<script lang="ts">
import {
  BlockHandleAdd,
  BlockHandleDraggable,
  BlockHandlePopup,
  BlockHandlePositioner,
  BlockHandleRoot,
} from 'prosekit/svelte/block-handle'

interface Props {
  dir?: 'ltr' | 'rtl'
}

const props: Props = $props()
</script>

<BlockHandleRoot class="contents">
  <BlockHandlePositioner placement={props.dir === 'rtl' ? 'right' : 'left'} class="CSS_BLOCK_HANDLE_POSITIONER">
    <BlockHandlePopup class="CSS_BLOCK_HANDLE_POPUP">
      <BlockHandleAdd class="CSS_BLOCK_HANDLE_ADD">
        <div class="CSS_ICON_PLUS"></div>
      </BlockHandleAdd>
      <BlockHandleDraggable class="CSS_BLOCK_HANDLE_DRAG">
        <div class="CSS_ICON_DRAG_HANDLE"></div>
      </BlockHandleDraggable>
    </BlockHandlePopup>
  </BlockHandlePositioner>
</BlockHandleRoot>
