// packages/solid/src/components/popover/popover-content.gen.ts
import { 
  type PopoverContentElement,
  type PopoverContentProps as Props,
  type PopoverContentEvents as Events,
  popoverContentProps,
  popoverContentEvents,
} from '@prosekit/web/popover'
import type { Component } from 'solid-js'

import type { PropsWithElement } from '../../types.ts'
import { createComponent } from '../create-component.ts'
import type { CreateProps } from '../create-props.ts'

/**
 * Props for the {@link PopoverContent} component.
 */
export interface PopoverContentProps extends Partial<CreateProps<Props, Events>> {}

export const PopoverContent: Component<PropsWithElement<
  PopoverContentProps,
  PopoverContentElement
>> = createComponent<
  PopoverContentProps,
  PopoverContentElement
>(
  'prosekit-popover-content', 
  Object.keys(popoverContentProps),
  Object.keys(popoverContentEvents),
)

// packages/react/src/components/popover/popover-content.gen.ts
import {
  type PopoverContentElement,
  type PopoverContentProps as Props,
  type PopoverContentEvents as Events,
  popoverContentProps,
  popoverContentEvents,
} from '@prosekit/web/popover'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component.ts'
import type { CreateProps } from '../create-props.ts'

/**
 * Props for the {@link PopoverContent} component.
 */
export interface PopoverContentProps extends Partial<CreateProps<Props, Events>> {}

export const PopoverContent: ForwardRefExoticComponent<
  PopoverContentProps &
  RefAttributes<PopoverContentElement> &
  HTMLAttributes<PopoverContentElement>
> = createComponent<
  PopoverContentProps,
  PopoverContentElement
>(
  'prosekit-popover-content',
  'PopoverContent',
  Object.keys(popoverContentProps),
  Object.keys(popoverContentEvents),
)
