// website/src/shared/react/block-handle.tsx
import { Themes } from '@prosekit/themes'
import {
  BlockHandleAdd,
  BlockHandleDraggable,
  BlockHandlePopover,
} from 'prosekit/react/block-handle'

export default function BlockHandle() {
  return (
    <BlockHandlePopover className={Themes.BLOCK_HANDLE_POPOVER}>
      <BlockHandleAdd className={Themes.BLOCK_HANDLE_ADD}>
        <div className={Themes.CSS_ICON_PLUS} />
      </BlockHandleAdd>
      <BlockHandleDraggable className={Themes.BLOCK_HANDLE_DRAG}>
        <div className={Themes.CSS_ICON_DRAG_HANDLE} />
      </BlockHandleDraggable>
    </BlockHandlePopover>
  )
}

// website/src/shared/svelte/block-handle.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import {
  BlockHandleAdd,
  BlockHandleDraggable,
  BlockHandlePopover,
} from 'prosekit/svelte/block-handle'
</script>

<BlockHandlePopover class={Themes.BLOCK_HANDLE_POPOVER}>
  <BlockHandleAdd class={Themes.BLOCK_HANDLE_ADD}>
    <div class={Themes.CSS_ICON_PLUS}></div>
  </BlockHandleAdd>
  <BlockHandleDraggable class={Themes.BLOCK_HANDLE_DRAG}>
    <div class={Themes.CSS_ICON_DRAG_HANDLE}></div>
  </BlockHandleDraggable>
</BlockHandlePopover>
