// playground/examples/vue-code/Toolbar.vue
<script setup lang="ts">
import { useEditor } from 'prosekit/vue'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })
</script>

<template>
  <div class="TOOLBAR">
    <button
      :data-state="editor.marks.code.isActive() ? 'on' : 'off'"
      @click="() => editor.commands.toggleCode()"
      @mousedown.prevent
      class="TOGGLE_BUTTON"
    >
      Code
    </button>
  </div>
</template>

// playground/src/examples/svelte/code/toolbar.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/svelte'
import Button from './button.svelte'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })
</script>

<div class={Themes.TOOLBAR}>
  <Button
    pressed={$editor.marks.code.isActive()}
    onClick={() => $editor.commands.toggleCode()}
  >
    Code
  </Button>
</div>
