// registry/src/svelte/ui/code-block-view/code-block-view.svelte
<script lang="ts">
import { renderMermaidSVG, THEMES } from 'beautiful-mermaid'
import type { ProseMirrorNode } from 'prosekit/pm/model'
import type { CodeBlockAttrs } from 'prosekit/extensions/code-block'
import { hasCodeBlockPreviewHiddenDecoration, shikiBundledLanguagesInfo } from 'prosekit/extensions/code-block'
import { TextSelection } from 'prosekit/pm/state'
import type { Decoration } from 'prosekit/pm/view'
import type { SvelteNodeViewProps } from 'prosekit/svelte'
import { fromStore } from 'svelte/store'

interface Props extends SvelteNodeViewProps {}

const props: Props = $props()
const node: ProseMirrorNode = $derived(fromStore(props.node).current)
const decorations: readonly Decoration[] = $derived(fromStore(props.decorations).current)

const attrs = $derived(node.attrs as CodeBlockAttrs)
const language = $derived(attrs.language || '')
const forceShowSource = $derived(hasCodeBlockPreviewHiddenDecoration(decorations))
const showMermaidPreview = $derived(!forceShowSource && language === 'mermaid')

const mermaidPreview = $derived.by<{ svg: string | null; error: Error | null }>(() => {
  if (language !== 'mermaid') return { svg: null, error: null }
  try {
    return { svg: renderMermaidSVG(node.textContent, THEMES['tokyo-night']), error: null }
  } catch (err) {
    return { svg: null, error: err instanceof Error ? err : new Error(String(err)) }
  }
})

function setLanguage(lang: string) {
  const newAttrs: CodeBlockAttrs = { language: lang }
  props.setAttrs(newAttrs)
}

function bindContentRef(element: HTMLPreElement) {
  props.contentRef(element)
}

function focusSource(event: MouseEvent) {
  event.preventDefault()
  const pos = props.getPos()
  if (typeof pos !== 'number') return
  const { state, dispatch } = props.view
  const selection = TextSelection.near(state.doc.resolve(pos + 1), 1)
  dispatch(state.tr.setSelection(selection as never))
  props.view.focus()
}
</script>

<div
  class="CSS_LANGUAGE_WRAPPER"
  contentEditable="false"
  data-preview={showMermaidPreview ? '' : undefined}
>
  <select
    aria-label="Code block language"
    class="CSS_LANGUAGE_SELECT"
    value={language}
    onchange={(event) => setLanguage((event.target as HTMLSelectElement).value)}
  >
    <option value="">Plain Text</option>
    {#each shikiBundledLanguagesInfo as info (info.id)}
      <option value={info.id}>
        {info.name}
      </option>
    {/each}
  </select>
</div>
<pre
  use:bindContentRef
  class="CSS_CODE_BLOCK_PREVIEW_SOURCE"
  data-preview={showMermaidPreview ? '' : undefined}
  data-language={language}
></pre>
{#if showMermaidPreview}
  <div
    class="CSS_CODE_BLOCK_PREVIEW_DISPLAY"
    contentEditable="false"
    tabindex={0}
    onmousedown={focusSource}
  >
    {#if mermaidPreview.error}
      <pre>{mermaidPreview.error.message}</pre>
    {/if}
    {#if mermaidPreview.svg}
      <div>{@html mermaidPreview.svg}</div>
    {/if}
  </div>
{/if}

// registry/src/vue/ui/code-block-view/code-block-view.vue
<script setup lang="ts">
import { renderMermaidSVG, THEMES } from 'beautiful-mermaid'
import { hasCodeBlockPreviewHiddenDecoration, shikiBundledLanguagesInfo, type CodeBlockAttrs } from 'prosekit/extensions/code-block'
import { TextSelection } from 'prosekit/pm/state'
import type { VueNodeViewProps } from 'prosekit/vue'
import { computed } from 'vue'

const props = defineProps<VueNodeViewProps>()

const attrs = computed(() => props.node.value.attrs as CodeBlockAttrs)
const language = computed(() => attrs.value.language || '')
const forceShowSource = computed(() => hasCodeBlockPreviewHiddenDecoration(props.decorations.value))
const showMermaidPreview = computed(() => !forceShowSource.value && language.value === 'mermaid')

const mermaidPreview = computed<{ svg: string | null; error: Error | null }>(() => {
  if (language.value !== 'mermaid') return { svg: null, error: null }
  try {
    return { svg: renderMermaidSVG(props.node.value.textContent, THEMES['tokyo-night']), error: null }
  } catch (err) {
    return { svg: null, error: err instanceof Error ? err : new Error(String(err)) }
  }
})

function setLanguage(lang: string) {
  const newAttrs: CodeBlockAttrs = { language: lang }
  props.setAttrs(newAttrs)
}

function focusSource(event: MouseEvent) {
  event.preventDefault()
  const pos = props.getPos()
  if (typeof pos !== 'number') return
  const { state, dispatch } = props.view
  const selection = TextSelection.near(state.doc.resolve(pos + 1), 1)
  dispatch(state.tr.setSelection(selection as never))
  props.view.focus()
}
</script>

<template>
  <div v-if="!showMermaidPreview" class="CSS_LANGUAGE_WRAPPER" contentEditable="false">
    <select
      aria-label="Code block language"
      class="CSS_LANGUAGE_SELECT"
      :value="language"
      @change="(event) => setLanguage((event.target as HTMLSelectElement).value)"
    >
      <option value="">Plain Text</option>
      <option
        v-for="info in shikiBundledLanguagesInfo"
        :key="info.id"
        :value="info.id"
      >
        {{ info.name }}
      </option>
    </select>
  </div>
  <pre
    :ref="contentRef"
    class="CSS_CODE_BLOCK_PREVIEW_SOURCE"
    :data-preview="showMermaidPreview ? '' : undefined"
    :data-language="language"
  ></pre>
  <div
    v-if="showMermaidPreview"
    class="CSS_CODE_BLOCK_PREVIEW_DISPLAY"
    contentEditable="false"
    :tabindex="0"
    @mousedown="focusSource"
  >
    <pre v-if="mermaidPreview.error">{{ mermaidPreview.error.message }}</pre>
    <div v-if="mermaidPreview.svg" v-html="mermaidPreview.svg"></div>
  </div>
</template>
