// aria-ui/packages/elements/src/generated/solid/tooltip-positioner.gen.ts
import {
  registerTooltipPositionerElement,
  type TooltipPositionerElement,
  type TooltipPositionerProps as TooltipPositionerElementProps,
} from "../../tooltip/index.ts";
import { mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";

/** Props for the {@link TooltipPositioner} Solid component. */
export interface TooltipPositionerProps extends JSX.HTMLAttributes<TooltipPositionerElement> {
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: TooltipPositionerElementProps["strategy"];
  /**
   * The initial placement of the floating element
   *
   * @default "top"
   */
  placement?: TooltipPositionerElementProps["placement"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: TooltipPositionerElementProps["autoUpdate"];
  /**
   * Whether to use the browser Popover API to place the floating element on
   * top of other page content.
   *
   * @default true
   */
  hoist?: TooltipPositionerElementProps["hoist"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: TooltipPositionerElementProps["offset"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: TooltipPositionerElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: TooltipPositionerElementProps["shift"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: TooltipPositionerElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: TooltipPositionerElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: TooltipPositionerElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: TooltipPositionerElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: TooltipPositionerElementProps["inline"];
  /**
   * Whether to hide the floating element when the reference element or the
   * floating element is fully clipped.
   *
   * @default false
   */
  hide?: TooltipPositionerElementProps["hide"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: TooltipPositionerElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: TooltipPositionerElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: TooltipPositionerElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: TooltipPositionerElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: TooltipPositionerElementProps["altBoundary"];
}

export const TooltipPositioner: Component<TooltipPositionerProps> = (
  props,
): any => {
  registerTooltipPositionerElement();

  const [elementProps, restProps] = splitProps(props, [
    "strategy",
    "placement",
    "autoUpdate",
    "hoist",
    "offset",
    "flip",
    "shift",
    "overlap",
    "fitViewport",
    "sameWidth",
    "sameHeight",
    "inline",
    "hide",
    "boundary",
    "rootBoundary",
    "overflowPadding",
    "elementContext",
    "altBoundary",
  ]);

  return h(
    "aria-ui-tooltip-positioner",
    mergeProps(restProps, {
      "prop:strategy": () => elementProps.strategy,
      "prop:placement": () => elementProps.placement,
      "prop:autoUpdate": () => elementProps.autoUpdate,
      "prop:hoist": () => elementProps.hoist,
      "prop:offset": () => elementProps.offset,
      "prop:flip": () => elementProps.flip,
      "prop:shift": () => elementProps.shift,
      "prop:overlap": () => elementProps.overlap,
      "prop:fitViewport": () => elementProps.fitViewport,
      "prop:sameWidth": () => elementProps.sameWidth,
      "prop:sameHeight": () => elementProps.sameHeight,
      "prop:inline": () => elementProps.inline,
      "prop:hide": () => elementProps.hide,
      "prop:boundary": () => elementProps.boundary,
      "prop:rootBoundary": () => elementProps.rootBoundary,
      "prop:overflowPadding": () => elementProps.overflowPadding,
      "prop:elementContext": () => elementProps.elementContext,
      "prop:altBoundary": () => elementProps.altBoundary,
    }),
  );
};

// aria-ui/packages/elements/src/generated/react/tooltip-positioner.gen.ts
import { createComponent } from "@aria-ui-v2/integrations/react";
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from "react";
import {
  registerTooltipPositionerElement,
  type TooltipPositionerElement,
  type TooltipPositionerProps as TooltipPositionerElementProps,
} from "../../tooltip/index.ts";

/** Props for the {@link TooltipPositioner} React component. */
export interface TooltipPositionerProps extends HTMLAttributes<TooltipPositionerElement> {
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: TooltipPositionerElementProps["strategy"];
  /**
   * The initial placement of the floating element
   *
   * @default "top"
   */
  placement?: TooltipPositionerElementProps["placement"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: TooltipPositionerElementProps["autoUpdate"];
  /**
   * Whether to use the browser Popover API to place the floating element on
   * top of other page content.
   *
   * @default true
   */
  hoist?: TooltipPositionerElementProps["hoist"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: TooltipPositionerElementProps["offset"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: TooltipPositionerElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: TooltipPositionerElementProps["shift"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: TooltipPositionerElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: TooltipPositionerElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: TooltipPositionerElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: TooltipPositionerElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: TooltipPositionerElementProps["inline"];
  /**
   * Whether to hide the floating element when the reference element or the
   * floating element is fully clipped.
   *
   * @default false
   */
  hide?: TooltipPositionerElementProps["hide"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: TooltipPositionerElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: TooltipPositionerElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: TooltipPositionerElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: TooltipPositionerElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: TooltipPositionerElementProps["altBoundary"];
}

const propNames: string[] = [
  "strategy",
  "placement",
  "autoUpdate",
  "hoist",
  "offset",
  "flip",
  "shift",
  "overlap",
  "fitViewport",
  "sameWidth",
  "sameHeight",
  "inline",
  "hide",
  "boundary",
  "rootBoundary",
  "overflowPadding",
  "elementContext",
  "altBoundary",
];
const eventHandlersMap: Record<string, string> = {};
export const TooltipPositioner: ForwardRefExoticComponent<
  TooltipPositionerProps & RefAttributes<TooltipPositionerElement>
> = /* @__PURE__ */ createComponent(
  "aria-ui-tooltip-positioner",
  "TooltipPositioner",
  propNames,
  eventHandlersMap,
  registerTooltipPositionerElement,
);
