// website/src/examples/svelte/code/toolbar.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/svelte'
import Button from './button.svelte'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })
</script>

<div class={Themes.CSS_TOOLBAR}>
  <Button
    pressed={$editor.marks.code.isActive()}
    onClick={() => $editor.commands.toggleCode()}
  >
    Code
  </Button>
</div>

// website/src/examples/vue/bold/toolbar.vue
<script setup lang="ts">
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/vue'

import Button from './button.vue'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })
</script>

<template>
  <div class="CSS_TOOLBAR">
    <Button
      :pressed="editor.marks.bold.isActive()"
      @click="() => editor.commands.toggleBold()"
    >
      Bold
    </Button>
  </div>
</template>
