// playground/examples/solid-readonly/use-readonly.ts
import { defineReadonly } from 'prosekit/extensions/readonly'
import { useExtension } from 'prosekit/solid'
import { createEffect, createSignal } from 'solid-js'

export function useReadonly() {
  const [getReadonly, setReadonly] = createSignal(false)
  const toggleReadonly = () => setReadonly((readonly) => !readonly)

  createEffect(() => {
    const readonly = getReadonly()
    const extension = readonly ? defineReadonly() : null
    useExtension(extension)
  })

  return { getReadonly, toggleReadonly }
}

// playground/examples/react-readonly/use-readonly.ts
import { defineReadonly } from 'prosekit/extensions/readonly'
import { useExtension } from 'prosekit/react'
import { useState, useMemo } from 'react'

export function useReadonly() {
  const [readonly, setReadonly] = useState(false)
  const toggleReadonly = () => setReadonly((readonly) => !readonly)

  const extension = useMemo(() => {
    return readonly ? defineReadonly() : null
  }, [readonly])
  useExtension(extension)

  return { readonly, toggleReadonly }
}
