// packages/svelte/src/components/table-handle/table-handle-drag-indicator.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { tableHandleDragIndicatorProps, tableHandleDragIndicatorEvents } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useComponent } from '../use-component'
import { useEventHandlers } from '../use-event-handlers'

let attributes: Record<string, unknown> = {}
let eventHandlers: Record<string, (...args: any[]) => any> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useComponent(Object.keys(tableHandleDragIndicatorProps), Object.keys(tableHandleDragIndicatorEvents))

$: {
  [attributes, eventHandlers] = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-handle-drag-indicator {...attributes} use:useEventHandlers={eventHandlers} bind:this={element}>
    <slot />
  </prosekit-table-handle-drag-indicator>
</ClientUpdate>

// packages/react/src/components/table-handle/table-handle-drag-indicator.gen.ts
import {
  type TableHandleDragIndicatorElement,
  type TableHandleDragIndicatorProps as Props,
  type TableHandleDragIndicatorEvents as Events,
  tableHandleDragIndicatorProps,
  tableHandleDragIndicatorEvents,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'
import type { CreateProps } from '../create-props'

/**
 * Props for the {@link TableHandleDragIndicator} component.
 */
export interface TableHandleDragIndicatorProps extends Partial<CreateProps<Props, Events>> {}
 
export const TableHandleDragIndicator: ForwardRefExoticComponent<
  TableHandleDragIndicatorProps &
  RefAttributes<TableHandleDragIndicatorElement> &
  HTMLAttributes<TableHandleDragIndicatorElement>
> = createComponent<
  TableHandleDragIndicatorProps, 
  TableHandleDragIndicatorElement
>(
  'prosekit-table-handle-drag-indicator',
  'TableHandleDragIndicator',
  Object.keys(tableHandleDragIndicatorProps),
  Object.keys(tableHandleDragIndicatorEvents),
)
