// packages/svelte/src/components/table-handle/table-handle-dnd-indicator.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { tableHandleDndIndicatorProps, tableHandleDndIndicatorEvents } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useComponent } from '../use-component'
import { useEventHandlers } from '../use-event-handlers'

let attributes: Record<string, unknown> = {}
let eventHandlers: Record<string, (...args: any[]) => any> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useComponent(Object.keys(tableHandleDndIndicatorProps), Object.keys(tableHandleDndIndicatorEvents))

$: {
  [attributes, eventHandlers] = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-handle-dnd-indicator {...attributes} use:useEventHandlers={eventHandlers} bind:this={element}>
    <slot />
  </prosekit-table-handle-dnd-indicator>
</ClientUpdate>

// packages/react/src/components/table-handle/table-handle-dnd-indicator.gen.ts
import {
  type TableHandleDndIndicatorElement,
  type TableHandleDndIndicatorProps as Props,
  type TableHandleDndIndicatorEvents as Events,
  tableHandleDndIndicatorProps,
  tableHandleDndIndicatorEvents,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'
import type { CreateProps } from '../create-props'

/**
 * Props for the {@link TableHandleDndIndicator} component.
 */
export interface TableHandleDndIndicatorProps extends Partial<CreateProps<Props, Events>> {}
 
export const TableHandleDndIndicator: ForwardRefExoticComponent<
  TableHandleDndIndicatorProps &
  RefAttributes<TableHandleDndIndicatorElement> &
  HTMLAttributes<TableHandleDndIndicatorElement>
> = createComponent<
  TableHandleDndIndicatorProps, 
  TableHandleDndIndicatorElement
>(
  'prosekit-table-handle-dnd-indicator',
  'TableHandleDndIndicator',
  Object.keys(tableHandleDndIndicatorProps),
  Object.keys(tableHandleDndIndicatorEvents),
)
