// packages/svelte/src/components/table-handle/table-handle-drop-cursor.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { tableHandleDropCursorProps, tableHandleDropCursorEvents } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useComponent } from '../use-component'
import { useEventHandlers } from '../use-event-handlers'

let attributes: Record<string, unknown> = {}
let eventHandlers: Record<string, (...args: any[]) => any> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useComponent(Object.keys(tableHandleDropCursorProps), Object.keys(tableHandleDropCursorEvents))

$: {
  [attributes, eventHandlers] = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-handle-drop-cursor {...attributes} use:useEventHandlers={eventHandlers} bind:this={element}>
    <slot />
  </prosekit-table-handle-drop-cursor>
</ClientUpdate>

// packages/react/src/components/table-handle/table-handle-drop-cursor.gen.ts
import {
  type TableHandleDropCursorElement,
  type TableHandleDropCursorProps as Props,
  type TableHandleDropCursorEvents as Events,
  tableHandleDropCursorProps,
  tableHandleDropCursorEvents,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'
import type { CreateProps } from '../create-props'

/**
 * Props for the {@link TableHandleDropCursor} component.
 */
export interface TableHandleDropCursorProps extends Partial<CreateProps<Props, Events>> {}
 
export const TableHandleDropCursor: ForwardRefExoticComponent<
  TableHandleDropCursorProps &
  RefAttributes<TableHandleDropCursorElement> &
  HTMLAttributes<TableHandleDropCursorElement>
> = createComponent<
  TableHandleDropCursorProps, 
  TableHandleDropCursorElement
>(
  'prosekit-table-handle-drop-cursor',
  'TableHandleDropCursor',
  Object.keys(tableHandleDropCursorProps),
  Object.keys(tableHandleDropCursorEvents),
)
