// packages/svelte/src/components/table-handle/table-handle-dnd-preview.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { tableHandleDndPreviewProps, tableHandleDndPreviewEvents } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useComponent } from '../use-component'
import { useEventHandlers } from '../use-event-handlers'

let attributes: Record<string, unknown> = {}
let eventHandlers: Record<string, (...args: any[]) => any> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useComponent(Object.keys(tableHandleDndPreviewProps), Object.keys(tableHandleDndPreviewEvents))

$: {
  [attributes, eventHandlers] = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-handle-dnd-preview {...attributes} use:useEventHandlers={eventHandlers} bind:this={element}>
    <slot />
  </prosekit-table-handle-dnd-preview>
</ClientUpdate>

// packages/react/src/components/table-handle/table-handle-dnd-preview.gen.ts
import {
  type TableHandleDndPreviewElement,
  type TableHandleDndPreviewProps as Props,
  type TableHandleDndPreviewEvents as Events,
  tableHandleDndPreviewProps,
  tableHandleDndPreviewEvents,
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'
import type { CreateProps } from '../create-props'

/**
 * Props for the {@link TableHandleDndPreview} component.
 */
export interface TableHandleDndPreviewProps extends Partial<CreateProps<Props, Events>> {}
 
export const TableHandleDndPreview: ForwardRefExoticComponent<
  TableHandleDndPreviewProps &
  RefAttributes<TableHandleDndPreviewElement> &
  HTMLAttributes<TableHandleDndPreviewElement>
> = createComponent<
  TableHandleDndPreviewProps, 
  TableHandleDndPreviewElement
>(
  'prosekit-table-handle-dnd-preview',
  'TableHandleDndPreview',
  Object.keys(tableHandleDndPreviewProps),
  Object.keys(tableHandleDndPreviewEvents),
)
