// packages/svelte/src/components/table-handle/table-cell-popover-root.gen.svelte
<script lang="ts">
import '@prosekit/web/table-handle'

import { defaultTableCellPopoverRootProps } from '@prosekit/web/table-handle'
import { ClientUpdate } from '../client-update'
import { useWebComponent } from '../../utils/use-web-component'

let attributes: Record<string, unknown> = {}
let element: HTMLElement | undefined = undefined
const handleChange = useWebComponent(defaultTableCellPopoverRootProps)

$: {
  attributes = handleChange(element, $$props)
}
</script>

<ClientUpdate>
  <prosekit-table-cell-popover-root {...attributes} bind:this={element}>
    <slot />
  </prosekit-table-cell-popover-root>
</ClientUpdate>

// packages/react/src/components/table-handle/table-cell-popover-root.gen.ts
import {
  defaultTableCellPopoverRootProps,
  type TableCellPopoverRootElement,
  type TableCellPopoverRootProps
} from '@prosekit/web/table-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'

export const TableCellPopoverRoot: ForwardRefExoticComponent<
  Partial<TableCellPopoverRootProps> &
  RefAttributes<TableCellPopoverRootElement> &
  HTMLAttributes<TableCellPopoverRootElement>
> = createComponent<
  TableCellPopoverRootProps, 
  TableCellPopoverRootElement
>(
  'prosekit-table-cell-popover-root',
  'TableCellPopoverRoot',
  defaultTableCellPopoverRootProps,
)
