// playground/components/react/button.tsx
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/react/tooltip'
import type { ReactNode } from 'react'

export default function Button({
  pressed,
  disabled,
  onClick,
  tooltip,
  children,
}: {
  pressed?: boolean
  disabled?: boolean
  onClick?: VoidFunction
  tooltip?: string
  children: ReactNode
}) {
  return (
    <TooltipRoot>
      <TooltipTrigger className={Themes.TOOLTIP_TRIGGER}>
        <button
          data-state={pressed ? 'on' : 'off'}
          disabled={disabled}
          onClick={() => onClick?.()}
          onMouseDown={(event) => event.preventDefault()}
          className={Themes.TOGGLE_BUTTON}
        >
          {children}
          {tooltip ? <span className="sr-only">{tooltip}</span> : null}
        </button>
      </TooltipTrigger>
      {tooltip ? (
        <TooltipContent className={Themes.TOOLTIP_CONTENT}>
          {tooltip}
        </TooltipContent>
      ) : null}
    </TooltipRoot>
  )
}

// playground/components/svelte/button.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/svelte/tooltip'

export let pressed: boolean = false
export let disabled: boolean = false
export let tooltip: string = ''
export let onClick: VoidFunction | undefined = undefined
</script>

<TooltipRoot>
  <TooltipTrigger class={Themes.TOOLTIP_TRIGGER}>
    <button
      data-state={pressed ? 'on' : 'off'}
      {disabled}
      on:click={() => onClick?.()}
      on:mousedown={(event) => event.preventDefault()}
      class={Themes.TOGGLE_BUTTON}
    >
      <slot />
      {#if tooltip}
        <span class="sr-only">{tooltip}</span>
      {/if}
    </button>
  </TooltipTrigger>
  <TooltipContent class={Themes.TOOLTIP_CONTENT}>
    {tooltip}
  </TooltipContent>
</TooltipRoot>
