// playground/examples/react-user-menu/App.tsx
import 'prosekit/basic/style.css'
import 'prosekit/extensions/placeholder/style.css'

import { createEditor } from 'prosekit/core'
import { ProseKit } from 'prosekit/react'
import { useMemo } from 'react'

import TagMenu from './TagMenu'
import UserMenu from './UserMenu'
import { defineExtension } from './extension'

export default function App() {
  const editor = useMemo(() => {
    const extension = defineExtension()
    return createEditor({ extension })
  }, [])

  return (
    <ProseKit editor={editor}>
      <div ref={editor.mount} className="EDITOR_CONTENT"></div>
      <UserMenu />
      <TagMenu />
    </ProseKit>
  )
}

// playground/examples/svelte-slash-menu/App.svelte
<script lang="ts">
import 'prosekit/basic/style.css'
import 'prosekit/extensions/placeholder/style.css'

import { createEditor } from 'prosekit/core'
import { defineExtension } from './extension'
import { onMount } from 'svelte'
import { ProseKit } from 'prosekit/svelte'
import SlashMenu from './SlashMenu.svelte'

const editor = createEditor({ extension: defineExtension() })

let place: HTMLDivElement
onMount(() => editor.mount(place))
</script>

<ProseKit {editor}>
  <div bind:this={place} class="EDITOR_CONTENT"></div>
  <SlashMenu />
</ProseKit>
