// playground/examples/preact-readonly/toggle.tsx
import type { ComponentChild } from 'preact'

export default function Toggle({
  active,
  available,
  onChange,
  children,
}: {
  active?: boolean
  available: boolean
  onChange: () => void
  children: ComponentChild
}) {
  return (
    <button
      data-state={active ? 'on' : 'off'}
      onMouseDown={(event) => event.preventDefault()}
      onClick={() => onChange()}
      disabled={!available}
      class="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}

// playground/examples/solid-readonly/toggle.tsx
import type { ParentProps } from 'solid-js'

export default function Toggle({
  active,
  available,
  onChange,
  children,
}: ParentProps<{
  active: () => boolean
  available: () => boolean
  onChange: () => void
}>) {
  return (
    <button
      data-state={active() ? 'on' : 'off'}
      onMouseDown={(event) => event.preventDefault()}
      onClick={() => onChange()}
      disabled={!available()}
      class="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}
