// examples/vue/src/slash-menu/ToggleItalicButton.vue
<script setup lang="ts">
import { useExampleEditor } from './use-example-editor'

const editor = useExampleEditor()
const onToggleItalic = () => editor.commands.toggleItalic()
</script>

<template>
  <button @mousedown.prevent="onToggleItalic">Toggle italic</button>
</template>
./use-example-editor

// examples/react/src/slash-menu/ToggleItalicButton.tsx
import { MouseEvent } from 'react'

import { useExampleEditor } from './use-example-editor'

export default function ToggleItalicButton() {
  const editor = useExampleEditor()

  const onToggleItalic = (event: MouseEvent) => {
    event.preventDefault()
    editor.commands.toggleItalic()
  }

  return <button onMouseDown={onToggleItalic}>Toggle italic</button>
}
