// playground/examples/vue-keymap/App.vue
<script setup lang="ts">
import 'prosekit/basic/style.css'

import { createEditor } from 'prosekit/core'
import { ProseKit } from 'prosekit/vue'
import { ref, watchPostEffect } from 'vue'
import { defineBasicExtension } from 'prosekit/basic'

import KeymapConfig from './KeymapConfig.vue'

const extension = defineBasicExtension()
const editor = createEditor({ extension })
const editorRef = ref<HTMLDivElement | null>(null)
watchPostEffect(() => editor.mount(editorRef.value))
</script>

<template>
  <ProseKit :editor="editor">
    <div class="EDITOR_VIEWPORT">
      <div ref="editorRef" class="EDITOR_CONTENT"></div>
      <KeymapConfig />
    </div>
  </ProseKit>
</template>

// playground/examples/preact-keymap/App.tsx
import 'prosekit/basic/style.css'

import { useMemo } from 'preact/hooks'
import { defineBasicExtension } from 'prosekit/basic'
import { createEditor } from 'prosekit/core'
import { ProseKit } from 'prosekit/preact'

import KeymapConfig from './KeymapConfig'

export default function App() {
  const editor = useMemo(() => {
    const extension = defineBasicExtension()
    return createEditor({ extension })
  }, [])

  return (
    <ProseKit editor={editor}>
      <div className="EDITOR_VIEWPORT">
        <div className="EDITOR_CONTENT" ref={editor.mount}></div>
        <KeymapConfig />
      </div>
    </ProseKit>
  )
}
