// playground/components/react/image-view.tsx
import { Themes } from '@prosekit/themes'
import { UploadTask } from 'prosekit/extensions/file'
import type { ImageAttrs } from 'prosekit/extensions/image'
import type { ReactNodeViewProps } from 'prosekit/react'
import { ResizableHandle, ResizableRoot } from 'prosekit/react/resizable'
import { useEffect, useState, type SyntheticEvent } from 'react'

export default function ImageView(props: ReactNodeViewProps) {
  const { setAttrs, node } = props
  const attrs = node.attrs as ImageAttrs
  const url = attrs.src || ''
  const uploading = url.startsWith('blob:')

  const [aspectRatio, setAspectRatio] = useState<number | undefined>()
  const [error, setError] = useState<string | undefined>()
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (!url.startsWith('blob:')) {
      return
    }

    const uploadTask = UploadTask.get<string>(url)
    if (!uploadTask) {
      return
    }

    const abortController = new AbortController()
    void uploadTask.finished
      .then((resultUrl) => {
        if (resultUrl && typeof resultUrl === 'string') {
          if (abortController.signal.aborted) {
            return
          }
          setAttrs({ src: resultUrl })
        } else {
          if (abortController.signal.aborted) {
            return
          }
          setError('Unexpected upload result')
        }
        UploadTask.delete(uploadTask.objectURL)
      })
      .catch((error) => {
        if (abortController.signal.aborted) {
          return
        }
        setError(String(error))
        UploadTask.delete(uploadTask.objectURL)
      })
    const unsubscribe = uploadTask.subscribeProgress(({ loaded, total }) => {
      if (abortController.signal.aborted) {
        return
      }
      if (total > 0) {
        setProgress(loaded / total)
      }
    })
    return () => {
      unsubscribe()
      abortController.abort()
    }
  }, [url, setAttrs])

  const handleImageLoad = (event: SyntheticEvent) => {
    const img = event.target as HTMLImageElement
    const { naturalWidth, naturalHeight } = img
    const ratio = naturalWidth / naturalHeight
    if (ratio && Number.isFinite(ratio)) {
      setAspectRatio(ratio)
    }
    if (naturalWidth && naturalHeight && (!attrs.width || !attrs.height)) {
      setAttrs({ width: naturalWidth, height: naturalHeight })
    }
  }

  return (
    <ResizableRoot
      width={attrs.width ?? undefined}
      height={attrs.height ?? undefined}
      aspectRatio={aspectRatio}
      onResizeEnd={(event) => setAttrs(event.detail)}
      data-selected={props.selected ? '' : undefined}
      className={Themes.IMAGE_RESIZEALE}
    >
      {url && !error && (
        <img
          src={url}
          onLoad={handleImageLoad}
          className={Themes.IMAGE_RESIZEALE_IMAGE}
        />
      )}
      {uploading && !error && (
        <div className={Themes.IMAGE_UPLOAD_PROGRESS}>
          <div className={Themes.ICON_LOADER}></div>
          <div>{Math.round(progress * 100)}%</div>
        </div>
      )}
      {error && (
        <div className={Themes.IMAGE_UPLOAD_ERROR}>
          <div className={Themes.ICON_IMAGE_ERROR}></div>
          <div className={Themes.IMAGE_UPLOAD_ERROR_MESSAGE}>
            Failed to upload image
          </div>
        </div>
      )}
      <ResizableHandle
        className={Themes.IMAGE_RESIZEALE_HANDLE}
        position="bottom-right"
      >
        <div className={Themes.ICON_CORNER_HANDLE}></div>
      </ResizableHandle>
    </ResizableRoot>
  )
}

// playground/components/vue/image-view.vue
<script setup lang="ts">
import { Themes } from '@prosekit/themes'
import { UploadTask } from 'prosekit/extensions/file'
import type { ImageAttrs } from 'prosekit/extensions/image'
import type { VueNodeViewProps } from 'prosekit/vue'
import { ResizableHandle, ResizableRoot } from 'prosekit/vue/resizable'
import { computed, ref, watchEffect } from 'vue'

const props = defineProps<VueNodeViewProps>()

const { setAttrs, node } = props
const attrs = computed(() => node.value.attrs as ImageAttrs)
const url = computed(() => attrs.value.src || '')
const uploading = computed(() => url.value.startsWith('blob:'))

const aspectRatio = ref<number | undefined>()
const error = ref<string | undefined>()
const progress = ref(0)

watchEffect((onCleanup) => {
  if (!url.value.startsWith('blob:')) {
    return
  }

  const uploadTask = UploadTask.get<string>(url.value)
  if (!uploadTask) {
    return
  }

  const abortController = new AbortController()
  void uploadTask.finished
    .then((resultUrl) => {
      if (resultUrl && typeof resultUrl === 'string') {
        if (abortController.signal.aborted) {
          return
        }
        setAttrs({ src: resultUrl })
      } else {
        if (abortController.signal.aborted) {
          return
        }
        error.value = 'Unexpected upload result'
      }
      UploadTask.delete(uploadTask.objectURL)
    })
    .catch((error) => {
      if (abortController.signal.aborted) {
        return
      }
      error.value = String(error)
      UploadTask.delete(uploadTask.objectURL)
    })
  const unsubscribe = uploadTask.subscribeProgress(({ loaded, total }) => {
    if (abortController.signal.aborted) {
      return
    }
    if (total > 0) {
      progress.value = loaded / total
    }
  })
  onCleanup(() => {
    unsubscribe()
    abortController.abort()
  })
})

function handleImageLoad(event: Event) {
  const img = event.target as HTMLImageElement
  const { naturalWidth, naturalHeight } = img
  const ratio = naturalWidth / naturalHeight
  if (ratio && Number.isFinite(ratio)) {
    aspectRatio.value = ratio
  }
  if (
    naturalWidth &&
    naturalHeight &&
    (!attrs.value.width || !attrs.value.height)
  ) {
    setAttrs({ width: naturalWidth, height: naturalHeight })
  }
}
</script>

<template>
  <ResizableRoot
    :width="attrs.width ?? undefined"
    :height="attrs.height ?? undefined"
    :aspect-ratio="aspectRatio"
    :data-selected="props.selected.value ? '' : undefined"
    :class="Themes.IMAGE_RESIZEALE"
    @resize-end="(event) => setAttrs(event.detail)"
  >
    <img
      v-if="url && !error"
      :src="url"
      :class="Themes.IMAGE_RESIZEALE_IMAGE"
      @load="handleImageLoad"
    />

    <div v-if="uploading && !error" :class="Themes.IMAGE_UPLOAD_PROGRESS">
      <div :class="Themes.ICON_LOADER"></div>
      <div>{{ Math.round(progress * 100) }}%</div>
    </div>
    <div v-if="error" :class="Themes.IMAGE_UPLOAD_ERROR">
      <div :class="Themes.ICON_IMAGE_ERROR"></div>
      <div :class="Themes.IMAGE_UPLOAD_ERROR_MESSAGE">
        Failed to upload image
      </div>
    </div>

    <ResizableHandle
      :class="Themes.IMAGE_RESIZEALE_HANDLE"
      position="bottom-right"
    >
      <div :class="Themes.ICON_CORNER_HANDLE"></div>
    </ResizableHandle>
  </ResizableRoot>
</template>
