// packages/react/src/components/block-handle/block-popover.gen.ts
import {
  defaultBlockPopoverProps,
  type BlockPopoverElement,
  type BlockPopoverProps
} from '@prosekit/web/block-handle'
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from 'react'

import { createComponent } from '../create-component'

export const BlockPopover: ForwardRefExoticComponent<
  Partial<BlockPopoverProps> &
  RefAttributes<BlockPopoverElement> &
  HTMLAttributes<BlockPopoverElement>
> = createComponent<
  BlockPopoverProps, 
  BlockPopoverElement
>(
  'prosekit-block-popover',
  'BlockPopover',
  defaultBlockPopoverProps,
)

// packages/svelte/src/components/block-handle/block-popover.gen.svelte
<script lang="ts">
import '@prosekit/web/block-handle'
import { defaultBlockPopoverProps } from '@prosekit/web/block-handle'

import { useEditorContext } from '../../contexts/editor-context'

const hasEditor = Object.hasOwn(defaultBlockPopoverProps, 'editor')
const editorContext = useEditorContext()
const editor = hasEditor ? editorContext : undefined
</script>

<prosekit-block-popover editor={editor} {...$$props}>
  <slot />
</prosekit-block-popover>
