// registry/src/react/ui/button/button.tsx
import { TooltipPopup, TooltipPositioner, TooltipRoot, TooltipTrigger } from 'prosekit/react/tooltip'
import type { MouseEventHandler, ReactNode } from 'react'

export default function Button(props: {
  pressed?: boolean
  disabled?: boolean
  onClick?: MouseEventHandler<HTMLButtonElement>
  tooltip?: string
  children: ReactNode
}) {
  return (
    <TooltipRoot>
      <TooltipTrigger className="CSS_TOOLTIP_TRIGGER">
        <button
          data-state={props.pressed ? 'on' : 'off'}
          disabled={props.disabled}
          onClick={props.onClick}
          onMouseDown={(event) => {
            // Prevent the editor from being blurred when the button is clicked
            event.preventDefault()
          }}
          className="CSS_TOGGLE_BUTTON"
        >
          {props.children}
          {props.tooltip ? <span className="sr-only">{props.tooltip}</span> : null}
        </button>
      </TooltipTrigger>
      {props.tooltip
        ? (
          <TooltipPositioner className="CSS_TOOLTIP_POSITIONER">
            <TooltipPopup className="CSS_TOOLTIP_POPUP">
              {props.tooltip}
            </TooltipPopup>
          </TooltipPositioner>
        )
        : null}
    </TooltipRoot>
  )
}

// registry/src/solid/ui/button/button.tsx
import { TooltipPopup, TooltipPositioner, TooltipRoot, TooltipTrigger } from 'prosekit/solid/tooltip'
import type { JSX } from 'solid-js'

export default function Button(props: {
  pressed?: boolean
  disabled?: boolean
  onClick?: () => void
  tooltip?: string
  children: JSX.Element
}): JSX.Element {
  return (
    <TooltipRoot>
      <TooltipTrigger class="CSS_TOOLTIP_TRIGGER">
        <button
          data-state={props.pressed ? 'on' : 'off'}
          disabled={props.disabled}
          onClick={props.onClick}
          onMouseDown={(event) => {
            // Prevent the editor from being blurred when the button is clicked
            event.preventDefault()
          }}
          class="CSS_TOGGLE_BUTTON"
        >
          {props.children}
          {props.tooltip ? <span class="sr-only">{props.tooltip}</span> : null}
        </button>
      </TooltipTrigger>
      {props.tooltip
        ? (
          <TooltipPositioner class="CSS_TOOLTIP_POSITIONER">
            <TooltipPopup class="CSS_TOOLTIP_POPUP">
              {props.tooltip}
            </TooltipPopup>
          </TooltipPositioner>
        )
        : null}
    </TooltipRoot>
  )
}
