// playground/examples/vue-code-block/code-block-view.vue
<script setup lang="ts">
import type { VueNodeViewProps } from 'prosekit/vue'
import { ComboBox } from 'prosekit/vue/combo-box'
import { ComboBoxInput } from 'prosekit/vue/combo-box-input'
import { ComboBoxItem } from 'prosekit/vue/combo-box-item'
import { ComboBoxList } from 'prosekit/vue/combo-box-list'
import { defineProps, ref } from 'vue'
import { languages } from './shikiji'

const props = defineProps<VueNodeViewProps>()

const showComboBox = ref(false)
const buttonRef = ref<HTMLButtonElement>()

const closeComboBox = () => {
  showComboBox.value = false
}
const toggleComboBox = () => {
  showComboBox.value = !showComboBox.value
}

const setLanguage = (language: string) => {
  props.setAttrs({ language })
}
</script>

<template>
  <div className="LANGUAGE_WRAPPER">
    <button
      className="LANGUAGE_BUTTON"
      @click="toggleComboBox"
      ref="buttonRef"
      contentEditable="false"
    >
      {{ props.node.value.attrs.language || 'Plain Text' }}
    </button>

    <ComboBox
      className="LANGUAGE_COMBO_BOX"
      :active="showComboBox"
      :reference="buttonRef"
      @dismiss="closeComboBox"
    >
      <ComboBoxInput
        placeholder="Search for a langauge..."
        className="LANGUAGE_COMBO_BOX_INPUT"
      ></ComboBoxInput>
      <ComboBoxList className="LANGUAGE_COMBO_BOX_LIST">
        <ComboBoxItem
          v-for="language in languages"
          :key="language"
          className="LANGUAGE_COMBO_BOX_ITEM"
          @select="() => setLanguage(language)"
        >
          {{ language }}
        </ComboBoxItem>
      </ComboBoxList>
    </ComboBox>
  </div>

  <pre :ref="contentRef" :data-language="props.node.value.attrs.language"></pre>
</template>

// playground/examples/react-toolbar/code-block-view.tsx
import { type ReactNodeViewComponentProps } from 'prosekit/react'
import { ComboBox } from 'prosekit/react/combo-box'
import { ComboBoxInput } from 'prosekit/react/combo-box-input'
import { ComboBoxItem } from 'prosekit/react/combo-box-item'
import { ComboBoxList } from 'prosekit/react/combo-box-list'
import { useRef, useState } from 'react'

import { languages } from './shikiji'

export default function CodeBlockView(props: ReactNodeViewComponentProps) {
  const [showComboBox, setShowComboBox] = useState(false)

  const setLanguage = (language: string) => {
    props.setAttrs({ language })
  }

  const closeComboBox = () => {
    setShowComboBox(false)
  }
  const toggleComboBox = () => {
    setShowComboBox((value) => !value)
  }

  const buttonRef = useRef<HTMLButtonElement>(null)

  return (
    <>
      <div className="LANGUAGE_WRAPPER">
        <button
          className="LANGUAGE_BUTTON"
          onClick={toggleComboBox}
          ref={buttonRef}
          contentEditable={false}
        >
          {props.node.attrs.language || 'Plain Text'}
        </button>

        <ComboBox
          className="LANGUAGE_COMBO_BOX"
          active={showComboBox}
          reference={buttonRef.current ?? undefined}
          onDismiss={closeComboBox}
        >
          <ComboBoxInput
            placeholder="Search for a langauge..."
            className="LANGUAGE_COMBO_BOX_INPUT"
          ></ComboBoxInput>
          <ComboBoxList className="LANGUAGE_COMBO_BOX_LIST">
            {languages.map((language) => (
              <ComboBoxItem
                key={language}
                className="LANGUAGE_COMBO_BOX_ITEM"
                onSelect={() => setLanguage(language)}
              >
                {language}
              </ComboBoxItem>
            ))}
          </ComboBoxList>
        </ComboBox>
      </div>

      <pre
        ref={props.contentRef}
        data-language={props.node.attrs.language}
      ></pre>
    </>
  )
}
