// packages/solid/src/components/autocomplete-item.gen.ts
/* eslint-disable @typescript-eslint/no-namespace */

import '@prosekit/lit/components/autocomplete-item'

import type { AutocompleteItemProps as AutocompleteItemElementProps } from '@prosekit/lit/components/autocomplete-item'
import type { Component, JSXElement } from 'solid-js'
import h from 'solid-js/h'

export type AutocompleteItemProps = {
  class?: string
  children?: JSXElement
} & AutocompleteItemElementProps

export const AutocompleteItem: Component<AutocompleteItemProps> = (props) => {
  return h('prosekit-autocomplete-item', props)
}

// packages/react/src/components/autocomplete-item.gen.ts
import { createComponent } from '@lit/react'
import type { SimplifyUnion } from '@prosekit/core'
import { AutocompleteItem as AutocompleteItemElement, type AutocompleteItemProps as AutocompleteItemElementProps } from '@prosekit/lit/components/autocomplete-item'
import React, { type ComponentType } from 'react'

export type AutocompleteItemProps = SimplifyUnion<{
  className?: string,
  children?: React.ReactNode,
} & AutocompleteItemElementProps>

const AutocompleteItemInner = createComponent({
  tagName: 'prosekit-autocomplete-item',
  elementClass: AutocompleteItemElement,
  react: React,
  displayName: 'AutocompleteItemInner',
})

export const AutocompleteItem: ComponentType<AutocompleteItemProps> = (props) => {
  return React.createElement(AutocompleteItemInner, props)
}

AutocompleteItem.displayName = 'AutocompleteItem'
