// packages/solid/src/components/block-popover.gen.ts
import '@prosekit/lit/block-popover'

import type { BlockPopoverProps as BlockPopoverElementProps } from '@prosekit/lit/block-popover'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type BlockPopoverProps = PropsWithChildren<PropsWithClass<BlockPopoverElementProps>>

export const BlockPopover: Component<BlockPopoverProps> = (props) => {
  return html`<prosekit-block-popover ...${forceProps(props)} />`
}

// packages/react/src/components/block-popover.gen.ts
import { createComponent } from '@lit/react'
import { BlockPopover as BlockPopoverElement, type BlockPopoverProps as BlockPopoverElementProps } from '@prosekit/lit/block-popover'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type BlockPopoverProps = React.PropsWithChildren<PropsWithClassName<BlockPopoverElementProps>>

const BlockPopoverInner = createComponent({
  tagName: 'prosekit-block-popover',
  elementClass: BlockPopoverElement,
  react: React,
  displayName: 'BlockPopoverInner',
})

export const BlockPopover: React.ComponentType<
  BlockPopoverProps & React.RefAttributes<BlockPopoverElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(BlockPopoverInner, { ...props, ref })
})

BlockPopover.displayName = 'BlockPopover'
