// packages/solid/src/components/inline-popover.gen.ts
import '@prosekit/lit/inline-popover'

import type { InlinePopoverProps as InlinePopoverElementProps } from '@prosekit/lit/inline-popover'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type InlinePopoverProps = PropsWithChildren<PropsWithClass<InlinePopoverElementProps>>

export const InlinePopover: Component<InlinePopoverProps> = (props) => {
  return html`<prosekit-inline-popover ...${forceProps(props)} />`
}

// packages/react/src/components/inline-popover.gen.ts
import { createComponent } from '@lit/react'
import { InlinePopover as InlinePopoverElement, type InlinePopoverProps as InlinePopoverElementProps } from '@prosekit/lit/inline-popover'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type InlinePopoverProps = React.PropsWithChildren<PropsWithClassName<InlinePopoverElementProps>>

const InlinePopoverInner = createComponent({
  tagName: 'prosekit-inline-popover',
  elementClass: InlinePopoverElement,
  react: React,
  displayName: 'InlinePopoverInner',
})

export const InlinePopover: React.ComponentType<
  InlinePopoverProps & React.RefAttributes<InlinePopoverElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(InlinePopoverInner, { ...props, ref })
})

InlinePopover.displayName = 'InlinePopover'
