// packages/solid/src/components/popover-trigger.gen.ts
import '@prosekit/lit/popover-trigger'

import type { PopoverTriggerProps as PopoverTriggerElementProps } from '@prosekit/lit/popover-trigger'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type PopoverTriggerProps = PropsWithChildren<PropsWithClass<PopoverTriggerElementProps>>

export const PopoverTrigger: Component<PopoverTriggerProps> = (props) => {
  return html`<prosekit-popover-trigger ...${forceProps(props)} />`
}

// packages/react/src/components/popover-trigger.gen.ts
import { createComponent } from '@lit/react'
import { PopoverTrigger as PopoverTriggerElement, type PopoverTriggerProps as PopoverTriggerElementProps } from '@prosekit/lit/popover-trigger'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type PopoverTriggerProps = React.PropsWithChildren<PropsWithClassName<PopoverTriggerElementProps>>

const PopoverTriggerInner = createComponent({
  tagName: 'prosekit-popover-trigger',
  elementClass: PopoverTriggerElement,
  react: React,
  displayName: 'PopoverTriggerInner',
})

export const PopoverTrigger: React.ComponentType<
  PopoverTriggerProps & React.RefAttributes<PopoverTriggerElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(PopoverTriggerInner, { ...props, ref })
})

PopoverTrigger.displayName = 'PopoverTrigger'
