// packages/svelte/src/components/prosekit/prosekit.svelte
<script lang="ts">
import type { Editor } from '@prosekit/core'
import type { Snippet } from 'svelte'
import { setEditorContext } from '../../contexts/editor-context.ts'
import { ViewRenderer } from '../view-renderer/index.ts'

let props: { editor: Editor; children?: Snippet } = $props()

setEditorContext(() => props.editor)
</script>

<ViewRenderer editor={props.editor}>
  {@render props.children?.()}
</ViewRenderer>

// packages/react/src/components/prosekit.ts
import type { Editor } from '@prosekit/core'
import { createElement, type ComponentType, type ReactNode } from 'react'

import { EditorContextProvider } from '../contexts/editor-context.ts'

import { ViewRenderer } from './view-renderer.ts'

export interface ProseKitProps {
  editor: Editor
  children?: ReactNode
}

/**
 * The root component for a ProseKit editor.
 *
 * @public
 */
export const ProseKit: ComponentType<ProseKitProps> = (props) => {
  const { editor, children } = props

  return createElement(
    EditorContextProvider,
    { value: editor },
    createElement(
      ViewRenderer,
      { editor, children },
    ),
  )
}
