// packages/solid/src/components/view-renderer.ts
import { union, type Editor } from '@prosekit/core'
import { useSolidRenderer } from '@prosemirror-adapter/solid'
import type { Component, JSX, ParentProps } from 'solid-js'

import { defineSolidMarkViewFactory } from '../extensions/solid-mark-view.ts'
import { defineSolidNodeViewFactory } from '../extensions/solid-node-view.ts'
import { useEditorExtension } from '../hooks/use-editor-extension.ts'

type ViewRendererProps = ParentProps<{
  editor: Editor
}>

export const ViewRenderer: Component<ViewRendererProps> = (props): JSX.Element => {
  const { renderSolidRenderer, removeSolidRenderer, render } = useSolidRenderer()

  const extension = union([
    defineSolidMarkViewFactory(renderSolidRenderer, removeSolidRenderer),
    defineSolidNodeViewFactory(renderSolidRenderer, removeSolidRenderer),
  ])

  useEditorExtension(() => props.editor, () => extension)

  return [props.children, render] as unknown as JSX.Element
}

// packages/react/src/components/view-renderer.ts
import { union, type Editor } from '@prosekit/core'
import { useReactRenderer } from '@prosemirror-adapter/react'
import { createElement, Fragment, useMemo, type ComponentType, type ReactNode } from 'react'

import { defineReactMarkViewFactory } from '../extensions/react-mark-view.ts'
import { defineReactNodeViewFactory } from '../extensions/react-node-view.ts'
import { useEditorExtension } from '../hooks/use-editor-extension.ts'

interface ViewRendererProps {
  editor: Editor
  children: ReactNode
}

export const ViewRenderer: ComponentType<ViewRendererProps> = ({ editor, children }): ReactNode => {
  const { renderReactRenderer, removeReactRenderer, render } = useReactRenderer()

  const extension = useMemo(() => {
    return union([
      defineReactMarkViewFactory(renderReactRenderer, removeReactRenderer),
      defineReactNodeViewFactory(renderReactRenderer, removeReactRenderer),
    ])
  }, [renderReactRenderer, removeReactRenderer])

  useEditorExtension(editor, extension)

  return createElement(Fragment, null, createElement(Fragment, null, children), createElement(Fragment, null, render()))
}
