// playground/examples/svelte-full/code-block-view.svelte
<script lang="ts">
	import type { CodeBlockAttrs } from 'prosekit/extensions/code-block';
	import type { SvelteNodeViewProps } from 'prosekit/svelte';
	import LanguageSelector from './language-selector.svelte';

	export let node: SvelteNodeViewProps['node'];
	export let setAttrs: SvelteNodeViewProps['setAttrs'];
	export let contentRef: SvelteNodeViewProps['contentRef'];

	$: language = $node.attrs.language;

	const setLanguage = (language: string) => {
		const attrs: CodeBlockAttrs = { language };
		setAttrs(attrs);
	};
</script>

<LanguageSelector {language} {setLanguage} />
<pre use:contentRef data-language={language}></pre>

// playground/examples/react-code-block-themes/code-block-view.tsx
import type { CodeBlockAttrs } from 'prosekit/extensions/code-block'
import { type ReactNodeViewProps } from 'prosekit/react'

import LanguageSelector from './language-selector'

export default function CodeBlockView(props: ReactNodeViewProps) {
  const attrs = props.node.attrs as CodeBlockAttrs
  const language = attrs.language

  const setLanguage = (language: string) => {
    props.setAttrs({ language })
  }

  return (
    <>
      <LanguageSelector language={language} setLanguage={setLanguage} />
      <pre ref={props.contentRef} data-language={language}></pre>
    </>
  )
}
