// registry/src/react/ui/tag-menu/tag-menu.tsx
import type { BasicExtension } from 'prosekit/basic'
import type { Union } from 'prosekit/core'
import type { MentionExtension } from 'prosekit/extensions/mention'
import { useEditor } from 'prosekit/react'
import {
  AutocompleteEmpty,
  AutocompleteItem,
  AutocompletePopup,
  AutocompletePositioner,
  AutocompleteRoot,
} from 'prosekit/react/autocomplete'

const regex = /#[\da-z]*$/i

export default function TagMenu(props: { tags: { id: number; label: string }[] }) {
  const editor = useEditor<Union<[MentionExtension, BasicExtension]>>()

  const handleTagInsert = (id: number, label: string) => {
    editor.commands.insertMention({
      id: id.toString(),
      value: '#' + label,
      kind: 'tag',
    })
    editor.commands.insertText({ text: ' ' })
  }

  return (
    <AutocompleteRoot regex={regex}>
      <AutocompletePositioner>
        <AutocompletePopup className="CSS_AUTOCOMPLETE_MENU">
          <AutocompleteEmpty className="CSS_AUTOCOMPLETE_MENU_ITEM">
            No results
          </AutocompleteEmpty>

          {props.tags.map((tag) => (
            <AutocompleteItem
              key={tag.id}
              className="CSS_AUTOCOMPLETE_MENU_ITEM"
              onSelect={() => handleTagInsert(tag.id, tag.label)}
            >
              #{tag.label}
            </AutocompleteItem>
          ))}
        </AutocompletePopup>
      </AutocompletePositioner>
    </AutocompleteRoot>
  )
}

// registry/src/svelte/ui/tag-menu/tag-menu.svelte
<script lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import type { Union } from 'prosekit/core'
import type { MentionExtension } from 'prosekit/extensions/mention'
import { useEditor } from 'prosekit/svelte'
import {
  AutocompleteEmpty,
  AutocompleteItem,
  AutocompletePopup,
  AutocompletePositioner,
  AutocompleteRoot,
} from 'prosekit/svelte/autocomplete'

interface Props {
  tags: { id: number; label: string }[]
}

const props: Props = $props()

const editor = useEditor<Union<[MentionExtension, BasicExtension]>>()

function handleTagInsert(id: number, label: string) {
  $editor.commands.insertMention({
    id: id.toString(),
    value: '#' + label,
    kind: 'tag',
  })
  $editor.commands.insertText({ text: ' ' })
}

const regex = /#[\da-z]*$/i
</script>

<AutocompleteRoot {regex} >
  <AutocompletePositioner>
    <AutocompletePopup class="CSS_AUTOCOMPLETE_MENU">
      <AutocompleteEmpty class="CSS_AUTOCOMPLETE_MENU_ITEM">
        No results
      </AutocompleteEmpty>

      {#each props.tags as tag (tag.id)}
        <AutocompleteItem
          class="CSS_AUTOCOMPLETE_MENU_ITEM"
          onSelect={() => handleTagInsert(tag.id, tag.label)}
        >
          #{tag.label}
        </AutocompleteItem>
      {/each}
    </AutocompletePopup>
  </AutocompletePositioner>
</AutocompleteRoot>
