// playground/examples/react-toolbar/ToggleButton.tsx
import React from 'react'

export function ToggleButton({
  active,
  available,
  onChange,
  children,
}: {
  active?: boolean
  available: boolean
  onChange: () => void
  children: React.ReactNode
}) {
  return (
    <button
      data-state={active ? 'on' : 'off'}
      onMouseDown={(event) => event.preventDefault()}
      onClick={() => onChange()}
      disabled={!available}
      className="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}

// playground/examples/solid-heading/ToggleButton.tsx
import type { ParentProps } from 'solid-js'

export default function ToggleButton({
  active,
  available,
  onChange,
  children,
}: ParentProps<{
  active?: boolean
  available: boolean
  onChange: () => void
}>) {
  return (
    <button
      data-state={active ? 'on' : 'off'}
      onMouseDown={(event) => event.preventDefault()}
      onClick={() => onChange()}
      disabled={!available}
      class="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}
