// playground/examples/svelte-word-count/word-counter.svelte
<script lang="ts">
import { useEditor } from 'prosekit/svelte'
import type { EditorExtension } from './extension'
import { derived } from 'svelte/store'

const editor = useEditor<EditorExtension>({ update: true })

const wordCount = derived(editor, ($editor) => {
  if (!$editor.mounted) {
    return 0
  }
  const text = $editor.view.state.doc.textContent
  return text.split(/\s+/).length
})
</script>

<div class="p-4 text-center italic tabular-nums">
  Word Count: {$wordCount}
</div>

// playground/examples/vue-word-counter/word-counter.vue
<script setup lang="ts">
import { useEditor } from 'prosekit/vue'
import type { EditorExtension } from './extension'
import { computed } from 'vue'

const editor = useEditor<EditorExtension>({ update: true })

const wordCount = computed(() => {
  if (!editor.value.mounted) {
    return 0
  }
  const text = editor.value.view.state.doc.textContent
  return text.split(/\s+/).length
})
</script>

<template>
  <div class="p-4 text-center italic tabular-nums">
    Word Count: {{ wordCount }}
  </div>
</template>
