// registry/src/svelte/ui/slash-menu/slash-menu.svelte
<script lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import { useEditor } from 'prosekit/svelte'
import { AutocompletePopup, AutocompletePositioner, AutocompleteRoot } from 'prosekit/svelte/autocomplete'

import SlashMenuEmpty from './slash-menu-empty.svelte'
import SlashMenuItem from './slash-menu-item.svelte'

const editor = useEditor<BasicExtension>()

// Match inputs like "/", "/table", "/heading 1" etc. Do not match "/ heading".
const regex = /(?<!\S)\/(\S.*)?$/u
</script>

<AutocompleteRoot {regex}>
  <AutocompletePositioner class="CSS_AUTOCOMPLETE_POSITIONER">
    <AutocompletePopup class="CSS_AUTOCOMPLETE_POPUP">
      <SlashMenuItem
        label="Text"
        onSelect={() => $editor.commands.setParagraph()}
      />

      <SlashMenuItem
        label="Heading 1"
        kbd="#"
        onSelect={() => $editor.commands.setHeading({ level: 1 })}
      />

      <SlashMenuItem
        label="Heading 2"
        kbd="##"
        onSelect={() => $editor.commands.setHeading({ level: 2 })}
      />

      <SlashMenuItem
        label="Heading 3"
        kbd="###"
        onSelect={() => $editor.commands.setHeading({ level: 3 })}
      />

      <SlashMenuItem
        label="Bullet list"
        kbd="-"
        onSelect={() => $editor.commands.wrapInList({ kind: 'bullet' })}
      />

      <SlashMenuItem
        label="Ordered list"
        kbd="1."
        onSelect={() => $editor.commands.wrapInList({ kind: 'ordered' })}
      />

      <SlashMenuItem
        label="Task list"
        kbd="[]"
        onSelect={() => $editor.commands.wrapInList({ kind: 'task' })}
      />

      <SlashMenuItem
        label="Toggle list"
        kbd=">>"
        onSelect={() => $editor.commands.wrapInList({ kind: 'toggle' })}
      />

      <SlashMenuItem
        label="Quote"
        kbd=">"
        onSelect={() => $editor.commands.setBlockquote()}
      />

      <SlashMenuItem
        label="Table"
        onSelect={() => $editor.commands.insertTable({ row: 3, col: 3 })}
      />

      <SlashMenuItem
        label="Divider"
        kbd="---"
        onSelect={() => $editor.commands.insertHorizontalRule()}
      />

      <SlashMenuItem
        label="Code"
        kbd="```"
        onSelect={() => $editor.commands.setCodeBlock()}
      />

      <SlashMenuEmpty />
    </AutocompletePopup>
  </AutocompletePositioner>
</AutocompleteRoot>

// registry/src/vue/ui/slash-menu/slash-menu.vue
<script setup lang="ts">
import type { BasicExtension } from 'prosekit/basic'
import { useEditor } from 'prosekit/vue'
import { AutocompletePopup, AutocompletePositioner, AutocompleteRoot } from 'prosekit/vue/autocomplete'

import SlashMenuEmpty from './slash-menu-empty.vue'
import SlashMenuItem from './slash-menu-item.vue'

const editor = useEditor<BasicExtension>()

// Match inputs like "/", "/table", "/heading 1" etc. Do not match "/ heading".
const regex = /(?<!\S)\/(\S.*)?$/u
</script>

<template>
  <AutocompleteRoot :regex="regex">
    <AutocompletePositioner class="CSS_AUTOCOMPLETE_POSITIONER">
      <AutocompletePopup class="CSS_AUTOCOMPLETE_POPUP">
        <SlashMenuItem
          label="Text"
          @select="() => editor.commands.setParagraph()"
        />

        <SlashMenuItem
          label="Heading 1"
          kbd="#"
          @select="() => editor.commands.setHeading({ level: 1 })"
        />

        <SlashMenuItem
          label="Heading 2"
          kbd="##"
          @select="() => editor.commands.setHeading({ level: 2 })"
        />

        <SlashMenuItem
          label="Heading 3"
          kbd="###"
          @select="() => editor.commands.setHeading({ level: 3 })"
        />

        <SlashMenuItem
          label="Bullet list"
          kbd="-"
          @select="() => editor.commands.wrapInList({ kind: 'bullet' })"
        />

        <SlashMenuItem
          label="Ordered list"
          kbd="1."
          @select="() => editor.commands.wrapInList({ kind: 'ordered' })"
        />

        <SlashMenuItem
          label="Task list"
          kbd="[]"
          @select="() => editor.commands.wrapInList({ kind: 'task' })"
        />

        <SlashMenuItem
          label="Toggle list"
          kbd=">>"
          @select="() => editor.commands.wrapInList({ kind: 'toggle' })"
        />

        <SlashMenuItem
          label="Quote"
          kbd=">"
          @select="() => editor.commands.setBlockquote()"
        />

        <SlashMenuItem
          label="Table"
          @select="() => editor.commands.insertTable({ row: 3, col: 3 })"
        />

        <SlashMenuItem
          label="Divider"
          kbd="---"
          @select="() => editor.commands.insertHorizontalRule()"
        />

        <SlashMenuItem
          label="Code"
          kbd="```"
          @select="() => editor.commands.setCodeBlock()"
        />

        <SlashMenuEmpty />
      </AutocompletePopup>
    </AutocompletePositioner>
  </AutocompleteRoot>
</template>
