// website/src/examples/react/text-align/toolbar.tsx
import type {
  Editor,
  NodeAction,
} from 'prosekit/core'
import { useEditorDerivedValue } from 'prosekit/react'

import Button from './button'
import type { EditorExtension } from './extension'

function isTextAlignActive(editor: Editor<EditorExtension>, value: string) {
  return Object.values(editor.nodes).some((node: NodeAction<any>) => {
    return node.isActive({ textAlign: value })
  })
}

function getToolbarItems(editor: Editor<EditorExtension>) {
  return {
    left: {
      isActive: isTextAlignActive(editor, 'left'),
      canExec: editor.commands.setTextAlign.canExec('left'),
      command: () => editor.commands.setTextAlign('left'),
    },
    center: {
      isActive: isTextAlignActive(editor, 'center'),
      canExec: editor.commands.setTextAlign.canExec('center'),
      command: () => editor.commands.setTextAlign('center'),
    },
    right: {
      isActive: isTextAlignActive(editor, 'right'),
      canExec: editor.commands.setTextAlign.canExec('right'),
      command: () => editor.commands.setTextAlign('right'),
    },
    justify: {
      isActive: isTextAlignActive(editor, 'justify'),
      canExec: editor.commands.setTextAlign.canExec('justify'),
      command: () => editor.commands.setTextAlign('justify'),
    },
  }
}

export default function Toolbar() {
  const items = useEditorDerivedValue(getToolbarItems)

  return (
    <div className="CSS_TOOLBAR">
      <Button
        pressed={items.left.isActive}
        disabled={!items.left.canExec}
        onClick={items.left.command}
        tooltip="Left"
      >
        Left
      </Button>

      <Button
        pressed={items.center.isActive}
        disabled={!items.center.canExec}
        onClick={items.center.command}
        tooltip="Center"
      >
        Center
      </Button>

      <Button
        pressed={items.right.isActive}
        disabled={!items.right.canExec}
        onClick={items.right.command}
        tooltip="Right"
      >
        Right
      </Button>

      <Button
        pressed={items.justify.isActive}
        disabled={!items.justify.canExec}
        onClick={items.justify.command}
        tooltip="Justify"
      >
        Justify
      </Button>
    </div>
  )
}

// playground/examples/svelte-text-align/toolbar.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import Button from './button.svelte'
import type { EditorExtension } from './extension'
import { useEditor } from 'prosekit/svelte'
import type { Editor } from 'prosekit/core'

const editor = useEditor<EditorExtension>({ update: true })

const isTextAlignActive = (editor: Editor<EditorExtension>, value: string) => {
  return Object.values(editor.nodes).some((node) => {
    return node.isActive({ textAlign: value })
  })
}
</script>

<div class={Themes.TOOLBAR}>
  <Button
    pressed={isTextAlignActive($editor, 'left')}
    disabled={!$editor.commands.setTextAlign.canApply('left')}
    onClick={() => $editor.commands.setTextAlign('left')}
  >
    Left
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'center')}
    disabled={!$editor.commands.setTextAlign.canApply('center')}
    onClick={() => $editor.commands.setTextAlign('center')}
  >
    Center
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'right')}
    disabled={!$editor.commands.setTextAlign.canApply('right')}
    onClick={() => $editor.commands.setTextAlign('right')}
  >
    Right
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'justify')}
    disabled={!$editor.commands.setTextAlign.canApply('justify')}
    onClick={() => $editor.commands.setTextAlign('justify')}
  >
    Justify
  </Button>
</div>
