// registry/src/solid/renderer.ts
import type { JSX } from 'solid-js'
import h from 'solid-js/h'

import { loaders } from './loaders.gen'

export function SolidRenderer({ story }: { story: string }): JSX.Element | JSX.FunctionElement {
  const Example = loaders[story as keyof typeof loaders]
  if (!Example) {
    console.warn(`[SolidRenderer] No example found for story ${story}`)
  }
  return Example ? h(Example, null) : null
}

// registry/src/svelte/renderer.svelte
<script lang="ts">
import { onMount } from 'svelte'

import { loaders } from './loaders.gen'

export let story: string = ''

let loader: (typeof loaders)[keyof typeof loaders] | undefined

onMount(() => {
  loader = loaders[story as keyof typeof loaders]
  if (!loader) {
    console.warn(`[SvelteRenderer] No example found for story ${story}`)
  }
})
</script>

{#if loader}
  {#await loader() then { default: LazyComponent }}
    <LazyComponent />
  {/await}
{:else}
  <div></div>
{/if}
