// packages/react/src/components/autocomplete-empty.gen.ts
import { createComponent } from '@lit/react'
import type { SimplifyUnion } from '@prosekit/core'
import { AutocompleteEmpty as AutocompleteEmptyElement, type AutocompleteEmptyProps as AutocompleteEmptyElementProps } from '@prosekit/lit/components/autocomplete-empty'
import React, { type ComponentType } from 'react'

export type AutocompleteEmptyProps = SimplifyUnion<{
  className?: string,
  children?: React.ReactNode,
} & AutocompleteEmptyElementProps>

const AutocompleteEmptyInner = createComponent({
  tagName: 'prosekit-autocomplete-empty',
  elementClass: AutocompleteEmptyElement,
  react: React,
  displayName: 'AutocompleteEmptyInner',
})

export const AutocompleteEmpty: ComponentType<AutocompleteEmptyProps> = (props) => {
  return React.createElement(AutocompleteEmptyInner, props)
}

AutocompleteEmpty.displayName = 'AutocompleteEmpty'

// packages/solid/src/components/autocomplete-empty.gen.ts
/* eslint-disable @typescript-eslint/no-namespace */

import '@prosekit/lit/components/autocomplete-empty'

import type { AutocompleteEmptyProps as AutocompleteEmptyElementProps } from '@prosekit/lit/components/autocomplete-empty'
import type { Component, JSXElement } from 'solid-js'
import h from 'solid-js/h'

export type AutocompleteEmptyProps = {
  class?: string
  children?: JSXElement
} & AutocompleteEmptyElementProps

export const AutocompleteEmpty: Component<AutocompleteEmptyProps> = (props) => {
  return h('prosekit-autocomplete-empty', props)
}
