// packages/react/src/components/block-drag-handle.gen.ts
import { createComponent } from '@lit/react'
import { BlockDragHandle as BlockDragHandleElement, type BlockDragHandleProps as BlockDragHandleElementProps } from '@prosekit/lit/block-drag-handle'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type BlockDragHandleProps = React.PropsWithChildren<PropsWithClassName<BlockDragHandleElementProps>>

const BlockDragHandleInner = createComponent({
  tagName: 'prosekit-block-drag-handle',
  elementClass: BlockDragHandleElement,
  react: React,
  displayName: 'BlockDragHandleInner',
})

export const BlockDragHandle: React.ComponentType<
  BlockDragHandleProps & React.RefAttributes<BlockDragHandleElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(BlockDragHandleInner, { ...props, ref })
})

BlockDragHandle.displayName = 'BlockDragHandle'

// packages/solid/src/components/block-drag-handle.gen.ts
import '@prosekit/lit/block-drag-handle'

import type { BlockDragHandleProps as BlockDragHandleElementProps } from '@prosekit/lit/block-drag-handle'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type BlockDragHandleProps = PropsWithChildren<PropsWithClass<BlockDragHandleElementProps>>

export const BlockDragHandle: Component<BlockDragHandleProps> = (props) => {
  return html`<prosekit-block-drag-handle ...${forceProps(props)} />`
}
