// packages/react/src/components/code-block-menu-popover.gen.ts
import { createComponent } from '@lit-labs/react'
import type { SimplifyUnion } from '@prosekit/core'
import { CodeBlockMenuPopover as CodeBlockMenuPopoverElement, type CodeBlockMenuPopoverProps as CodeBlockMenuPopoverElementProps } from '@prosekit/lit/components/code-block-menu-popover'
import React, { type ComponentType } from 'react'

export type CodeBlockMenuPopoverProps = SimplifyUnion<{
  className?: string,
  children?: React.ReactNode,
} & CodeBlockMenuPopoverElementProps>

const CodeBlockMenuPopoverComponent = createComponent({
  tagName: 'prosekit-code-block-menu-popover',
  elementClass: CodeBlockMenuPopoverElement,
  react: React,
  displayName: 'CodeBlockMenuPopoverComponent',
})

export const CodeBlockMenuPopover: ComponentType<CodeBlockMenuPopoverProps> = (props) => {
  return React.createElement(CodeBlockMenuPopoverComponent, props)
}

// packages/solid/src/components/code-block-menu-popover.gen.ts
/* eslint-disable @typescript-eslint/no-namespace */

import '@prosekit/lit/components/code-block-menu-popover'

import type { CodeBlockMenuPopoverProps as CodeBlockMenuPopoverElementProps } from '@prosekit/lit/components/code-block-menu-popover'
import type { Component, JSXElement } from 'solid-js'
import html from 'solid-js/html'

export type CodeBlockMenuPopoverProps = {
  class?: string
  children?: JSXElement
} & CodeBlockMenuPopoverElementProps

export const CodeBlockMenuPopover: Component<CodeBlockMenuPopoverProps> = (props) => {
  return html`<prosekit-code-block-menu-popover ...${props} />`
}
