// packages/react/src/components/combo-box-input.gen.ts
import { createComponent } from '@lit/react'
import type { SimplifyUnion } from '@prosekit/core'
import { ComboBoxInput as ComboBoxInputElement, type ComboBoxInputProps as ComboBoxInputElementProps } from '@prosekit/lit/components/combo-box-input'
import React, { type ComponentType } from 'react'

export type ComboBoxInputProps = SimplifyUnion<{
  className?: string,
  children?: React.ReactNode,
} & ComboBoxInputElementProps>

const ComboBoxInputInner = createComponent({
  tagName: 'prosekit-combo-box-input',
  elementClass: ComboBoxInputElement,
  react: React,
  displayName: 'ComboBoxInputInner',
})

export const ComboBoxInput: ComponentType<ComboBoxInputProps> = (props) => {
  return React.createElement(ComboBoxInputInner, props)
}

ComboBoxInput.displayName = 'ComboBoxInput'

// packages/solid/src/components/combo-box-input.gen.ts
/* eslint-disable @typescript-eslint/no-namespace */

import '@prosekit/lit/components/combo-box-input'

import type { ComboBoxInputProps as ComboBoxInputElementProps } from '@prosekit/lit/components/combo-box-input'
import type { Component, JSXElement } from 'solid-js'
import html from 'solid-js/html'

export type ComboBoxInputProps = {
  class?: string
  children?: JSXElement
} & ComboBoxInputElementProps

export const ComboBoxInput: Component<ComboBoxInputProps> = (props) => {
  return html`<prosekit-combo-box-input ...${props} />`
}
