// packages/react/src/components/combo-box-list.gen.ts
import { createComponent } from '@lit/react'
import type { SimplifyUnion } from '@prosekit/core'
import { ComboBoxList as ComboBoxListElement, type ComboBoxListProps as ComboBoxListElementProps } from '@prosekit/lit/components/combo-box-list'
import React, { type ComponentType } from 'react'

export type ComboBoxListProps = SimplifyUnion<{
  className?: string,
  children?: React.ReactNode,
} & ComboBoxListElementProps>

const ComboBoxListInner = createComponent({
  tagName: 'prosekit-combo-box-list',
  elementClass: ComboBoxListElement,
  react: React,
  displayName: 'ComboBoxListInner',
})

export const ComboBoxList: ComponentType<ComboBoxListProps> = (props) => {
  return React.createElement(ComboBoxListInner, props)
}

ComboBoxList.displayName = 'ComboBoxList'

// packages/solid/src/components/combo-box-list.gen.ts
/* eslint-disable @typescript-eslint/no-namespace */

import '@prosekit/lit/components/combo-box-list'

import type { ComboBoxListProps as ComboBoxListElementProps } from '@prosekit/lit/components/combo-box-list'
import type { Component, JSXElement } from 'solid-js'
import html from 'solid-js/html'

export type ComboBoxListProps = {
  class?: string
  children?: JSXElement
} & ComboBoxListElementProps

export const ComboBoxList: Component<ComboBoxListProps> = (props) => {
  return html`<prosekit-combo-box-list ...${props} />`
}
