// packages/react/src/components/drag-handle.gen.ts
import { createComponent } from '@lit/react'
import { DragHandle as DragHandleElement, type DragHandleProps as DragHandleElementProps } from '@prosekit/lit/drag-handle'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type DragHandleProps = React.PropsWithChildren<PropsWithClassName<DragHandleElementProps>>

const DragHandleInner = createComponent({
  tagName: 'prosekit-drag-handle',
  elementClass: DragHandleElement,
  react: React,
  displayName: 'DragHandleInner',
})

export const DragHandle: React.ComponentType<
  DragHandleProps & React.RefAttributes<DragHandleElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(DragHandleInner, { ...props, ref })
})

DragHandle.displayName = 'DragHandle'

// packages/solid/src/components/drag-handle.gen.ts
import '@prosekit/lit/drag-handle'

import type { DragHandleProps as DragHandleElementProps } from '@prosekit/lit/drag-handle'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type DragHandleProps = PropsWithChildren<PropsWithClass<DragHandleElementProps>>

export const DragHandle: Component<DragHandleProps> = (props) => {
  return html`<prosekit-drag-handle ...${forceProps(props)} />`
}
