// packages/react/src/components/popover-root.gen.ts
import { createComponent } from '@lit/react'
import { PopoverRoot as PopoverRootElement, type PopoverRootProps as PopoverRootElementProps } from '@prosekit/lit/popover-root'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type PopoverRootProps = React.PropsWithChildren<PropsWithClassName<PopoverRootElementProps>>

const PopoverRootInner = createComponent({
  tagName: 'prosekit-popover-root',
  elementClass: PopoverRootElement,
  react: React,
  displayName: 'PopoverRootInner',
})

export const PopoverRoot: React.ComponentType<
  PopoverRootProps & React.RefAttributes<PopoverRootElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(PopoverRootInner, { ...props, ref })
})

PopoverRoot.displayName = 'PopoverRoot'

// packages/solid/src/components/popover-root.gen.ts
import '@prosekit/lit/popover-root'

import type { PopoverRootProps as PopoverRootElementProps } from '@prosekit/lit/popover-root'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type PopoverRootProps = PropsWithChildren<PropsWithClass<PopoverRootElementProps>>

export const PopoverRoot: Component<PopoverRootProps> = (props) => {
  return html`<prosekit-popover-root ...${forceProps(props)} />`
}
