// packages/react/src/components/popover.gen.ts
import { createComponent } from '@lit/react'
import { Popover as PopoverElement, type PopoverProps as PopoverElementProps } from '@prosekit/lit/popover'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type PopoverProps = React.PropsWithChildren<PropsWithClassName<PopoverElementProps>>

const PopoverInner = createComponent({
  tagName: 'prosekit-popover',
  elementClass: PopoverElement,
  react: React,
  displayName: 'PopoverInner',
})

export const Popover: React.ComponentType<
  PopoverProps & React.RefAttributes<PopoverElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(PopoverInner, { ...props, ref })
})

Popover.displayName = 'Popover'

// packages/solid/src/components/popover.gen.ts
import '@prosekit/lit/popover'

import type { PopoverProps as PopoverElementProps } from '@prosekit/lit/popover'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type PopoverProps = PropsWithChildren<PropsWithClass<PopoverElementProps>>

export const Popover: Component<PopoverProps> = (props) => {
  return html`<prosekit-popover ...${forceProps(props)} />`
}
