// packages/react/src/components/prosekit.tsx
import { Editor } from '@prosekit/core'
import React, { ComponentType } from 'react'

import { editorContext } from '../contexts/editor-context'

export interface ProseKitProps {
  editor: Editor
  children?: React.ReactNode
}

export const ProseKit: ComponentType<ProseKitProps> = (props) => {
  const editor = props.editor

  return (
    <EditorContextProvider value={{ editor }}>
      {props.children}
    </EditorContextProvider>
  )
}

const EditorContextProvider = editorContext.Provider

// packages/solid/src/components/prosekit.ts
import type { Editor } from '@prosekit/core'
import { ProsemirrorAdapterProvider } from '@prosemirror-adapter/solid'
import { createComponent, type Component, type ParentProps } from 'solid-js'

import { EditorContextProvider } from '../contexts/editor-context'
import { consumeSolidViews } from '../extensions/solid-node-view'

export type ProseKitProps = ParentProps<{
  editor: Editor
}>

/**
 * The root component for a ProseKit editor.
 *
 * @public
 */
export const ProseKit: Component<ProseKitProps> = (props) => {
  return createComponent(ProsemirrorAdapterProvider, {
    get children() {
      return createComponent(EditorContextProvider, {
        get value() {
          return props.editor
        },
        get children() {
          consumeSolidViews()
          return props.children
        },
      })
    },
  })
}
