// packages/react/src/components/resizable-handle.gen.ts
import { createComponent } from '@lit/react'
import { ResizableHandle as ResizableHandleElement, type ResizableHandleProps as ResizableHandleElementProps } from '@prosekit/lit/resizable-handle'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type ResizableHandleProps = React.PropsWithChildren<PropsWithClassName<ResizableHandleElementProps>>

const ResizableHandleInner = createComponent({
  tagName: 'prosekit-resizable-handle',
  elementClass: ResizableHandleElement,
  react: React,
  displayName: 'ResizableHandleInner',
})

export const ResizableHandle: React.ComponentType<
  ResizableHandleProps & React.RefAttributes<ResizableHandleElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(ResizableHandleInner, { ...props, ref })
})

ResizableHandle.displayName = 'ResizableHandle'

// packages/solid/src/components/resizable-handle.gen.ts
import '@prosekit/lit/resizable-handle'

import type { ResizableHandleProps as ResizableHandleElementProps } from '@prosekit/lit/resizable-handle'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type ResizableHandleProps = PropsWithChildren<PropsWithClass<ResizableHandleElementProps>>

export const ResizableHandle: Component<ResizableHandleProps> = (props) => {
  return html`<prosekit-resizable-handle ...${forceProps(props)} />`
}
