// packages/react/src/components/tooltip-content.gen.ts
import { createComponent } from '@lit/react'
import { TooltipContent as TooltipContentElement, type TooltipContentProps as TooltipContentElementProps } from '@prosekit/lit/tooltip-content'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type TooltipContentProps = React.PropsWithChildren<PropsWithClassName<TooltipContentElementProps>>

const TooltipContentInner = createComponent({
  tagName: 'prosekit-tooltip-content',
  elementClass: TooltipContentElement,
  react: React,
  displayName: 'TooltipContentInner',
})

export const TooltipContent: React.ComponentType<
  TooltipContentProps & React.RefAttributes<TooltipContentElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(TooltipContentInner, { ...props, ref })
})

TooltipContent.displayName = 'TooltipContent'

// packages/solid/src/components/tooltip-content.gen.ts
import '@prosekit/lit/tooltip-content'

import type { TooltipContentProps as TooltipContentElementProps } from '@prosekit/lit/tooltip-content'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type TooltipContentProps = PropsWithChildren<PropsWithClass<TooltipContentElementProps>>

export const TooltipContent: Component<TooltipContentProps> = (props) => {
  return html`<prosekit-tooltip-content ...${forceProps(props)} />`
}
