// packages/react/src/components/tooltip-trigger.gen.ts
import { createComponent } from '@lit/react'
import { TooltipTrigger as TooltipTriggerElement, type TooltipTriggerProps as TooltipTriggerElementProps } from '@prosekit/lit/tooltip-trigger'
import React from 'react'

import {type PropsWithClassName} from '../types'

export type TooltipTriggerProps = React.PropsWithChildren<PropsWithClassName<TooltipTriggerElementProps>>

const TooltipTriggerInner = createComponent({
  tagName: 'prosekit-tooltip-trigger',
  elementClass: TooltipTriggerElement,
  react: React,
  displayName: 'TooltipTriggerInner',
})

export const TooltipTrigger: React.ComponentType<
  TooltipTriggerProps & React.RefAttributes<TooltipTriggerElement>
> = React.forwardRef((props, ref) => {
  return React.createElement(TooltipTriggerInner, { ...props, ref })
})

TooltipTrigger.displayName = 'TooltipTrigger'

// packages/solid/src/components/tooltip-trigger.gen.ts
import '@prosekit/lit/tooltip-trigger'

import type { TooltipTriggerProps as TooltipTriggerElementProps } from '@prosekit/lit/tooltip-trigger'
import type { Component } from 'solid-js'
import html from 'solid-js/html'

import type { PropsWithClass, PropsWithChildren } from '../types'
import { forceProps } from '../utils/force-props'

export type TooltipTriggerProps = PropsWithChildren<PropsWithClass<TooltipTriggerElementProps>>

export const TooltipTrigger: Component<TooltipTriggerProps> = (props) => {
  return html`<prosekit-tooltip-trigger ...${forceProps(props)} />`
}
