// playground/examples/react/readonly/use-readonly.ts
import { defineReadonly } from 'prosekit/extensions/readonly'
import { useExtension } from 'prosekit/react'
import { useState, useMemo } from 'react'

export function useReadonly() {
  const [readonly, setReadonly] = useState(true)

  const extension = useMemo(() => {
    return readonly ? defineReadonly() : null
  }, [readonly])
  useExtension(extension)

  return { readonly, setReadonly }
}

// registry/src/solid/examples/readonly/use-readonly.ts
import { defineReadonly } from 'prosekit/extensions/readonly'
import { useExtension } from 'prosekit/solid'
import {
  createMemo,
  createSignal,
} from 'solid-js'

export function useReadonly() {
  const [readonly, setReadonly] = createSignal(true)

  const extension = createMemo(() => {
    return readonly() ? defineReadonly() : null
  })
  useExtension(extension)

  return { readonly, setReadonly }
}
