// registry/src/svelte/ui/image-upload-popover/image-upload-popover.svelte
<script lang="ts">
import type { Uploader } from 'prosekit/extensions/file'
import type { ImageExtension } from 'prosekit/extensions/image'
import { useEditor } from 'prosekit/svelte'
import { OpenChangeEvent, PopoverPopup, PopoverPositioner, PopoverRoot, PopoverTrigger } from 'prosekit/svelte/popover'

import { Button } from '../button'

interface Props {
  uploader: Uploader<string>
  tooltip: string
  disabled: boolean
  children?: import('svelte').Snippet
}

const props: Props = $props()

let open = $state(false)
let url = $state('')
let file = $state<File | null>(null)
const ariaId = $props.id()

const editor = useEditor<ImageExtension>()

function handleFileChange(event: Event) {
  const target = event.target as HTMLInputElement
  const selectedFile = target.files?.[0]

  if (selectedFile) {
    file = selectedFile
    url = ''
  } else {
    file = null
  }
}

function handleUrlChange(event: Event) {
  const target = event.target as HTMLInputElement
  const inputUrl = target.value

  if (inputUrl) {
    url = inputUrl
    file = null
  } else {
    url = ''
  }
}

function deferResetState() {
  setTimeout(() => {
    url = ''
    file = null
  }, 300)
}

function handleSubmit() {
  if (url) {
    $editor.commands.insertImage({ src: url })
  } else if (file) {
    $editor.commands.uploadImage({ file, uploader: props.uploader })
  }
  open = false
  deferResetState()
}

function handleOpenChange(event: OpenChangeEvent) {
  if (!event.detail) {
    deferResetState()
  }
  open = event.detail
}
</script>

<PopoverRoot {open} onOpenChange={handleOpenChange}>
  <PopoverTrigger>
    <Button pressed={open} disabled={props.disabled} tooltip={props.tooltip}>
      {@render props.children?.()}
    </Button>
  </PopoverTrigger>

  <PopoverPositioner placement='bottom' class="CSS_IMAGE_UPLOAD_POSITIONER"><PopoverPopup class="CSS_IMAGE_UPLOAD_CARD">
      {#if !file}
        <label for="id-link-{ariaId}">Embed Link</label>
        <input
          id="id-link-{ariaId}"
          class="CSS_IMAGE_UPLOAD_INPUT"
          placeholder="Paste the image link..."
          type="url"
          value={url}
          oninput={handleUrlChange}
        />
      {/if}

      {#if !url}
        <label for="id-upload-{ariaId}">Upload</label>
        <input
          id="id-upload-{ariaId}"
          class="CSS_IMAGE_UPLOAD_INPUT"
          accept="image/*"
          type="file"
          onchange={handleFileChange}
        />
      {/if}

      {#if url}
        <button class="CSS_IMAGE_UPLOAD_BUTTON" onclick={handleSubmit}>
          Insert Image
        </button>
      {/if}

      {#if file}
        <button class="CSS_IMAGE_UPLOAD_BUTTON" onclick={handleSubmit}>
          Upload Image
        </button>
      {/if}
    </PopoverPopup></PopoverPositioner>
</PopoverRoot>

// registry/src/vue/ui/image-upload-popover/image-upload-popover.vue
<script setup lang="ts">
import type { Uploader } from 'prosekit/extensions/file'
import type { ImageExtension } from 'prosekit/extensions/image'
import { useEditor } from 'prosekit/vue'
import { OpenChangeEvent, PopoverPopup, PopoverPositioner, PopoverRoot, PopoverTrigger } from 'prosekit/vue/popover'
import { ref, useId } from 'vue'

import { Button } from '../button'

const props = defineProps<{
  uploader: Uploader<string>
  tooltip: string
  disabled: boolean
}>()

const open = ref(false)
const url = ref('')
const file = ref<File | null>(null)
const ariaId = useId()

const editor = useEditor<ImageExtension>()

function handleFileChange(event: Event) {
  const target = event.target as HTMLInputElement
  const selectedFile = target.files?.[0]

  if (selectedFile) {
    file.value = selectedFile
    url.value = ''
  } else {
    file.value = null
  }
}

function handleUrlChange(event: Event) {
  const target = event.target as HTMLInputElement
  const inputUrl = target.value

  if (inputUrl) {
    url.value = inputUrl
    file.value = null
  } else {
    url.value = ''
  }
}

function deferResetState() {
  setTimeout(() => {
    url.value = ''
    file.value = null
  }, 300)
}

function handleSubmit() {
  if (url.value) {
    editor.value.commands.insertImage({ src: url.value })
  } else if (file.value) {
    editor.value.commands.uploadImage({ file: file.value, uploader: props.uploader })
  }
  open.value = false
  deferResetState()
}

function handleOpenChange(event: OpenChangeEvent) {
  if (!event.detail) {
    deferResetState()
  }
  open.value = event.detail
}
</script>

<template>
  <PopoverRoot :open="open" @open-change="handleOpenChange">
    <PopoverTrigger>
      <Button :pressed="open" :disabled="props.disabled" :tooltip="props.tooltip">
        <slot />
      </Button>
    </PopoverTrigger>

    <PopoverPositioner placement='bottom' class="CSS_IMAGE_UPLOAD_POSITIONER"><PopoverPopup class="CSS_IMAGE_UPLOAD_CARD">
        <label v-if="!file" :for="`id-link-${ariaId}`">Embed Link</label>
        <input
          v-if="!file"
          :id="`id-link-${ariaId}`"
          class="CSS_IMAGE_UPLOAD_INPUT"
          placeholder="Paste the image link..."
          type="url"
          :value="url"
          @input="handleUrlChange"
        />

        <label v-if="!url" :for="`id-upload-${ariaId}`">Upload</label>
        <input
          v-if="!url"
          :id="`id-upload-${ariaId}`"
          class="CSS_IMAGE_UPLOAD_INPUT"
          accept="image/*"
          type="file"
          @change="handleFileChange"
        />

        <button v-if="url" class="CSS_IMAGE_UPLOAD_BUTTON" @click="handleSubmit">
          Insert Image
        </button>

        <button v-if="file" class="CSS_IMAGE_UPLOAD_BUTTON" @click="handleSubmit">
          Upload Image
        </button>
      </PopoverPopup></PopoverPositioner>
  </PopoverRoot>
</template>
