// website/src/shared/vue/image-upload-popover.vue
<script setup lang="ts">
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/vue'
import {
  PopoverContent,
  PopoverRoot,
  PopoverTrigger,
} from 'prosekit/vue/popover'
import {
  computed,
  ref,
} from 'vue'

import Button from './button.vue'
import type { EditorExtension } from './extension'

const props = defineProps<{
  disabled: Boolean
  tooltip: string
}>()

const open = ref(false)
const webUrl = ref('')
const objectUrl = ref('')
const url = computed(() => webUrl.value || objectUrl.value)
const editor = useEditor<EditorExtension>()

function handleFileChange(event: Event) {
  const file = (event.target as HTMLInputElement)?.files?.[0]

  if (file) {
    objectUrl.value = URL.createObjectURL(file)
    webUrl.value = ''
  } else {
    objectUrl.value = ''
  }
}

function handleWebUrlChange(event: Event) {
  const url = (event.target as HTMLInputElement)?.value

  if (url) {
    webUrl.value = url
    objectUrl.value = ''
  } else {
    webUrl.value = ''
  }
}

function deferResetState() {
  setTimeout(() => {
    webUrl.value = ''
    objectUrl.value = ''
  }, 300)
}

function handleSubmit() {
  editor.value.commands.insertImage({ src: url.value })
  deferResetState()
  open.value = false
}

function handleOpenChange(openValue: boolean) {
  if (!openValue) {
    deferResetState()
  }
  open.value = openValue
}
</script>

<template>
  <PopoverRoot :open="open" @open-change="handleOpenChange">
    <PopoverTrigger>
      <Button
        :pressed="open"
        :disabled="props.disabled"
        :tooltip="props.tooltip"
      >
        <slot />
      </Button>
    </PopoverTrigger>

    <PopoverContent class="CSS_IMAGE_UPLOAD_CARD">
      <template v-if="!objectUrl">
        <label>Embed Link</label>
        <input
          class="CSS_IMAGE_UPLOAD_INPUT"
          placeholder="Paste the image link..."
          type="url"
          :value="webUrl"
          @input="handleWebUrlChange"
        />
      </template>
      <template v-if="!webUrl">
        <label>Upload</label>
        <input
          class="CSS_IMAGE_UPLOAD_INPUT"
          accept="image/*"
          type="file"
          @input="handleFileChange"
        />
      </template>
      <button
        v-if="url"
        class="CSS_IMAGE_UPLOAD_BUTTON"
        @click="handleSubmit"
      >
        Insert Image
      </button>
    </PopoverContent>
  </PopoverRoot>
</template>

// website/src/examples/svelte/full/image-upload-popover.svelte
<script lang="ts">
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/svelte'
import {
  PopoverContent,
  PopoverRoot,
  PopoverTrigger,
} from 'prosekit/svelte/popover'
import Button from './button.svelte'
import type { EditorExtension } from './extension'

export let disabled: boolean
export let tooltip: string

let open = false
let webUrl = ''
let objectUrl = ''
$: url = webUrl || objectUrl
const editor = useEditor<EditorExtension>()

const handleFileChange = (event: Event) => {
  const file = (event.target as HTMLInputElement)?.files?.[0]

  if (file) {
    objectUrl = URL.createObjectURL(file)
    webUrl = ''
  } else {
    objectUrl = ''
  }
}

const handleWebUrlChange = (event: Event) => {
  const url = (event.target as HTMLInputElement)?.value

  if (url) {
    webUrl = url
    objectUrl = ''
  } else {
    webUrl = ''
  }
}

const deferResetState = () => {
  setTimeout(() => {
    webUrl = ''
    objectUrl = ''
  }, 300)
}

const handleSubmit = () => {
  $editor.commands.insertImage({ src: url })
  deferResetState()
  open = false
}

const handleOpenChange = (openValue: boolean) => {
  if (!openValue) {
    deferResetState()
  }
  open = openValue
}
</script>

<PopoverRoot {open} on:OpenChange={handleOpenChange}>
  <PopoverTrigger>
    <Button pressed={open} {disabled} {tooltip}>
      <slot />
    </Button>
  </PopoverTrigger>

  <PopoverContent class="CSS_IMAGE_UPLOAD_CARD">
    {#if !objectUrl}
      <label for="embed-link-input">Embed Link</label>
      <input
        class="CSS_IMAGE_UPLOAD_INPUT"
        placeholder="Paste the image link..."
        type="url"
        value={webUrl}
        on:input={handleWebUrlChange}
        id="embed-link-input"
      />
    {/if}
    {#if !webUrl}
      <label for="upload-input">Upload</label>
      <input
        class="CSS_IMAGE_UPLOAD_INPUT"
        accept="image/*"
        type="file"
        on:input={handleFileChange}
      />
    {/if}
    {#if url}
      <button class="CSS_IMAGE_UPLOAD_BUTTON" on:click={handleSubmit}>
        Insert Image
      </button>
    {/if}
  </PopoverContent>
</PopoverRoot>
