// playground/examples/react-user-menu/TagMenu.tsx
import type { MentionAttrs } from 'prosekit/extensions/mention'
import { useEditor } from 'prosekit/react'
import { AutocompleteEmpty } from 'prosekit/react/autocomplete-empty'
import { AutocompleteItem } from 'prosekit/react/autocomplete-item'
import { AutocompleteList } from 'prosekit/react/autocomplete-list'
import { AutocompletePopover } from 'prosekit/react/autocomplete-popover'

import type { ExampleExtension } from './extension'
import { tags } from './tags'

export default function TagMenu() {
  const editor = useEditor<ExampleExtension>()

  const handleTagInsert = (id: number, label: string) => {
    const attrs: MentionAttrs = {
      id: id.toString(),
      value: '#' + label,
      kind: 'tag',
    }
    const node = editor.schema.nodes.mention.create(attrs)
    editor.commands.insertNode({ node })
    editor.commands.insertText({ text: ' ' })
  }

  return (
    <AutocompletePopover editor={editor} regex={/#[\da-z]*$/i}>
      <AutocompleteList editor={editor} className="SLASH_MENU">
        <AutocompleteEmpty className="SLASH_MENU_ITEM">
          No Tag match
        </AutocompleteEmpty>

        {tags.map((tag) => (
          <AutocompleteItem
            key={tag.id}
            className="SLASH_MENU_ITEM"
            onSelect={() => handleTagInsert(tag.id, tag.label)}
          >
            #{tag.label}
          </AutocompleteItem>
        ))}
      </AutocompleteList>
    </AutocompletePopover>
  )
}

// website/components/demo-editor/tag-menu.tsx
import type { MentionAttrs } from 'prosekit/extensions/mention'
import { AutocompleteEmpty } from 'prosekit/vue/autocomplete-empty'
import { AutocompleteItem } from 'prosekit/vue/autocomplete-item'
import { AutocompleteList } from 'prosekit/vue/autocomplete-list'
import { AutocompletePopover } from 'prosekit/vue/autocomplete-popover'
import { defineComponent } from 'vue'

import { tags } from './tags'
import { useExampleEditor } from './use-example-editor'

export const TagMenu = defineComponent({
  name: 'TagMenu',
  setup() {
    const editor = useExampleEditor()

    const handleTagInsert = (id: number, label: string) => {
      const attrs: MentionAttrs = {
        id: id.toString(),
        value: '#' + label,
        kind: 'tag',
      }
      const node = editor.schema.nodes.mention.create(attrs)
      editor.commands.insertNode({ node })
      editor.commands.insertText({ text: ' ' })
    }

    return () => (
      <AutocompletePopover editor={editor} regex={/#[\da-z]*$/i}>
        <AutocompleteList editor={editor} class="SLASH_MENU">
          <AutocompleteEmpty class="SLASH_MENU_ITEM">
            No Tag match
          </AutocompleteEmpty>
          {tags.map((tag) => (
            <AutocompleteItem
              class="SLASH_MENU_ITEM"
              onSelect={() => handleTagInsert(tag.id, tag.label)}
            >
              {tag.label}
            </AutocompleteItem>
          ))}
        </AutocompleteList>
      </AutocompletePopover>
    )
  },
})
