// playground/examples/react-inline-menu/ToggleButton.tsx
import React from 'react'

export default function ToggleButton({
  active,
  available,
  onChange,
  children,
}: {
  active?: boolean
  available: boolean
  onChange: () => void
  children: React.ReactNode
}) {
  return (
    <button
      data-state={active ? 'on' : 'off'}
      onMouseDown={(event) => event.preventDefault()}
      onClick={() => onChange()}
      disabled={!available}
      className="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}

// website/components/demo-editor/toggle-button.tsx
import { defineComponent } from 'vue'

export const ToggleButton = defineComponent<{
  active?: boolean
  available: boolean
  onChange: VoidFunction
}>((props, { slots }) => {
  return () => (
    <button
      class="TOGGLE_BUTTON"
      disabled={!props.available}
      data-state={props.active ? 'on' : 'off'}
      onClick={() => props.onChange?.()}
      onMousedown={(event: MouseEvent) => event.preventDefault()}
    >
      {slots.default?.()}
    </button>
  )
})
