// playground/examples/react-readonly/toolbar.tsx
import Toggle from './toggle'
import { useReadonly } from './use-readonly'

export default function Toolbar() {
  const { readonly, toggleReadonly } = useReadonly()

  return (
    <div className="TOOLBAR">
      <Toggle available={true} active={readonly} onChange={toggleReadonly}>
        Readonly
      </Toggle>

      <Toggle available={true} active={!readonly} onChange={toggleReadonly}>
        Editable
      </Toggle>
    </div>
  )
}

// playground/examples/vue-readonly/toolbar.vue
<script setup lang="ts">
import Toggle from './toggle.vue'
import { useReadonly } from './use-readonly'

const { readonly, toggleReadonly } = useReadonly()
</script>

<template>
  <div class="TOOLBAR">
    <Toggle :available="true" :active="readonly" :onChange="toggleReadonly">
      Readonly
    </Toggle>

    <Toggle :available="true" :active="!readonly" :onChange="toggleReadonly">
      Editable
    </Toggle>
  </div>
</template>
