// playground/examples/react/user-menu-dynamic/use-user-query.ts
import {
  useEffect,
  useState,
} from 'react'

import { users as allUsers } from './user-data'

/**
 * Simulate a user searching with some delay.
 */
export function useUserQuery(query: string, enabled: boolean) {
  const [users, setUsers] = useState<{ name: string; id: number }[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!enabled) {
      setUsers([])
      return
    }

    setLoading(true)

    const searchQuery = query.toLowerCase()

    const id = setTimeout(async () => {
      await waitForTestBlocking()

      setLoading(false)

      setUsers(
        allUsers
          .filter((user) => user.name.toLowerCase().includes(searchQuery))
          .slice(0, 10),
      )
    }, 500)

    return () => {
      clearTimeout(id)
    }
  }, [enabled, query])

  return { loading, users }
}

/**
 * Use a global variable to simulate a network request delay.
 */
async function waitForTestBlocking() {
  return await new Promise((resolve) => {
    const id = setInterval(() => {
      const hasTestBlocking = !!(window as any)._PROSEKIT_TEST_BLOCKING
      if (!hasTestBlocking) {
        clearInterval(id)
        resolve(true)
      }
    }, 100)
  })
}

// registry/src/solid/examples/user-menu-dynamic/use-user-query.ts
import {
  createEffect,
  createSignal,
} from 'solid-js'

import type { User } from '../../sample/sample-query-users'
import { queryUsers } from '../../sample/sample-query-users'

/**
 * Simulate a user searching with some delay.
 */
export function useUserQuery(
  getQuery: () => string,
  getEnabled: () => boolean,
) {
  const [users, setUsers] = createSignal<User[]>([])
  const [loading, setLoading] = createSignal(true)

  createEffect(() => {
    const query = getQuery()
    const enabled = getEnabled()

    if (!enabled) {
      setUsers([])
      return
    }

    setLoading(true)
    let cancelled = false

    void queryUsers(query).then((filteredUsers) => {
      if (cancelled) {
        return
      }
      setUsers(filteredUsers)
      setLoading(false)
    })

    return () => {
      cancelled = true
    }
  })

  return { loading, users }
}
