// registry/src/react/examples/user-menu-dynamic/use-user-query.ts
import {
  useEffect,
  useState,
} from 'react'

import type { User } from '../../sample/query-users'
import { queryUsers } from '../../sample/query-users'

/**
 * Simulate a user searching with some delay.
 */
export function useUserQuery(query: string, enabled: boolean) {
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(true)

  if (!enabled && users.length > 0) {
    setUsers([])
  }

  useEffect(() => {
    if (!enabled) {
      return
    }

    let cancelled = false

    void (async () => {
      setLoading(true)
      const filteredUsers = await queryUsers(query)
      if (cancelled) {
        return
      }
      setUsers(filteredUsers)
      setLoading(false)
    })()

    return () => {
      cancelled = true
    }
  }, [enabled, query])

  return { loading, users }
}

// registry/src/solid/examples/user-menu-dynamic/use-user-query.ts
import {
  createEffect,
  createSignal,
} from 'solid-js'

import type { User } from '../../sample/sample-query-users'
import { queryUsers } from '../../sample/sample-query-users'

/**
 * Simulate a user searching with some delay.
 */
export function useUserQuery(
  getQuery: () => string,
  getEnabled: () => boolean,
) {
  const [users, setUsers] = createSignal<User[]>([])
  const [loading, setLoading] = createSignal(true)

  createEffect(() => {
    const query = getQuery()
    const enabled = getEnabled()

    if (!enabled) {
      setUsers([])
      return
    }

    setLoading(true)
    let cancelled = false

    void queryUsers(query).then((filteredUsers) => {
      if (cancelled) {
        return
      }
      setUsers(filteredUsers)
      setLoading(false)
    })

    return () => {
      cancelled = true
    }
  })

  return { loading, users }
}
