// playground/examples/react-inline-menu/InlineButtons.tsx
import { useEditor } from 'prosekit/react'

import type { EditorExtension } from './extension'

export default function InlineButtons() {
  const editor = useEditor<EditorExtension>({ update: true })

  return (
    <>
      <button
        data-state={editor.marks.bold.isActive() ? 'on' : 'off'}
        onClick={() => editor.commands.toggleBold()}
        onMouseDown={(event) => event.preventDefault()}
        className="TOGGLE_BUTTON"
      >
        Bold
      </button>
      <button
        data-state={editor.marks.italic.isActive() ? 'on' : 'off'}
        onClick={() => editor.commands.toggleItalic()}
        onMouseDown={(event) => event.preventDefault()}
        className="TOGGLE_BUTTON"
      >
        Italic
      </button>
      <button
        data-state={editor.marks.underline.isActive() ? 'on' : 'off'}
        onClick={() => editor.commands.toggleUnderline()}
        onMouseDown={(event) => event.preventDefault()}
        className="TOGGLE_BUTTON"
      >
        Underline
      </button>
    </>
  )
}

// playground/examples/vue-inline-menu/inline-buttons.vue
<script setup lang="ts">
import { useEditor } from 'prosekit/vue'
import type { EditorExtension } from './extension'
import Button from './button.vue'

const editor = useEditor<EditorExtension>({ update: true })
</script>

<template>
  <Button
    :pressed="editor.marks.bold.isActive()"
    @click="editor.commands.toggleBold()"
  >
    Bold
  </Button>

  <Button
    :pressed="editor.marks.italic.isActive()"
    @click="editor.commands.toggleItalic()"
  >
    Italic
  </Button>

  <Button
    :pressed="editor.marks.underline.isActive()"
    @click="editor.commands.toggleUnderline()"
  >
    Underline
  </Button>
</template>
