// packages/react/src/hooks/use-extension.ts
import { Extension } from '@prosekit/core'
import { useEffect } from 'react'

import { useEditor } from './use-editor'

interface UseExtensionProps<T extends Extension = Extension> {
  extension: T
}

export function useExtension({ extension }: UseExtensionProps) {
  const editor = useEditor()
  useEffect(() => editor.use(extension), [editor, extension])
}

// packages/solid/src/hooks/use-extension.ts
import { type Extension } from '@prosekit/core'
import { onCleanup, onMount } from 'solid-js'

import { useEditor } from './use-editor'

interface UseExtensionProps<T extends Extension = Extension> {
  extension: T
}

export function useExtension({ extension }: UseExtensionProps) {
  const editor = useEditor()

  onMount(() => {
    const cleanup = editor().use(extension)
    onCleanup(cleanup)
  })
}
