// packages/react/src/components/view-renderer.ts
import { union, type Editor } from '@prosekit/core'
import { useReactRenderer } from '@prosemirror-adapter/react'
import { createElement, Fragment, useMemo, type ComponentType, type ReactNode } from 'react'

import { defineReactMarkViewFactory } from '../extensions/react-mark-view.ts'
import { defineReactNodeViewFactory } from '../extensions/react-node-view.ts'
import { useEditorExtension } from '../hooks/use-editor-extension.ts'

interface ViewRendererProps {
  editor: Editor
  children: ReactNode
}

export const ViewRenderer: ComponentType<ViewRendererProps> = ({ editor, children }): ReactNode => {
  const { renderReactRenderer, removeReactRenderer, render } = useReactRenderer()

  const extension = useMemo(() => {
    return union([
      defineReactMarkViewFactory(renderReactRenderer, removeReactRenderer),
      defineReactNodeViewFactory(renderReactRenderer, removeReactRenderer),
    ])
  }, [renderReactRenderer, removeReactRenderer])

  useEditorExtension(editor, extension)

  return createElement(Fragment, null, createElement(Fragment, null, children), createElement(Fragment, null, render()))
}

// packages/svelte/src/components/view-renderer/view-renderer.svelte
<script lang="ts">
import { union, type Editor } from '@prosekit/core'
import { useSvelteRenderer } from '@prosemirror-adapter/svelte'
import { getAllContexts } from 'svelte'
import { readable } from 'svelte/store'
import { defineSvelteMarkViewFactory } from '../../extensions/svelte-mark-view.ts'
import { defineSvelteNodeViewFactory } from '../../extensions/svelte-node-view.ts'
import { useEditorExtension } from '../../hooks/use-editor-extension.ts'

export let editor: Editor

const { renderSvelteRenderer, removeSvelteRenderer } = useSvelteRenderer()
const context = getAllContexts()

const extension = union([
  defineSvelteMarkViewFactory(renderSvelteRenderer, removeSvelteRenderer, context),
  defineSvelteNodeViewFactory(renderSvelteRenderer, removeSvelteRenderer, context),
])

useEditorExtension(editor, readable(extension))
</script>

<slot />
