// packages/react/src/hooks/use-editor-extension.ts
import { Editor, EditorNotFoundError, type Extension } from '@prosekit/core'
import { useEffect } from 'react'

/**
 * @internal
 */
export function useEditorExtension(
  editor: Editor | null | undefined,
  extension: Extension | null,
) {
  if (!editor) {
    throw new EditorNotFoundError()
  }

  useEffect(() => {
    if (extension) {
      return editor.use(extension)
    }
  }, [editor, extension])
}

// packages/lit/src/controllers/use-editor-extension.ts
import { type Editor, type Extension } from '@prosekit/core'
import type { ReactiveControllerHost } from 'lit'

import type { WithEditor } from '../types/with-editor'

/**
 * @internal 
 */
export function useEditorExtension(
  host: WithEditor<ReactiveControllerHost>,
  extension: Extension,
) {
  let cleanup: VoidFunction | undefined
  let editor: Editor | undefined | null

  const update = () => {
    cleanup?.()
    cleanup = editor?.use(extension)
  }

  const hostConnected = () => {
    editor = host.editor
    update()
  }

  const hostUpdated = () => {
    const newEditor = host.editor
    if (editor !== newEditor) {
      editor = newEditor
      update()
    }
  }

  const hostDisconnected = () => {
    cleanup?.()
    cleanup = undefined
  }

  host.addController({
    hostConnected,
    hostDisconnected,
    hostUpdated,
  })
}
