// playground/examples/solid-heading/toggle.tsx
import type { ParentProps } from 'solid-js'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  children,
}: ParentProps<{
  pressed: () => boolean
  disabled?: () => boolean
  onClick: () => void
}>) {
  return (
    <button
      data-state={pressed() ? 'on' : 'off'}
      disabled={disabled?.()}
      onClick={() => onClick()}
      onMouseDown={(event) => event.preventDefault()}
      class="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}

// playground/examples/react-code-block/toggle.tsx
import type { ReactNode } from 'react'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  children,
}: {
  pressed: boolean
  disabled?: boolean
  onClick: VoidFunction
  children: ReactNode
}) {
  return (
    <button
      data-state={pressed ? 'on' : 'off'}
      disabled={disabled}
      onClick={() => onClick()}
      onMouseDown={(event) => event.preventDefault()}
      className="TOGGLE_BUTTON"
    >
      {children}
    </button>
  )
}
