// playground/examples/react/loaders.gen.ts
// This file is generated from gen-playground-pages.ts
import { lazy } from 'react'

export const loaders = {
  'minimal': lazy(() => import('./minimal/editor')),
  'block-handle': lazy(() => import('./block-handle/editor')),
  'blockquote': lazy(() => import('./blockquote/editor')),
  'change-tracking': lazy(() => import('./change-tracking/editor')),
  'code-block': lazy(() => import('./code-block/editor')),
  'code-block-themes': lazy(() => import('./code-block-themes/editor')),
  'full': lazy(() => import('./full/editor')),
  'gap-cursor': lazy(() => import('./gap-cursor/editor')),
  'heading': lazy(() => import('./heading/editor')),
  'horizontal-rule': lazy(() => import('./horizontal-rule/editor')),
  'image-view': lazy(() => import('./image-view/editor')),
  'inline-menu': lazy(() => import('./inline-menu/editor')),
  'keymap': lazy(() => import('./keymap/editor')),
  'link': lazy(() => import('./link/editor')),
  'list': lazy(() => import('./list/editor')),
  'loro': lazy(() => import('./loro/editor')),
  'mark-rule': lazy(() => import('./mark-rule/editor')),
  'placeholder': lazy(() => import('./placeholder/editor')),
  'readonly': lazy(() => import('./readonly/editor')),
  'save-html': lazy(() => import('./save-html/editor')),
  'save-json': lazy(() => import('./save-json/editor')),
  'save-markdown': lazy(() => import('./save-markdown/editor')),
  'search': lazy(() => import('./search/editor')),
  'slash-menu': lazy(() => import('./slash-menu/editor')),
  'table': lazy(() => import('./table/editor')),
  'toolbar': lazy(() => import('./toolbar/editor')),
  'unmount': lazy(() => import('./unmount/editor')),
  'user-menu': lazy(() => import('./user-menu/editor')),
  'user-menu-dynamic': lazy(() => import('./user-menu-dynamic/editor')),
  'word-counter': lazy(() => import('./word-counter/editor')),
  'yjs': lazy(() => import('./yjs/editor')),
}

// playground/src/examples/solid/loaders.gen.ts
// This file is generated from gen-playground-pages.ts
import { lazy } from 'solid-js'

export const loaders = {
  'minimal': lazy(() => import('./minimal/editor')),
  'code-block': lazy(() => import('./code-block/editor')),
  'drop-cursor': lazy(() => import('./drop-cursor/editor')),
  'heading': lazy(() => import('./heading/editor')),
  'keymap': lazy(() => import('./keymap/editor')),
  'link-mark-view': lazy(() => import('./link-mark-view/editor')),
  'readonly': lazy(() => import('./readonly/editor')),
  'slash-menu': lazy(() => import('./slash-menu/editor')),
  'text-align': lazy(() => import('./text-align/editor')),
}
