// playground/src/components/ui/demo/dropdown-menu-item.svelte
<script lang="ts">
import { DropdownMenu } from 'bits-ui'

const props: DropdownMenu.ItemProps = $props()
</script>

<DropdownMenu.Item
  class="flex h-8 select-none items-center rounded py-3 pl-3 pr-1.5 text-sm outline-none ring-transparent data-[highlighted]:bg-muted"
  {...props}
>
  {@render props.children?.()}
</DropdownMenu.Item>

// website/components/dropdown-menu/dropdown-menu-item.tsx
import { DropdownMenuItem as RadixDropdownMenuItem } from 'radix-vue'
import { defineComponent } from 'vue'

export const DropdownMenuItem = defineComponent((props, { slots }) => {
  return () => (
    <RadixDropdownMenuItem class="relative flex w-full select-none items-center justify-between rounded px-2 py-1.5 text-sm outline-none transition focus:bg-[--vp-c-default-soft] focus:text-[--vp-c-brand-1]">
      {slots.default?.()}
    </RadixDropdownMenuItem>
  )
})
