// packages/react/src/contexts/editor-context.ts
import type { Editor, Extension } from '@prosekit/core'
import { createContext, useContext } from 'react'


const editorContext = createContext<Editor | null>(null)

/**
 * @internal
 */
export function useEditorContext<E extends Extension>(): Editor<E> | null {
  return useContext(editorContext)
}

/**
 * @internal
 */
export const EditorContextProvider = editorContext.Provider

// packages/solid/src/contexts/editor-context.ts
import type {
  Editor,
  Extension,
} from '@prosekit/core'
import {
  createContext,
  useContext,
} from 'solid-js'

const editorContext = createContext<Editor | null>(null)

/**
 * @internal
 */
export function useEditorContext<E extends Extension>(): Editor<E> | null {
  return useContext(editorContext)
}

/**
 * @internal
 */
export const EditorContextProvider = editorContext.Provider
