// packages/react-binding/src/contexts/editor-context.ts
import { createContext, useContext } from 'react'
import type { Extension } from '@prosekit/core'
import type { Provider } from 'react'

import type { ReactBindingEditor } from '../editor/react-binding-editor.ts'

const EditorContext = createContext<ReactBindingEditor | null>(null)

/**
 * @internal
 */
export function useEditorContext<E extends Extension = any>(): ReactBindingEditor<E> | null {
  return useContext(EditorContext) as ReactBindingEditor<E> | null
}

/**
 * @internal
 */
export const EditorContextProvider: Provider<ReactBindingEditor | null> = EditorContext.Provider

// packages/solid/src/contexts/editor-context.ts
import type {
  Editor,
  Extension,
} from '@prosekit/core'
import {
  createContext,
  useContext,
} from 'solid-js'

const editorContext = createContext<Editor | null>(null)

/**
 * @internal
 */
export function useEditorContext<E extends Extension>(): Editor<E> | null {
  return useContext(editorContext)
}

/**
 * @internal
 */
export const EditorContextProvider = editorContext.Provider
