// playground/examples/react-code-block/toggle.tsx
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/react/tooltip'
import type { ReactNode } from 'react'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  tooltip,
  children,
}: {
  pressed: boolean
  disabled?: boolean
  onClick?: VoidFunction
  tooltip?: string
  children: ReactNode
}) {
  return (
    <TooltipRoot>
      <TooltipTrigger className="TOOLTIP_TRIGGER">
        <button
          data-state={pressed ? 'on' : 'off'}
          disabled={disabled}
          onClick={() => onClick?.()}
          onMouseDown={(event) => event.preventDefault()}
          className="TOGGLE_BUTTON"
        >
          {children}
        </button>
      </TooltipTrigger>
      {tooltip && !disabled ? (
        <TooltipContent offset={4} className="TOOLTIP_CONTENT">
          {tooltip}
        </TooltipContent>
      ) : null}
    </TooltipRoot>
  )
}

// playground/examples/vue-text-align/toggle.vue
<script setup lang="ts">
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/vue/tooltip'

defineProps<{
  pressed: Boolean
  disabled?: Boolean
  tooltip?: string
  onClick?: VoidFunction
}>()
</script>

<template>
  <TooltipRoot>
    <TooltipTrigger className="TOOLTIP_TRIGGER">
      <button
        :data-state="pressed ? 'on' : 'off'"
        :disabled="disabled ? true : undefined"
        @click="onClick"
        @mousedown.prevent
        class="TOGGLE_BUTTON"
      >
        <slot></slot>
      </button>
    </TooltipTrigger>
    <TooltipContent
      v-if="tooltip && !disabled"
      :offset="4"
      className="TOOLTIP_CONTENT"
    >
      {{ tooltip }}
    </TooltipContent>
  </TooltipRoot>
</template>
