// registry/src/preact/ui/image-upload-popover/image-upload-popover.tsx
import type { ComponentChild, JSX } from 'preact'
import { useId, useState } from 'preact/hooks'
import type { Uploader } from 'prosekit/extensions/file'
import type { ImageExtension } from 'prosekit/extensions/image'
import { useEditor } from 'prosekit/preact'
import type { OpenChangeEvent } from 'prosekit/preact/popover'
import { PopoverPopup, PopoverPositioner, PopoverRoot, PopoverTrigger } from 'prosekit/preact/popover'

import { Button } from '../button'

export default function ImageUploadPopover(props: {
  uploader: Uploader<string>
  tooltip: string
  disabled: boolean
  children: ComponentChild
}) {
  const [open, setOpen] = useState(false)
  const [url, setUrl] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const ariaId = useId()

  const editor = useEditor<ImageExtension>()

  const handleFileChange = (
    event: JSX.TargetedEvent<HTMLInputElement, Event>,
  ) => {
    const file = event.currentTarget.files?.[0]

    if (file) {
      setFile(file)
      setUrl('')
    } else {
      setFile(null)
    }
  }

  const handleUrlChange = (
    event: JSX.TargetedEvent<HTMLInputElement, Event>,
  ) => {
    const url = event.currentTarget.value

    if (url) {
      setUrl(url)
      setFile(null)
    } else {
      setUrl('')
    }
  }

  const deferResetState = () => {
    setTimeout(() => {
      setUrl('')
      setFile(null)
    }, 300)
  }

  const handleSubmit = () => {
    if (url) {
      editor.commands.insertImage({ src: url })
    } else if (file) {
      editor.commands.uploadImage({ file, uploader: props.uploader })
    }
    setOpen(false)
    deferResetState()
  }

  const handleOpenChange = (event: OpenChangeEvent) => {
    if (!event.detail) {
      deferResetState()
    }
    setOpen(event.detail)
  }

  return (
    <PopoverRoot open={open} onOpenChange={handleOpenChange}>
      <PopoverTrigger>
        <Button pressed={open} disabled={props.disabled} tooltip={props.tooltip}>
          {props.children}
        </Button>
      </PopoverTrigger>

      <PopoverPositioner placement="bottom" className="CSS_IMAGE_UPLOAD_POSITIONER">
        <PopoverPopup className="CSS_IMAGE_UPLOAD_CARD">
          {file ? null : (
            <>
              <label htmlFor={`id-link-${ariaId}`}>Embed Link</label>
              <input
                id={`id-link-${ariaId}`}
                className="CSS_IMAGE_UPLOAD_INPUT"
                placeholder="Paste the image link..."
                type="url"
                value={url}
                onChange={handleUrlChange}
              />
            </>
          )}

          {url ? null : (
            <>
              <label htmlFor={`id-upload-${ariaId}`}>Upload</label>
              <input
                id={`id-upload-${ariaId}`}
                className="CSS_IMAGE_UPLOAD_INPUT"
                accept="image/*"
                type="file"
                onChange={handleFileChange}
              />
            </>
          )}

          {url
            ? (
              <button className="CSS_IMAGE_UPLOAD_BUTTON" onClick={handleSubmit}>
                Insert Image
              </button>
            )
            : null}

          {file
            ? (
              <button className="CSS_IMAGE_UPLOAD_BUTTON" onClick={handleSubmit}>
                Upload Image
              </button>
            )
            : null}
        </PopoverPopup>
      </PopoverPositioner>
    </PopoverRoot>
  )
}

// registry/src/solid/ui/image-upload-popover/image-upload-popover.tsx
import type { Uploader } from 'prosekit/extensions/file'
import type { ImageExtension } from 'prosekit/extensions/image'
import { useEditor } from 'prosekit/solid'
import type { OpenChangeEvent } from 'prosekit/solid/popover'
import { PopoverPopup, PopoverPositioner, PopoverRoot, PopoverTrigger } from 'prosekit/solid/popover'
import { createSignal, createUniqueId, Show, type JSX } from 'solid-js'

import { Button } from '../button'

export default function ImageUploadPopover(props: {
  uploader: Uploader<string>
  tooltip: string
  disabled: boolean
  children: JSX.Element
}): JSX.Element {
  const [open, setOpen] = createSignal(false)
  const [url, setUrl] = createSignal('')
  const [file, setFile] = createSignal<File | null>(null)
  const ariaId = createUniqueId()

  const editor = useEditor<ImageExtension>()

  const handleFileChange = (event: Event) => {
    const target = event.target as HTMLInputElement
    const selectedFile = target.files?.[0]

    if (selectedFile) {
      setFile(selectedFile)
      setUrl('')
    } else {
      setFile(null)
    }
  }

  const handleUrlChange = (event: Event) => {
    const target = event.target as HTMLInputElement
    const inputUrl = target.value

    if (inputUrl) {
      setUrl(inputUrl)
      setFile(null)
    } else {
      setUrl('')
    }
  }

  const deferResetState = () => {
    setTimeout(() => {
      setUrl('')
      setFile(null)
    }, 300)
  }

  const handleSubmit = () => {
    if (url()) {
      editor().commands.insertImage({ src: url() })
    } else if (file()) {
      editor().commands.uploadImage({ file: file()!, uploader: props.uploader })
    }
    setOpen(false)
    deferResetState()
  }

  const handleOpenChange = (event: OpenChangeEvent) => {
    if (!event.detail) {
      deferResetState()
    }
    setOpen(event.detail)
  }

  return (
    <PopoverRoot open={open()} onOpenChange={handleOpenChange}>
      <PopoverTrigger>
        <Button pressed={open()} disabled={props.disabled} tooltip={props.tooltip}>
          {props.children}
        </Button>
      </PopoverTrigger>

      <PopoverPositioner placement="bottom" class="CSS_IMAGE_UPLOAD_POSITIONER">
        <PopoverPopup class="CSS_IMAGE_UPLOAD_CARD">
          <Show when={!file()}>
            <label for={`id-link-${ariaId}`}>Embed Link</label>
            <input
              id={`id-link-${ariaId}`}
              class="CSS_IMAGE_UPLOAD_INPUT"
              placeholder="Paste the image link..."
              type="url"
              value={url()}
              onInput={handleUrlChange}
            />
          </Show>

          <Show when={!url()}>
            <label for={`id-upload-${ariaId}`}>Upload</label>
            <input
              id={`id-upload-${ariaId}`}
              class="CSS_IMAGE_UPLOAD_INPUT"
              accept="image/*"
              type="file"
              onChange={handleFileChange}
            />
          </Show>

          <Show when={url()}>
            <button class="CSS_IMAGE_UPLOAD_BUTTON" onClick={handleSubmit}>
              Insert Image
            </button>
          </Show>

          <Show when={file()}>
            <button class="CSS_IMAGE_UPLOAD_BUTTON" onClick={handleSubmit}>
              Upload Image
            </button>
          </Show>
        </PopoverPopup>
      </PopoverPositioner>
    </PopoverRoot>
  )
}
