// playground/examples/react-change-tracking/editor-main.tsx
import 'prosekit/basic/style.css'

import { Themes } from '@prosekit/themes'
import { defineBasicExtension } from 'prosekit/basic'
import { createEditor, union, type NodeJSON } from 'prosekit/core'
import {
  CommitRecorder,
  defineCommitRecorder,
} from 'prosekit/extensions/commit'
import { ProseKit } from 'prosekit/react'
import { useMemo } from 'react'

export default function Editor({
  commitRecorder,
  defaultDoc,
}: {
  commitRecorder: CommitRecorder
  defaultDoc?: NodeJSON
}) {
  const editor = useMemo(() => {
    const extension = union([
      defineBasicExtension(),
      defineCommitRecorder(commitRecorder),
    ])
    return createEditor({ extension, defaultDoc })
  }, [commitRecorder, defaultDoc])

  return (
    <ProseKit editor={editor}>
      <div className={Themes.EDITOR_VIEWPORT}>
        <div className={Themes.EDITOR_SCROLLING}>
          <div ref={editor.mount} className={Themes.EDITOR_CONTENT}></div>
        </div>
      </div>
    </ProseKit>
  )
}

// playground/examples/svelte-change-tracking/editor-main.svelte
<script lang="ts">
import 'prosekit/basic/style.css'

import { Themes } from '@prosekit/themes'
import { defineBasicExtension } from 'prosekit/basic'
import { createEditor, union, type NodeJSON } from 'prosekit/core'
import {
  CommitRecorder,
  defineCommitRecorder,
} from 'prosekit/extensions/commit'
import { ProseKit } from 'prosekit/svelte'

export let commitRecorder: CommitRecorder
export let defaultDoc: NodeJSON

const extension = union([
  defineBasicExtension(),
  defineCommitRecorder(commitRecorder),
])

const editor = createEditor({ extension, defaultDoc })

const mount = (element: HTMLElement) => {
  editor.mount(element)
  return { destroy: () => editor.unmount() }
}
</script>

<ProseKit {editor}>
  <div class={Themes.EDITOR_VIEWPORT}>
    <div class={Themes.EDITOR_SCROLLING}>
      <div use:mount class={Themes.EDITOR_CONTENT}></div>
    </div>
  </div>
</ProseKit>
