// registry/src/svelte/ui/search/search.svelte
<script lang="ts">
import { defineSearchQuery, type SearchCommandsExtension } from 'prosekit/extensions/search'
import { useEditor, useExtension } from 'prosekit/svelte'
import { toStore } from 'svelte/store'

import { Button } from '../button'

interface Props {
  onClose?: () => void
}

const props: Props = $props()

let showReplace = $state(false)
let searchText = $state('')
let replaceText = $state('')
let caseSensitive = $state(false)
let wholeWord = $state(false)
let regexp = $state(false)
let literal = $state(false)

const editor = useEditor<SearchCommandsExtension>()

const extension = $derived(
  searchText
    ? defineSearchQuery({
      search: searchText,
      replace: replaceText,
      caseSensitive,
      wholeWord,
      regexp,
      literal,
    })
    : null,
)

useExtension(toStore(() => extension))

function toggleReplace() {
  showReplace = !showReplace
}

function isPlainEnter(event: KeyboardEvent) {
  return (
    event.key === 'Enter'
    && !event.shiftKey
    && !event.metaKey
    && !event.altKey
    && !event.ctrlKey
    && !event.isComposing
  )
}

function isShiftEnter(event: KeyboardEvent) {
  return (
    event.key === 'Enter'
    && event.shiftKey
    && !event.metaKey
    && !event.altKey
    && !event.ctrlKey
    && !event.isComposing
  )
}

function handleSearchKeyDown(event: KeyboardEvent) {
  if (isPlainEnter(event)) {
    event.preventDefault()
    $editor.commands.findNext()
  } else if (isShiftEnter(event)) {
    event.preventDefault()
    $editor.commands.findPrev()
  }
}

function handleReplaceKeyDown(event: KeyboardEvent) {
  if (isPlainEnter(event)) {
    event.preventDefault()
    $editor.commands.replaceNext()
  } else if (isShiftEnter(event)) {
    event.preventDefault()
    $editor.commands.replaceAll()
  }
}
</script>

<div class="CSS_SEARCH">
  <Button tooltip="Toggle Replace" onClick={toggleReplace}>
    <span
      data-rotate={showReplace ? '' : undefined}
      class="CSS_ICON_CHEVRON_RIGHT CSS_TOGGLE_ROTATE"
    ></span>
  </Button>
  <input
    bind:value={searchText}
    placeholder="Search"
    type="text"
    class="CSS_SEARCH_INPUT"
    onkeydown={handleSearchKeyDown}
  />
  <div class="CSS_SEARCH_CONTROLLER">
    <Button
      tooltip="Previous (Shift Enter)"
      onClick={$editor.commands.findPrev}
    >
      <span class="CSS_ICON_ARROW_LEFT"></span>
    </Button>
    <Button
      tooltip="Next (Enter)"
      onClick={$editor.commands.findNext}
    >
      <span class="CSS_ICON_ARROW_RIGHT"></span>
    </Button>
    <Button tooltip="Close" onClick={props.onClose}>
      <span class="CSS_ICON_CLOSE"></span>
    </Button>
    <Button
      pressed={caseSensitive}
      tooltip="Case Sensitive"
      onClick={() => (caseSensitive = !caseSensitive)}
    >
      <span class="CSS_CASE_SENSITIVE"></span>
    </Button>
    <Button
      pressed={wholeWord}
      tooltip="Whole Word"
      onClick={() => (wholeWord = !wholeWord)}
    >
      <span class="CSS_ICON_WHOLE_WORD"></span>
    </Button>
    <Button
      pressed={regexp}
      tooltip="Regular Expression"
      onClick={() => (regexp = !regexp)}
    >
      <span class="CSS_ICON_REGEXP"></span>
    </Button>
    <Button
      pressed={literal}
      tooltip="Literal Escape Sequences"
      onClick={() => (literal = !literal)}
    >
      <span class="CSS_ICON_LITERAL"></span>
    </Button>
  </div>
  {#if showReplace}
    <input
      bind:value={replaceText}
      placeholder="Replace"
      type="text"
      class="CSS_SEARCH_INPUT"
      onkeydown={handleReplaceKeyDown}
    />
    <div class="CSS_SEARCH_CONTROLLER">
      <Button
        tooltip="Replace (Enter)"
        onClick={$editor.commands.replaceNext}
      >
        Replace
      </Button>
      <Button
        tooltip="Replace All (Shift Enter)"
        onClick={$editor.commands.replaceAll}
      >
        All
      </Button>
    </div>
  {/if}
</div>

// registry/src/vue/ui/search/search.vue
<script setup lang="ts">
import { defineSearchQuery, type SearchCommandsExtension } from 'prosekit/extensions/search'
import { useEditor, useExtension } from 'prosekit/vue'
import { computed, ref } from 'vue'

import { Button } from '../button'

const props = defineProps<{ onClose?: () => void }>()

const showReplace = ref(false)
const searchText = ref('')
const replaceText = ref('')
const caseSensitive = ref(false)
const wholeWord = ref(false)
const regexp = ref(false)
const literal = ref(false)

const editor = useEditor<SearchCommandsExtension>()

const extension = computed(() => {
  if (!searchText.value) {
    return null
  }
  return defineSearchQuery({
    search: searchText.value,
    replace: replaceText.value,
    caseSensitive: caseSensitive.value,
    wholeWord: wholeWord.value,
    regexp: regexp.value,
    literal: literal.value,
  })
})

useExtension(extension)

function toggleReplace() {
  showReplace.value = !showReplace.value
}

function isPlainEnter(event: KeyboardEvent) {
  return (
    event.key === 'Enter'
    && !event.shiftKey
    && !event.metaKey
    && !event.altKey
    && !event.ctrlKey
    && !event.isComposing
  )
}

function isShiftEnter(event: KeyboardEvent) {
  return (
    event.key === 'Enter'
    && event.shiftKey
    && !event.metaKey
    && !event.altKey
    && !event.ctrlKey
    && !event.isComposing
  )
}

function handleSearchKeyDown(event: KeyboardEvent) {
  if (isPlainEnter(event)) {
    event.preventDefault()
    editor.value.commands.findNext()
  } else if (isShiftEnter(event)) {
    event.preventDefault()
    editor.value.commands.findPrev()
  }
}

function handleReplaceKeyDown(event: KeyboardEvent) {
  if (isPlainEnter(event)) {
    event.preventDefault()
    editor.value.commands.replaceNext()
  } else if (isShiftEnter(event)) {
    event.preventDefault()
    editor.value.commands.replaceAll()
  }
}
</script>

<template>
  <div class="CSS_SEARCH">
    <Button tooltip="Toggle Replace" @click="toggleReplace">
      <span
        :data-rotate="showReplace ? '' : undefined"
        class="CSS_ICON_CHEVRON_RIGHT CSS_TOGGLE_ROTATE"
      />
    </Button>
    <input
      v-model="searchText"
      placeholder="Search"
      type="text"
      class="CSS_SEARCH_INPUT"
      @keydown="handleSearchKeyDown"
    >
    <div class="CSS_SEARCH_CONTROLLER">
      <Button
        tooltip="Previous (Shift Enter)"
        @click="editor.commands.findPrev"
      >
        <span class="CSS_ICON_ARROW_LEFT" />
      </Button>
      <Button
        tooltip="Next (Enter)"
        @click="editor.commands.findNext"
      >
        <span class="CSS_ICON_ARROW_RIGHT" />
      </Button>
      <Button tooltip="Close" @click="props.onClose">
        <span class="CSS_ICON_CLOSE" />
      </Button>
      <Button
        :pressed="caseSensitive"
        tooltip="Case Sensitive"
        @click="caseSensitive = !caseSensitive"
      >
        <span class="CSS_CASE_SENSITIVE" />
      </Button>
      <Button
        :pressed="wholeWord"
        tooltip="Whole Word"
        @click="wholeWord = !wholeWord"
      >
        <span class="CSS_ICON_WHOLE_WORD" />
      </Button>
      <Button
        :pressed="regexp"
        tooltip="Regular Expression"
        @click="regexp = !regexp"
      >
        <span class="CSS_ICON_REGEXP" />
      </Button>
      <Button
        :pressed="literal"
        tooltip="Literal Escape Sequences"
        @click="literal = !literal"
      >
        <span class="CSS_ICON_LITERAL" />
      </Button>
    </div>
    <template v-if="showReplace">
      <input
        v-model="replaceText"
        placeholder="Replace"
        type="text"
        class="CSS_SEARCH_INPUT"
        @keydown="handleReplaceKeyDown"
      >
      <div class="CSS_SEARCH_CONTROLLER">
        <Button
          tooltip="Replace (Enter)"
          @click="editor.commands.replaceNext"
        >
          Replace
        </Button>
        <Button
          tooltip="Replace All (Shift Enter)"
          @click="editor.commands.replaceAll"
        >
          All
        </Button>
      </div>
    </template>
  </div>
</template>
