// website/src/examples/react/full/tag-menu.tsx
import { Themes } from '@prosekit/themes'
import { useEditor } from 'prosekit/react'
import {
  AutocompleteEmpty,
  AutocompleteItem,
  AutocompleteList,
  AutocompletePopover,
} from 'prosekit/react/autocomplete'

import type { EditorExtension } from './extension'
import { tags } from './tag-data'

export default function TagMenu() {
  const editor = useEditor<EditorExtension>()

  const handleTagInsert = (id: number, label: string) => {
    editor.commands.insertMention({
      id: id.toString(),
      value: '#' + label,
      kind: 'tag',
    })
    editor.commands.insertText({ text: ' ' })
  }

  return (
    <AutocompletePopover
      regex={/#[\da-z]*$/i}
      className={Themes.AUTOCOMPLETE_MENU}
    >
      <AutocompleteList>
        <AutocompleteEmpty className={Themes.AUTOCOMPLETE_MENU_ITEM}>
          No results
        </AutocompleteEmpty>

        {tags.map((tag) => (
          <AutocompleteItem
            key={tag.id}
            className={Themes.AUTOCOMPLETE_MENU_ITEM}
            onSelect={() => handleTagInsert(tag.id, tag.label)}
          >
            #{tag.label}
          </AutocompleteItem>
        ))}
      </AutocompleteList>
    </AutocompletePopover>
  )
}

// playground/examples/svelte-full/tag-menu.svelte
<script lang="ts">
	import { Themes } from '@prosekit/themes';
	import {
		AutocompleteEmpty,
		AutocompleteItem,
		AutocompleteList,
		AutocompletePopover
	} from 'prosekit/svelte/autocomplete';

	import { useEditor } from 'prosekit/svelte';
	import type { EditorExtension } from './extension';
	import { tags } from './tag-data';

	const editor = useEditor<EditorExtension>();

	const handleTagInsert = (id: number, label: string) => {
		$editor.commands.insertMention({
			id: id.toString(),
			value: '#' + label,
			kind: 'tag'
		});
		$editor.commands.insertText({ text: ' ' });
	};
</script>

<AutocompletePopover regex={/#[\da-z]*$/i} class={Themes.AUTOCOMPLETE_MENU}>
	<AutocompleteList>
		<AutocompleteEmpty class={Themes.AUTOCOMPLETE_MENU_ITEM}>No results</AutocompleteEmpty>
		{#each tags as tag}
			<AutocompleteItem
				class={Themes.AUTOCOMPLETE_MENU_ITEM}
				onSelect={() => handleTagInsert(tag.id, tag.label)}
			>
				{tag.label}
			</AutocompleteItem>
		{/each}
	</AutocompleteList>
</AutocompletePopover>
