// registry/src/solid/examples/keymap/use-submit-keymap.ts
import type { Keymap } from 'prosekit/core'
import { useKeymap } from 'prosekit/solid'
import type { Accessor } from 'solid-js'

export function useSubmitKeymap(
  hotkey: Accessor<'Shift-Enter' | 'Enter'>,
  onSubmit: (hotkey: string) => void,
): void {
  const keymap = () => {
    const currentHotkey = hotkey()
    return {
      [currentHotkey]: () => {
        onSubmit(currentHotkey)
        return true
      },
    } satisfies Keymap
  }

  useKeymap(keymap)
}

// playground/examples/react/keymap/use-submit-keymap.ts
import { type Keymap } from 'prosekit/core'
import { useKeymap } from 'prosekit/react'
import { useMemo } from 'react'

export function useSubmitKeymap(
  hotkey: 'Shift-Enter' | 'Enter',
  onSubmit: (hotkey: string) => void,
) {
  const keymap: Keymap = useMemo(() => {
    return {
      [hotkey]: () => {
        onSubmit(hotkey)
        // Return true to stop further keypress propagation.
        return true
      },
    }
  }, [hotkey, onSubmit])

  useKeymap(keymap)
}
