// playground/examples/vue-list/toggle.vue
<script setup lang="ts">
import { defineProps, type Component } from 'vue'

const props = defineProps<{
  as?: string | Component
  pressed: Boolean
  disabled?: Boolean
  onClick?: VoidFunction
}>()
</script>

<template>
  <component
    :is="props.as || 'button'"
    :data-state="pressed ? 'on' : 'off'"
    :disabled="disabled ? true : undefined"
    @click="onClick"
    @mousedown.prevent
    class="TOGGLE_BUTTON"
  >
    <slot></slot>
  </component>
</template>

// playground/examples/svelte-keymap/toggle.svelte
<script lang="ts">
export let pressed: boolean
export let disabled: boolean = false
export let onClick: VoidFunction
</script>

<button
  data-state={pressed ? 'on' : 'off'}
  disabled={disabled ? true : undefined}
  on:click={onClick}
  on:mousedown|preventDefault
  class="TOGGLE_BUTTON"
>
  <slot />
</button>
