// packages/solid/src/extensions/solid-mark-view.ts
import {
  defineMarkViewComponent,
  defineMarkViewFactory,
  type Extension,
} from '@prosekit/core'
import type { MarkViewConstructor } from '@prosekit/pm/view'
import type { CoreMarkViewUserOptions } from '@prosemirror-adapter/core'
import {
  useMarkViewContext,
  useMarkViewFactory,
  type MarkViewContextProps,
  type SolidMarkViewUserOptions,
} from '@prosemirror-adapter/solid'
import {
  createComponent,
  createMemo,
  type Accessor,
  type Component,
} from 'solid-js'

import { useExtension } from '../hooks/use-extension'

/**
 * @public
 */
export interface SolidMarkViewProps extends MarkViewContextProps {}

/**
 * @public
 */
export type SolidMarkViewComponent = Component<SolidMarkViewProps>

/**
 * Options for {@link defineSolidMarkView}.
 *
 * @public
 */
export interface SolidMarkViewOptions
  extends CoreMarkViewUserOptions<SolidMarkViewComponent> {
  /**
   * The name of the mark type.
   */
  name: string
}

function withMarkViewProps(
  component: SolidMarkViewComponent,
): Component<SolidMarkViewProps> {
  return function MarkViewPropsWrapper() {
    const props: Accessor<SolidMarkViewProps> = useMarkViewContext()

    return createComponent(component, props())
  }
}

/**
 * @internal
 */
export function consumeSolidViews() {
  const markViewFactory = useMarkViewFactory()
  const extension = createMemo(
    () => defineSolidMarkViewFactory(markViewFactory),
    [markViewFactory],
  )

  useExtension(extension)
}

/**
 * Defines a mark view using a Solid component.
 *
 * @public
 */
export function defineSolidMarkView(options: SolidMarkViewOptions): Extension {
  const { name, component, ...userOptions } = options

  const args: SolidMarkViewUserOptions = {
    ...userOptions,
    component: withMarkViewProps(component),
  }

  return defineMarkViewComponent<SolidMarkViewUserOptions>({
    group: 'solid',
    name,
    args,
  })
}

function defineSolidMarkViewFactory(
  factory: (options: SolidMarkViewOptions) => MarkViewConstructor,
) {
  return defineMarkViewFactory<SolidMarkViewOptions>({
    group: 'solid',
    factory,
  })
}

// packages/react/src/extensions/react-mark-view.ts
import { defineMarkViewComponent, defineMarkViewFactory, type Extension } from '@prosekit/core'
import type { MarkViewConstructor } from '@prosekit/pm/view'
import type { CoreMarkViewUserOptions } from '@prosemirror-adapter/core'
import { useMarkViewContext, useMarkViewFactory, type MarkViewContext, type ReactMarkViewUserOptions } from '@prosemirror-adapter/react'
import { createElement, useMemo, type ComponentType, type FC } from 'react'

import { useExtension } from '../hooks/use-extension.ts'

/**
 * @public
 */
export interface ReactMarkViewProps extends MarkViewContext {}

/**
 * @public
 */
export type ReactMarkViewComponent = ComponentType<ReactMarkViewProps>

/**
 * Options for {@link defineReactMarkView}.
 *
 * @public
 */
export interface ReactMarkViewOptions extends CoreMarkViewUserOptions<ReactMarkViewComponent> {
  /**
   * The name of the mark type.
   */
  name: string
}

function withMarkViewProps(component: ReactMarkViewComponent) {
  return function MarkViewPropsWrapper() {
    const props: ReactMarkViewProps = useMarkViewContext()
    return createElement(component, props)
  }
}

/**
 * @internal
 */
export const ReactMarkViewConsumer: FC = () => {
  const markViewFactory = useMarkViewFactory()
  const extension = useMemo(
    () => defineReactMarkViewFactory(markViewFactory),
    [markViewFactory],
  )
  useExtension(extension)

  return null
}

/**
 * Defines a mark view using a React component.
 *
 * @public
 */
export function defineReactMarkView(options: ReactMarkViewOptions): Extension {
  const { name, component, ...userOptions } = options

  const args: ReactMarkViewUserOptions = {
    ...userOptions,
    component: withMarkViewProps(component),
  }

  return defineMarkViewComponent<ReactMarkViewUserOptions>({
    group: 'react',
    name,
    args,
  })
}

function defineReactMarkViewFactory(
  factory: (options: ReactMarkViewUserOptions) => MarkViewConstructor,
) {
  return defineMarkViewFactory<ReactMarkViewUserOptions>({
    group: 'react',
    factory,
  })
}
