// packages/solid/src/extensions/solid-node-view.ts
import {
  defineNodeViewComponent,
  defineNodeViewFactory,
  type BaseNodeViewOptions,
  type Extension,
} from '@prosekit/core'
import type { Attrs, ProseMirrorNode } from '@prosekit/pm/model'
import type {
  EditorView,
  Decoration,
  DecorationSource,
  NodeViewConstructor,
} from '@prosekit/pm/view'
import {
  useNodeViewContext,
  useNodeViewFactory,
  type SolidNodeViewUserOptions,
} from '@prosemirror-adapter/solid'
import {
  createComponent,
  createMemo,
  type Accessor,
  type Component,
} from 'solid-js'

import { useExtension } from '../hooks/use-extension'

/**
 * @public
 */
export interface SolidNodeViewProps {
  // won't change
  contentRef: (node: HTMLElement | null) => void
  view: EditorView
  getPos: () => number | undefined
  setAttrs: (attrs: Attrs) => void

  // changes between updates
  node: ProseMirrorNode
  selected: boolean
  decorations: readonly Decoration[]
  innerDecorations: DecorationSource
}

/**
 * @public
 */
export type SolidNodeViewComponent = Component<SolidNodeViewProps>

/**
 * Options for {@link defineReactNodeView}.
 *
 * @public
 */
export interface SolidNodeViewOptions extends BaseNodeViewOptions {
  /**
   * The name of the node type.
   */
  name: string

  /**
   * The Solid component to render the node.
   */
  component: SolidNodeViewComponent
}

function withNodeViewProps(
  component: SolidNodeViewComponent,
): Component<SolidNodeViewProps> {
  return function NodeViewPropsWrapper() {
    const props: Accessor<SolidNodeViewProps> = useNodeViewContext()

    return createComponent(component, props()) 
  }
}

/**
 * @internal
 */
export const SolidViewsConsumer: Component = () => {
  const nodeViewFactory = useNodeViewFactory()
  const extension = createMemo(
    () => defineSolidNodeViewFactory(nodeViewFactory),
    [nodeViewFactory],
  )

  useExtension(extension)

  return null
}

/**
 * Defines a node view using a Solid component.
 *
 * @public
 */
export function defineSolidNodeView(options: SolidNodeViewOptions): Extension {
  const { name, component, ...userOptions } = options

  const args: SolidNodeViewUserOptions = {
    ...userOptions,
    component: withNodeViewProps(component),
  }

  return defineNodeViewComponent<SolidNodeViewUserOptions>({
    group: 'solid',
    name,
    args,
  })
}

function defineSolidNodeViewFactory(
  factory: (options: SolidNodeViewOptions) => NodeViewConstructor,
) {
  return defineNodeViewFactory<SolidNodeViewOptions>({
    group: 'solid',
    factory,
  })
}

// packages/react/src/extensions/react-node-view.ts
import type { BaseNodeViewOptions, Extension } from '@prosekit/core'
import { defineNodeViewComponent, defineNodeViewFactory } from '@prosekit/core'
import type { Attrs, ProseMirrorNode } from '@prosekit/pm/model'
import type {
  Decoration,
  DecorationSource,
  EditorView,
  NodeViewConstructor,
} from '@prosekit/pm/view'
import type { ReactNodeViewUserOptions } from '@prosemirror-adapter/react'
import {
  useNodeViewContext,
  useNodeViewFactory,
} from '@prosemirror-adapter/react'
import { createElement, useMemo, type ComponentType, type FC } from 'react'

import { useExtension } from '../hooks/use-extension'

/**
 * @public
 */
export interface ReactNodeViewProps {
  // won't change
  contentRef: (node: HTMLElement | null) => void
  view: EditorView
  getPos: () => number | undefined
  setAttrs: (attrs: Attrs) => void

  // changes between updates
  node: ProseMirrorNode
  selected: boolean
  decorations: readonly Decoration[]
  innerDecorations: DecorationSource
}

/**
 * @public
 */
export type ReactNodeViewComponent = ComponentType<ReactNodeViewProps>

/**
 * Options for {@link defineReactNodeView}.
 *
 * @public
 */
export interface ReactNodeViewOptions extends BaseNodeViewOptions {
  /**
   * The name of the node type.
   */
  name: string

  /**
   * The React component to render the node.
   */
  component: ReactNodeViewComponent
}

function withNodeViewProps(component: ReactNodeViewComponent) {
  return function NodeViewPropsWrapper() {
    const props: ReactNodeViewProps = useNodeViewContext()
    return createElement(component, props)
  }
}

/**
 * @internal
 */
export const ReactViewsConsumer: FC = () => {
  const nodeViewFactory = useNodeViewFactory()
  const extension = useMemo(
    () => defineReactNodeViewFactory(nodeViewFactory),
    [nodeViewFactory],
  )
  useExtension(extension)

  return null
}

/**
 * Defines a node view using a React component.
 *
 * @public
 */
export function defineReactNodeView(options: ReactNodeViewOptions): Extension {
  const { name, component, ...userOptions } = options

  const args: ReactNodeViewUserOptions = {
    ...userOptions,
    component: withNodeViewProps(component),
  }

  return defineNodeViewComponent<ReactNodeViewUserOptions>({
    group: 'react',
    name,
    args,
  })
}

function defineReactNodeViewFactory(
  factory: (options: ReactNodeViewUserOptions) => NodeViewConstructor,
) {
  return defineNodeViewFactory<ReactNodeViewUserOptions>({
    group: 'react',
    factory,
  })
}
