// playground/examples/vue-code-block/toggle.vue
<script setup lang="ts">
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/vue/tooltip'

defineProps<{
  pressed: Boolean
  disabled?: Boolean
  tooltip?: string
  onClick?: VoidFunction
}>()
</script>

<template>
  <TooltipRoot>
    <TooltipTrigger :class="Themes.TOOLTIP_TRIGGER">
      <button
        :data-state="pressed ? 'on' : 'off'"
        :disabled="disabled ? true : undefined"
        @click="onClick"
        @mousedown.prevent
        :class="Themes.TOGGLE_BUTTON"
      >
        <slot></slot>
      </button>
    </TooltipTrigger>
    <TooltipContent
      v-if="tooltip && !disabled"
      :offset="4"
      :class="Themes.TOOLTIP_CONTENT"
    >
      {{ tooltip }}
    </TooltipContent>
  </TooltipRoot>
</template>

// playground/examples/react-keymap/toggle.tsx
import { Themes } from '@prosekit/themes'
import {
  TooltipContent,
  TooltipRoot,
  TooltipTrigger,
} from 'prosekit/react/tooltip'
import type { ReactNode } from 'react'

export default function Toggle({
  pressed,
  disabled,
  onClick,
  tooltip,
  children,
}: {
  pressed: boolean
  disabled?: boolean
  onClick?: VoidFunction
  tooltip?: string
  children: ReactNode
}) {
  return (
    <TooltipRoot>
      <TooltipTrigger className={Themes.TOOLTIP_TRIGGER}>
        <button
          data-state={pressed ? 'on' : 'off'}
          disabled={disabled}
          onClick={() => onClick?.()}
          onMouseDown={(event) => event.preventDefault()}
          className={Themes.TOGGLE_BUTTON}
        >
          {children}
        </button>
      </TooltipTrigger>
      {tooltip && !disabled ? (
        <TooltipContent offset={4} className={Themes.TOOLTIP_CONTENT}>
          {tooltip}
        </TooltipContent>
      ) : null}
    </TooltipRoot>
  )
}
