// playground/examples/vue-save-and-restore/event-handlers.vue
<script setup lang="ts">
import { defineDocChangeHandler } from 'prosekit/core'
import { useExtension } from 'prosekit/vue'
import { computed } from 'vue'

const props = defineProps<{
  onDocChange: VoidFunction
}>()

const extension = computed(() => {
  return defineDocChangeHandler(props.onDocChange)
})

useExtension(extension)
</script>

// playground/examples/react-save-and-restore/event-handlers.tsx
import { defineDocChangeHandler } from 'prosekit/core'
import { useExtension } from 'prosekit/react'
import { useMemo } from 'react'

export default function EventHandlers({
  onDocChange,
}: {
  onDocChange: () => void
}) {
  const extension = useMemo(() => {
    return defineDocChangeHandler(onDocChange)
  }, [onDocChange])

  useExtension(extension)

  return null
}
