// registry/src/react/renderer.ts
import type { NodeJSON } from 'prosekit/core'
import type { JSX } from 'react'
import {
  createElement,
  Suspense,
} from 'react'

import { loaders } from './loaders.gen'

interface ExampleProps {
  initialContent?: NodeJSON
}

interface Props {
  story: string
  exampleProps?: ExampleProps
}

export function ReactRenderer(props: Props): JSX.Element {
  const Example = loaders[props.story as keyof typeof loaders]
  if (!Example) {
    console.warn(`[ReactRenderer] No example found for story ${props.story}`)
  }
  const fallback = createElement('div', { 'data-testid': 'react-renderer-fallback' }, null)
  const children = Example ? createElement(Example, props.exampleProps ?? null) : null
  return createElement(Suspense, { fallback }, children)
}

ReactRenderer.displayName = 'ReactRenderer'

// registry/src/lit/renderer.ts
import { LitElement } from 'lit'
import { html, unsafeStatic } from 'lit/static-html.js'
import type { NodeJSON } from 'prosekit/core'

import { loaders } from './loaders.gen.ts'
import { suppressLitWarnings } from './suppress-lit-warnings.ts'

suppressLitWarnings()

interface ExampleProps {
  initialContent?: NodeJSON
}

export class LitRenderer extends LitElement {
  story: string
  exampleProps?: ExampleProps

  override createRenderRoot() {
    return this
  }

  static override properties = {
    story: { type: String },
    exampleProps: { attribute: false },
  }

  constructor() {
    super()
    this.story = ''
  }

  override render() {
    const story = this.story

    if (!story) {
      return html`<p data-testid="lit-renderer-fallback">Loading...</p>`
    }

    const loader = loaders[story as keyof typeof loaders]
    if (!loader) {
      const message = `[LitRenderer] No loader found for story ${story}`
      console.warn(message)
      return html`<p data-testid="lit-renderer-fallback">${message}</p>`
    }

    void loader()
    const tag = unsafeStatic('lit-editor-example-' + story)
    return html`<${tag} .initialContent=${this.exampleProps?.initialContent} style="display: contents;"></${tag}>`
  }
}

export function registerLitRenderer() {
  suppressLitWarnings()
  if (customElements.get('lit-renderer')) return
  customElements.define('lit-renderer', LitRenderer)
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-renderer': LitRenderer
  }
}
