// registry/src/solid/loaders.gen.ts
// This file is generated from update-loader.ts
import { lazy } from 'solid-js'

export const loaders = {
  'block-handle': lazy(() => import('./examples/block-handle').then((m) => ({ default: m.ExampleEditor }))),
  'blockquote': lazy(() => import('./examples/blockquote').then((m) => ({ default: m.ExampleEditor }))),
  'bold': lazy(() => import('./examples/bold').then((m) => ({ default: m.ExampleEditor }))),
  'change-tracking': lazy(() => import('./examples/change-tracking').then((m) => ({ default: m.ExampleEditor }))),
  'code': lazy(() => import('./examples/code').then((m) => ({ default: m.ExampleEditor }))),
  'code-block': lazy(() => import('./examples/code-block').then((m) => ({ default: m.ExampleEditor }))),
  'code-block-themes': lazy(() => import('./examples/code-block-themes').then((m) => ({ default: m.ExampleEditor }))),
  'drop-cursor': lazy(() => import('./examples/drop-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'emoji-rules': lazy(() => import('./examples/emoji-rules').then((m) => ({ default: m.ExampleEditor }))),
  'full': lazy(() => import('./examples/full').then((m) => ({ default: m.ExampleEditor }))),
  'gap-cursor': lazy(() => import('./examples/gap-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'hard-break': lazy(() => import('./examples/hard-break').then((m) => ({ default: m.ExampleEditor }))),
  'heading': lazy(() => import('./examples/heading').then((m) => ({ default: m.ExampleEditor }))),
  'horizontal-rule': lazy(() => import('./examples/horizontal-rule').then((m) => ({ default: m.ExampleEditor }))),
  'image-view': lazy(() => import('./examples/image-view').then((m) => ({ default: m.ExampleEditor }))),
  'inline-menu': lazy(() => import('./examples/inline-menu').then((m) => ({ default: m.ExampleEditor }))),
  'italic': lazy(() => import('./examples/italic').then((m) => ({ default: m.ExampleEditor }))),
  'keymap': lazy(() => import('./examples/keymap').then((m) => ({ default: m.ExampleEditor }))),
  'link': lazy(() => import('./examples/link').then((m) => ({ default: m.ExampleEditor }))),
  'list': lazy(() => import('./examples/list').then((m) => ({ default: m.ExampleEditor }))),
  'list-custom-checkbox': lazy(() => import('./examples/list-custom-checkbox').then((m) => ({ default: m.ExampleEditor }))),
  'minimal': lazy(() => import('./examples/minimal').then((m) => ({ default: m.ExampleEditor }))),
  'placeholder': lazy(() => import('./examples/placeholder').then((m) => ({ default: m.ExampleEditor }))),
  'readonly': lazy(() => import('./examples/readonly').then((m) => ({ default: m.ExampleEditor }))),
  'rtl': lazy(() => import('./examples/rtl').then((m) => ({ default: m.ExampleEditor }))),
  'strike': lazy(() => import('./examples/strike').then((m) => ({ default: m.ExampleEditor }))),
  'table': lazy(() => import('./examples/table').then((m) => ({ default: m.ExampleEditor }))),
  'text-align': lazy(() => import('./examples/text-align').then((m) => ({ default: m.ExampleEditor }))),
  'toolbar': lazy(() => import('./examples/toolbar').then((m) => ({ default: m.ExampleEditor }))),
  'typography': lazy(() => import('./examples/typography').then((m) => ({ default: m.ExampleEditor }))),
  'underline': lazy(() => import('./examples/underline').then((m) => ({ default: m.ExampleEditor }))),
  'unmount': lazy(() => import('./examples/unmount').then((m) => ({ default: m.ExampleEditor }))),
  'view-adapter': lazy(() => import('./examples/view-adapter').then((m) => ({ default: m.ExampleEditor }))),
}

// registry/src/react/loaders.gen.ts
// This file is generated from update-loader.ts
import { lazy } from 'react'

export const loaders = {
  'block-handle': lazy(() => import('./examples/block-handle').then((m) => ({ default: m.ExampleEditor }))),
  'blockquote': lazy(() => import('./examples/blockquote').then((m) => ({ default: m.ExampleEditor }))),
  'bold': lazy(() => import('./examples/bold').then((m) => ({ default: m.ExampleEditor }))),
  'change-tracking': lazy(() => import('./examples/change-tracking').then((m) => ({ default: m.ExampleEditor }))),
  'code': lazy(() => import('./examples/code').then((m) => ({ default: m.ExampleEditor }))),
  'code-block': lazy(() => import('./examples/code-block').then((m) => ({ default: m.ExampleEditor }))),
  'code-block-themes': lazy(() => import('./examples/code-block-themes').then((m) => ({ default: m.ExampleEditor }))),
  'drop-cursor': lazy(() => import('./examples/drop-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'emoji-rules': lazy(() => import('./examples/emoji-rules').then((m) => ({ default: m.ExampleEditor }))),
  'full': lazy(() => import('./examples/full').then((m) => ({ default: m.ExampleEditor }))),
  'gap-cursor': lazy(() => import('./examples/gap-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'hard-break': lazy(() => import('./examples/hard-break').then((m) => ({ default: m.ExampleEditor }))),
  'heading': lazy(() => import('./examples/heading').then((m) => ({ default: m.ExampleEditor }))),
  'horizontal-rule': lazy(() => import('./examples/horizontal-rule').then((m) => ({ default: m.ExampleEditor }))),
  'image-view': lazy(() => import('./examples/image-view').then((m) => ({ default: m.ExampleEditor }))),
  'inline-menu': lazy(() => import('./examples/inline-menu').then((m) => ({ default: m.ExampleEditor }))),
  'italic': lazy(() => import('./examples/italic').then((m) => ({ default: m.ExampleEditor }))),
  'keymap': lazy(() => import('./examples/keymap').then((m) => ({ default: m.ExampleEditor }))),
  'link': lazy(() => import('./examples/link').then((m) => ({ default: m.ExampleEditor }))),
  'link-mark-view': lazy(() => import('./examples/link-mark-view').then((m) => ({ default: m.ExampleEditor }))),
  'list': lazy(() => import('./examples/list').then((m) => ({ default: m.ExampleEditor }))),
  'list-custom-checkbox': lazy(() => import('./examples/list-custom-checkbox').then((m) => ({ default: m.ExampleEditor }))),
  'loro': lazy(() => import('./examples/loro').then((m) => ({ default: m.ExampleEditor }))),
  'mark-rule': lazy(() => import('./examples/mark-rule').then((m) => ({ default: m.ExampleEditor }))),
  'minimal': lazy(() => import('./examples/minimal').then((m) => ({ default: m.ExampleEditor }))),
  'placeholder': lazy(() => import('./examples/placeholder').then((m) => ({ default: m.ExampleEditor }))),
  'readonly': lazy(() => import('./examples/readonly').then((m) => ({ default: m.ExampleEditor }))),
  'save-html': lazy(() => import('./examples/save-html').then((m) => ({ default: m.ExampleEditor }))),
  'save-json': lazy(() => import('./examples/save-json').then((m) => ({ default: m.ExampleEditor }))),
  'save-markdown': lazy(() => import('./examples/save-markdown').then((m) => ({ default: m.ExampleEditor }))),
  'search': lazy(() => import('./examples/search').then((m) => ({ default: m.ExampleEditor }))),
  'select-block': lazy(() => import('./examples/select-block').then((m) => ({ default: m.ExampleEditor }))),
  'slash-menu': lazy(() => import('./examples/slash-menu').then((m) => ({ default: m.ExampleEditor }))),
  'strike': lazy(() => import('./examples/strike').then((m) => ({ default: m.ExampleEditor }))),
  'table': lazy(() => import('./examples/table').then((m) => ({ default: m.ExampleEditor }))),
  'text-align': lazy(() => import('./examples/text-align').then((m) => ({ default: m.ExampleEditor }))),
  'text-color': lazy(() => import('./examples/text-color').then((m) => ({ default: m.ExampleEditor }))),
  'toolbar': lazy(() => import('./examples/toolbar').then((m) => ({ default: m.ExampleEditor }))),
  'typography': lazy(() => import('./examples/typography').then((m) => ({ default: m.ExampleEditor }))),
  'underline': lazy(() => import('./examples/underline').then((m) => ({ default: m.ExampleEditor }))),
  'unmount': lazy(() => import('./examples/unmount').then((m) => ({ default: m.ExampleEditor }))),
  'user-menu': lazy(() => import('./examples/user-menu').then((m) => ({ default: m.ExampleEditor }))),
  'user-menu-dynamic': lazy(() => import('./examples/user-menu-dynamic').then((m) => ({ default: m.ExampleEditor }))),
  'word-counter': lazy(() => import('./examples/word-counter').then((m) => ({ default: m.ExampleEditor }))),
  'yjs': lazy(() => import('./examples/yjs').then((m) => ({ default: m.ExampleEditor }))),
}
